### ISSUE TITLE
Project Roadmap 

### ISSUE THREAD

**Issue by samuelgoldenbaum** [getsentry/sentry-unity#10]
Hi all, thanks for sharing this project. Can we please get a roadmap together. Would be useful to know what is in the works so we don't have duplication of efforts. I have had a look at the SDK and current public methods and would need to add the following:

1. Allow SentryEvent object to be built up and passed to SendMessage. This allows important additional properties to be set before logging - like current user and any custom info.
2. Allow Custom/Exceptions to be manually sent to Sentry in i.e. we may capture exceptions and actively send these to Sentry in something like SendException()

**Comment by bruno-garcia** [comment]
@samuelgoldenbaum thanks for bringing this to us. We don't have a roadmap right now and the points you raised are surely things we need to discuss.
We'll be getting some updates on this soon though.

**Comment by bruno-garcia** [comment]
@samuelgoldenbaum `CaptureEvent` is now in the SDK.
I'll make few more modifications before bumping the version though.

**Comment by bruno-garcia** [comment]
@samuelgoldenbaum please take a look at: https://github.com/getsentry/sentry-unity/issues/15
Since it's based on the full SDK, you can `CaptureException(ex)` which was your second request.
In fact, there's a sample scene which such use case.

Would love to hear what you think.

**Comment by samuelgoldenbaum** [comment]
Thanks guys, will take a look. I previously made a small change to `ScheduleException` in `SentrySdk` to support custom exceptions that didn't match the `var exc = condition.Split(new char[] { ':' }, 2);` condition. Will feedback as soon as I get a break to pull and integrate.

**Comment by bruno-garcia** [comment]
There's an announcement here: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222

We're working on a new SDK based on the .NET SDK. Also, [Sentry is hiring a Unity developer](https://sentry.io/careers/). The mobile SDK team tracks its work on GitHub, so we'll be seeing some activity on this repository coming next year.
