### ISSUE TITLE
Sentry: (Error) Failed to resolve persistent installation ID. System.UnauthorizedAccessException: Access to the path "xxxxxxx" is denied.

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1012]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.23.1

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2020.3.13f

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android and iOS

### Steps to Reproduce

Sentry Initialization Programmatically

### Expected Result

No errors thrown

### Actual Result

Sentry: (Error) Failed to resolve persistent installation ID. System.UnauthorizedAccessException: Access to the path "xxxxxx" is denied.
Sentry: (Error) Failed to find an appropriate network interface for installation ID. _-> This line JUST ON iOS_

**Comment by bitsandfoxes** [comment]
Hey @ArnauKokoro, thanks for reporting this. I assume when you're initializing the SDK you're not setting the `CacheDirectoryPath`? 
It looks like the Session Tracking is at fault here. But the SDK should definitely not create errors due to this.

You could work around this error for now, by setting `AutoSessionTracking = false`.

**Comment by ArnauKokoro** [comment]
Hi @bitsandfoxes,

I'm not setting _CacheDirectoryPath_.
What's happend if I disable _AutoSessionTracking_ because I had it enabled on other SDK versions?

**Comment by bitsandfoxes** [comment]
I assumed your intention was to disable all offline caching. You could set the `CacheDirectoryPath` yourself, the SDK defaults to `Application.PersistentDataPath`.

If you disable `AutoSessionTracking` the SDK will no longer send information about [release health](https://docs.sentry.io/product/releases/health/) i.e. crash-free rate e.t.c.

**Comment by ArnauKokoro** [comment]
I see...I need that AutoSessionTracking.

So...to avoid that error I should add a _CacheDirectoryPath_? What's a normal _CacheDirectoryPath_ for Android and iOS?

Many thanks!

**Comment by ArnauKokoro** [comment]
Hi @bitsandfoxes,

Got it fixed with these workaround:

What I did is set _Application.temporaryCachePath_ as a _CacheDirectoryPath_ on the programmatically initial options and keep _AutoSessionTracking_ enabled.

With these options the error not occurs.

Thanks!

**Comment by bitsandfoxes** [comment]
Thanks for confirming the workaround.

**Comment by vaind** [comment]
That this is failing for you is quite surprising to me though. As mentioned above, we set the default value to [`Application.persistentDataPath`](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html) and this seems to work fine on all platforms. Can you confirm the path in the error you mentioned above (`Sentry: (Error) Failed to resolve persistent installation ID. System.UnauthorizedAccessException: Access to the path "xxxxxx"`) looked like the path in the Unity docs for the given platform?

**Comment by bitsandfoxes** [comment]
Thanks again @ArnauKokoro. We're tracking this issue over here: https://github.com/getsentry/sentry-unity/issues/1025
