### ISSUE TITLE
Sentry: (Info) Detected an ANR event: Application not responding for at least 5000 ms.

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1013]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.23.1

How did you install the package?
Git-URL

Which version of Unity?
2020.3.13f

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Sentry Initialize programmatically

### Expected Result

Not throw a Sentry error, just log it.

### Actual Result

Error thrown as a sentry exception error and send it to sentry.

### Any logs or screenshots

Sentry: (Info) Detected an ANR event: Application not responding for at least 5000 ms.

**Comment by bitsandfoxes** [comment]
Hey @ArnauKokoro. I'm not sure I understand the issue. When an ANR is detected we capture and send it to Sentry.
Is this not the behavior you are experiencing?

**Comment by bitsandfoxes** [comment]
I know that without the stack trace to pinpoint where it froze it's hard to tell what's going on. ANR means it froze for some time but it might have recovered. Do the breadcrumbs in the issue give you any more insights into this? Based on the timestamps you might be able to see a >= 5s gap.

**Comment by bitsandfoxes** [comment]
One thing that comes to mind might be startup/scene loading where a "false" ANR might be reported.

**Comment by bitsandfoxes** [comment]
So the issue is: There is no freeze, there is no ANR, but Sentry reports an ANR?

**Comment by ArnauKokoro** [comment]
Yes, that's it!

**Comment by bitsandfoxes** [comment]
Is it possible for you to create a small repro? I failed to reproduce this behaviour with the sample we have.

**Comment by ArnauKokoro** [comment]
Working as expected!
