### ISSUE TITLE
Have a way to set log type that can be captured as a breadcrumb

### ISSUE THREAD

**Issue by eomene** [getsentry/sentry-unity#1029]
What problem could Sentry solve that it doesn't?
Right now I see all logs, normal logs, warning and logerrors are captured by sentry as breadcrumbs. But in my project there are alot of logwarnings that I just want to be able to ignore. 
I know we can technically do a filter. But there are alot. I would rather have a setting where I tell sentry not to automatically send breadcrumbs. Because I want to do it myself. 
Or set it to ignore warnings, logs and so on. 

It would be very handy...
Or maybe this is already possible. Would be nice if you can tell me how or send me in the right direction.

**Comment by bitsandfoxes** [comment]
Hey @eomene. 
You're basically asking for a way to disable the automatic breadcrumb creation from logs? Or to capture only one specific type of log as breadcrumb?

We do have plans for making breadcrumbs configurable based on levels here:https://github.com/getsentry/sentry-unity/issues/60. Would that work for you?

**Comment by bitsandfoxes** [comment]
While having granular control over breadcrumbs is still on the to-do, an opt-out absolutely makes sense to me.
