### ISSUE TITLE
Not Compatible with Google Admob 7.2.0

### ISSUE THREAD

**Issue by Awais6** [getsentry/sentry-unity#1037]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
sentry.io

Which version of the SDK?
0.23.1 and 0.23.0

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
Unity 2021.3.11f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
On Android Device

### Steps to Reproduce
Use Unity 2021.3.11f1 and install Google Mobiel Ads 7.2.0 then install Sentry 0.23.1 and use IL2CPP backend then build and game crashes at launch on emulator or real android device,

### Expected Result

Should not crash

### Any logs or screenshots

`--------- beginning of crash
10-22 11:45:12.409  2677  2677 E AndroidRuntime: FATAL EXCEPTION: main
10-22 11:45:12.409  2677  2677 E AndroidRuntime: Process: com.tellosoft.contrcutionbuilder2, PID: 2677
10-22 11:45:12.409  2677  2677 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.AppLifecycleIntegration.addObserver(AppLifecycleIntegration.java:92)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.AppLifecycleIntegration.register(AppLifecycleIntegration.java:60)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.Sentry.init(Sentry.java:188)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.Sentry.init(Sentry.java:117)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:87)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:56)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:27)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:44)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:5855)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5447)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5386)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-22 11:45:12.409  2677  2677 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-22 11:45:12.414   552  2691 W ActivityManager:   Force finishing activity com.tellosoft.contrcutionbuilder2/com.unity3d.player.UnityPlayerActivity`

**Comment by Awais6** [comment]
related to this #953

**Comment by bitsandfoxes** [comment]
Thanks for raising and connecting this.

**Comment by Awais6** [comment]
Welcome,
When will this bug clear? Any workaround or should I move to Sentry-Unity-Lite SDK?

**Comment by bitsandfoxes** [comment]
There will be a release today.

**Comment by Awais6** [comment]
@bitsandfoxes No update yet? I am waiting to build the game on Android

**Comment by bitsandfoxes** [comment]
> @bitsandfoxes No update yet? I am waiting to build the game on Android

Sorry for the delay. The release got stuck in our release pipeline, but it should be available shortly.
