### ISSUE TITLE
Sentry LastEventId by Type

### ISSUE THREAD

**Issue by hajimeku** [getsentry/sentry-unity#1045]
Hey! 
I am trying to find a way on how I could integrate https://docs.sentry.io/platforms/unity/enriching-events/user-feedback/ into my application.

I figured out that I could do
`var eventId = SentrySdk.LastEventId;`
And then send this eventId to CaptureUserFeedback

The problem I have now is that I would like to only do this for specific uncaught exceptions or crashes the user might have experienced. Is there any way to detect this?
If I cant detect this the last eventId is usually some texture not being able to load from an avatar for example.

**Comment by mattjohnsonpint** [comment]
Also, I just noticed that even though we documented its usage, the `Exception` property is hidden from some IDEs.  Fixing that with https://github.com/getsentry/sentry-dotnet/pull/2011 for the next release.  It is safe to use either way.

**Comment by hajimeku** [comment]
thanks Matt! This will solve my issue

**Comment by hajimeku** [comment]
I'm trying to make sense of how I should use this feature.
Is it common that this is used as a bug-reporting tool?

I tried to use            
`SentrySdk.CaptureUserFeedback(SentryId.Empty, "testmail@azerion.com", "There is a comment here", "Apollo");`

**Comment by mattjohnsonpint** [comment]
Instead of `SentryId.Empty`, pass the actual ID of the associated event.

See also: https://docs.sentry.io/platforms/dotnet/enriching-events/user-feedback/

**Comment by hajimeku** [comment]
This solved it yea!  We thought it would only be an extra piece of information.
