### ISSUE TITLE
Building a project for development with 0.24.0 in Xcode 13.2.1 causes an exception

### ISSUE THREAD

**Issue by abond-sd** [getsentry/sentry-unity#1049]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.24.0

How did you install the package?
Git-URL

Which version of Unity?
2021.3.6f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
It's happening when building via Xcode 13.2.1 (the stable version that Unity Cloud Build supports)

### Steps to Reproduce
1. Integrate Sentry 0.24.0 into the project
2. Switch the platform to iOS
3. Make a build in Unity
4. Archive the project in Xcode and distribute the app for development with bitcode enabled

### Expected Result

We were previously using 0.21.2 and didn't encounter this error when building the same project via Xcode.

### Actual Result

Shortly after preparing the app for distribution to development, Xcode displays an error dialog with this information:

ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/wj/32vpwt4d65l7k52n8l8r6s540000gq/T/ipatool20221025-33634-1lhq8kq/thinned-out/arm64/Payload/Redacted.app/Frameworks/Sentry.framework/Sentry --generate-dsym /var/folders/wj/32vpwt4d65l7k52n8l8r6s540000gq/T/ipatool20221025-33634-1lhq8kq/thinned-out/arm64/Payload/Redacted.app/Frameworks/Sentry.framework/Sentry.dSYM --strip-swift-symbols /var/folders/wj/32vpwt4d65l7k52n8l8r6s540000gq/T/ipatool20221025-33634-1lhq8kq/thinned-in/arm64/Payload/Redacted.app/Frameworks/Sentry.framework/Sentry
Status: pid 33671 exit 1
Stdout:
    SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk

**Comment by abond-sd** [comment]
It works correctly with Xcode 14.

**Comment by bitsandfoxes** [comment]
Hey @abond-sd, thanks for raising this. I'm looking into it.

**Comment by abond-sd** [comment]
Thanks very much @bitsandfoxes!

**Comment by bitsandfoxes** [comment]
Are you still running into this issue? I tested building with `Xcode 13_latest` (13.4.1 in my case) which is supported according to their [cloud docs](https://unity-technologies.github.io/cloud-build-docs-public/xcode-unity-versions-compatibility) and I could not reproduce this issue.
Please feel free to reopen this is not resolved for you.

**Comment by abond-sd** [comment]
Thanks for checking on this! We updated to Xcode 14 and haven't seen this since. I believe it still happens on the UCB Xcode default (13.2.1 IIRC) if that matters, but we are comfortable with the Xcode version update to address it.
