### ISSUE TITLE
Better UPM meta-data: documentation, changelog, license.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#105]
UPM shows links such as:

![image](https://user-images.githubusercontent.com/1633368/113749042-2a7e7e00-96d7-11eb-86fb-7bc13b316cc4.png)

Currently clicking on them leads nowhere:
![image](https://user-images.githubusercontent.com/1633368/113749068-323e2280-96d7-11eb-9bf0-ed03e4a74525.png)

We need to point it to `CHANGELOG.md`, a basic docs file that emphases our complete documentation is on docs.sentry.io/platform/unity but describes some basic steps such as finding the SDK's "Unity Window" and adding the DSN.

[Links to the sample](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/) in the package window

**Comment by semuserable** [comment]
closed by https://github.com/getsentry/sentry-unity/pull/124
