### ISSUE TITLE
SentrySdk.CaptureMessage logs dont show in the Editor log

### ISSUE THREAD

**Issue by hajimeku** [getsentry/sentry-unity#1050]
In our project, we moved a lot of LogError code to use functions SentrySdk.CaptureMessage.
The problem we have now is that we don't see these Errors while working in the Editor.
We can do Debug.LogError but now it will show twice in Sentry.

Is there any way we could solve this?

**Comment by bitsandfoxes** [comment]
This seems related to https://github.com/getsentry/sentry-unity/issues/60.

Right now, the SDK captures logs coming through `LogError` as events. Is there a specific reason you want to `CaptureMessage` it yourself? I guess you're disabling the logger for release builds?

**Comment by hajimeku** [comment]
We do not disable the logger in release builds, we do disable anything below error to not show up in RC builds.

CaptureMessage allows us to add tags and extra data to the LogError.

We have for example in our game a log error message like "Image could not be loaded for a special offer" and then apply tags to this error about the ID of the offer and the URL of the image it's trying to load.

Now the main problem is that we have over 100 LogErrors built into our game to monitor if everything is going well.
Usually, we find these problems during development already because we see them in the editor log. With CaptureMessage I don't see this in my editor log.

**Comment by hajimeku** [comment]
What would be a good solution for us is that we can:
1: Use LogError and be able to attach some tags or data to it.
2: CaptureMessage would call the Logger with a sentry prefix so that it doesn't get captured there.

Doesnt get captured there because I found this code:
```
// We're not capturing SDK internal logs
if (logMessage.StartsWith(UnityLogger.LogPrefix, StringComparison.Ordinal))
{
    // TODO: Maybe color Sentry internal logs (highlight 'Sentry'?)
    return;
}
```

**Comment by bitsandfoxes** [comment]
I think I get your point. Let met take this back to the team, I'll see if we can come up with something.

**Comment by vaind** [comment]
@hajimeku you can use the [BeforeSend hook](https://docs.sentry.io/platforms/unity/configuration/options/#before-send) to log events coming from sentry, i.e. also those you've just posted through `captureMessage()`. You can configure your own callback for BeforeSend using [programmatic configuration](https://docs.sentry.io/platforms/unity/configuration/options/#programmatic-configuration).

Please give it a go and see if it works for you. Feel free to reopen this issue (or open a new one) if that doesn't work out.

**Comment by hajimeku** [comment]
Hey, i think i would end up in a loop then
If I use the Debug.LogError function.

**Comment by hajimeku** [comment]
Oke thanks we will do this!
