### ISSUE TITLE
iOS Archiving fails for `v0.24.0` due to nested bundle, invalid framework path

### ISSUE THREAD

**Issue by jzapdot** [getsentry/sentry-unity#1059]
### Environment

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which version of the SDK?**
`v0.24.0`

**How did you install the package? (Git-URL, Assetstore)**
Git URL

**Which version of Unity and other apps/OS?**
**Unity:** `Unity 2021.3.9f1`
**macOS:** `macOS Monterey 12.6 (21G115)`
**xCode:** `Version 14.0.1 (14A400)`

**Is this happening in Unity (editor) or on a player like Android, iOS, Windows?**
It occurs both in Xcode when attempting to validate an archive and/or on the console in our CI attempting to publish an archive to the cloud.

### Steps to Reproduce

1. Build to an Xcode project from Unity.
2. Archive the project and then attempt to validate it and/or upload an archive to test flight.

### Expected Result

The validation should pass without error.

### Actual Result

The archive validation fails for multiple reasons including:
* Invalid directory. The bundle Payload/AppName.app/Frameworks/UnityFramework.framework/Sentry.framework is not contained in a correctly named
directory. It should be under Frameworks. (ID: 64a834ee-9d86-40c2-895b-6965b3eff824)
* Invalid directory. The bundle Payload/AppName.app/Sentry.framework is not contained in a correctly named directory. It should be under Frameworks. (ID:
6caa977b-7e9d-4ff1-8508-e7882bf3feff)
* CFBundleldentifier Collision. There is more than one bundle with the CFBundleldentifier value 'io.sentry.Sentry' under the iOS application 'AppName.app'. (ID:
3bae8552-5f66-4c90-b850-5c1946765d6d)
* Invalid Bundle. The bundle at 'AppName.app/Frameworks/UnityFramework.framework' contains disallowed nested bundles. (ID: 69537fb-1588-474c-b2d7-

![image](https://user-images.githubusercontent.com/40764984/199064665-24fd229c-98b6-4517-b620-b81099fc05e9.png)

**Comment by bitsandfoxes** [comment]
Thanks for raising this!
Fixed by https://github.com/getsentry/sentry-unity/pull/1056 and will be part of the next release.
