### ISSUE TITLE
Make dir `package` a template for the UPM package

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#106]
The goal is to make `/package` just a template which CI will use to build the `.zip` that we'll publish for UPM.

This means nothing should exist in this package that isnt' supposed to be moved into the `package-release` package during CI:

https://github.com/getsentry/sentry-unity/blob/2380fe420a6a46d8e2bd913fb94e61f94d7b3127/.github/workflows/ci.yaml#L174-L189

The `README.md` in `/package` will be displayed on the repository used by UPM.

We'll push the contents of the zip to https://github.com/getsentry/unity

First step of it was done here: https://github.com/getsentry/sentry-unity/pull/104

Ideally the `package-dev` combined with the "template" `package` folder would result in the artifact we publish.
So that the sample, as worked on in dev, is made available through UPM.

**Comment by semuserable** [comment]
Is there anything left to do here?

**Comment by bruno-garcia** [comment]
@semuserable need to take a look.
First thing I wonder is: Is there anything on `package` today that doesn't need to be there? That was there when we thought of it being used as a complete package? If so it should be deleted.
