### ISSUE TITLE
Switch Mono.Cecil usage over to a package dependency

### ISSUE THREAD

**Issue by oddgames-david** [getsentry/sentry-unity#1068]
This is the one I normally use: https://github.com/needle-mirror/com.unity.nuget.mono-cecil.git

**Comment by muveso** [comment]
I have mono-cecil conflicts too.

**Comment by bitsandfoxes** [comment]
Sorry about that. I missed, that the new dependencies got added to the `Editor` directory. We already have the [conflict resolution](https://github.com/getsentry/sentry-unity/pull/1064) merged, I'll make a new release with the fix later today.

**Comment by vaind** [comment]
As said above, the dependency conflict should be resolved in the upcoming v0.25.1 - feel free to reopen in case the issue persists.
