### ISSUE TITLE
Can't see sourcecode or linenumbers on stacktrace

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1084]
Hi,

After updating to the latests version of the sentry-unity sdk and enabling uploading symbols for Android and iOS (checked they are uploaded) I can't see the sourcecode or linenumbers on the exceptions stacktrace with Mono or IL2CPP. I see the same as when I had other sdk version and had not uploaded the symbolics.

I only see the Class and Method where the exception happens, but not sourcecode or linenumber.

What am I missing?

Many thanks!

**Comment by bitsandfoxes** [comment]
Hey @ArnauKokoro, is there any issue with the event on Sentry? Can you provide a link to one of those events?

**Comment by ArnauKokoro** [comment]
Hi @bitsandfoxes 

These are NullPointerExceptions non controlled:

This is what I had on earlier version:
<img width="1092" alt="Captura de Pantalla 2022-11-18 a las 11 09 02" src="https://user-images.githubusercontent.com/80262126/202677455-73d90d41-1100-4273-b233-21c7d8378129.png">
<img width="832" alt="Captura de Pantalla 2022-11-18 a las 11 11 19" src="https://user-images.githubusercontent.com/80262126/202677505-018be192-6c50-4b1f-878d-ce7594a49044.png">

And this is what I have now:
<img width="1095" alt="Captura de Pantalla 2022-11-18 a las 11 09 17" src="https://user-images.githubusercontent.com/80262126/202677705-77f54121-56ff-4090-951e-3357d42ab91c.png">
<img width="812" alt="Captura de Pantalla 2022-11-18 a las 11 08 10" src="https://user-images.githubusercontent.com/80262126/202677742-1f842948-f6e2-4375-a518-7704fe341f17.png">

I don't know how to give you a public link to one of our exceptions events

Thanks!

**Comment by bitsandfoxes** [comment]
Can you send the event to stefan@sentry.io? I'd like to take a closer look.

**Comment by ArnauKokoro** [comment]
@bitsandfoxes Done

**Comment by bitsandfoxes** [comment]
It looks to me like the IL2CPP integration did not get enabled. Are you on Unity 2019 by any chance? Did you receive any warnings during the build? Could you try building for Android with the logging verbosity set to `Debug` in the editor window -> Advanced?

**Comment by ArnauKokoro** [comment]
@bitsandfoxes I see what can be the problem. I have disable Sentry (on config window) avoiding to startup on init. I initialize it manually. I upload symbols manually.

And that's why I get this warning:

_The IL2CPP line number support requires the debug symbol upload to be enabled._ 

Thanks!

**Comment by bitsandfoxes** [comment]
I see. So you're not making use of the `SentryScriptableObject` either? You're calling `SentryUnity.Init` yourself?
May I ask why? Is something not working for you with the self-initialization?

**Comment by ArnauKokoro** [comment]
We use SentryUnity.Init because we are having problems with a webview plugin.

We don't use SentryScriptableObject.

**Comment by vaind** [comment]
@ArnauKokoro are you doing all the same things as in [SentryInitialization.cs](https://github.com/getsentry/sentry-unity/blob/main/package-dev/Runtime/SentryInitialization.cs)? That's where all the configuration, including native setup & IL2CPP line number config, happens. If you're not passing the whole `SentryUnityInfo` when creating options, then it won't work.
This file is normally part of your game. What problems were you facing that prevented you from using it? Maybe it would be possible to resolve them and avoid trying to do everything manually.

**Comment by vaind** [comment]
> Yes, we have all the options we would have on the editor window on the manual SentryInit.

`SentryUnityInfo` is a custom type that's initialized based on some compiler directives - it's not available through UnityEditor, see the file I've linked in my previous post. 

But yes, its definitely best to try and use the standard initialization

**Comment by ArnauKokoro** [comment]
I will try to get our webview work as intented with Sentry Auto Enabled. But if not I will try to get work that SentryUnityInfo as intended.

Many thanks!

**Comment by ArnauKokoro** [comment]
@bitsandfoxes Sentry Auto Init (from de Sentry Dialog) enabled and got it working. I can see now the line number and the source code on the events.

Thanks!

**Comment by bitsandfoxes** [comment]
That's great news! I guess this has been related to the issue building with Android Studio!

**Comment by ArnauKokoro** [comment]
@bitsandfoxes yes, it is! But in this particular issue it was because I initialized Sentry manually and I uploaded the symbolics with an sh script after building, and that was not working. To make it work I had to initialize it automatically enabling it from the Unity Editor Sentry Dialog to upload automatically the symbolics.
