### ISSUE TITLE
Using Unity, Every time I build an IL2CPP client a new project setting --emit-source-mapping option is added

### ISSUE THREAD

**Issue by sebas77** [getsentry/sentry-unity#1093]
Using Unity, Every time I build an IL2CPP client a new project setting --emit-source-mapping option is added

Setting additional IL2CPP arguments '--emit-source-mapping' for platform StandaloneWindows64
UnityEngine.Debug:Log (object)
Sentry.Unity.Editor.Il2CppOption:OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at /sentry-unity/src/Sentry.Unity.Editor/Il2CppOption.cs:15)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

![image](https://user-images.githubusercontent.com/945379/204111168-2f82df5d-cbbd-44d9-812e-c43ee7d1500f.png)

**Comment by bitsandfoxes** [comment]
Hey, sorry you're running into this issue. Could you confirm that you're using a version newer than: `0.24.0`? It was supposed to contain the [fix](https://github.com/getsentry/sentry-unity/pull/997) for this.

**Comment by sebas77** [comment]
oh great thanks, we were probably stuck at 0.23
