### ISSUE TITLE
Sentry adding `--emit-source-mapping` multiple times a project is built

### ISSUE THREAD

**Issue by silent1mezzo** [getsentry/sentry-unity#1094]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?

How did you install the package? (Git-URL, Assetstore)

Which version of Unity?

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

### Actual Result

https://twitter.com/sebify/status/1595043609908334597

### Any logs or screenshots
![FiK7tI8XwAM4uTQ](https://user-images.githubusercontent.com/155016/204114620-f40895ba-b05a-4de4-a15e-1793b8c03717.png)

**Comment by bitsandfoxes** [comment]
Hey, sorry you're running into this issue. Could you confirm that you're using a version newer than: `0.24.0`? It was supposed to contain the [fix](https://github.com/getsentry/sentry-unity/pull/997) for this.

**Comment by bitsandfoxes** [comment]
Duplicated of https://github.com/getsentry/sentry-unity/issues/1093
