### ISSUE TITLE
Gradle Task Upload Symbols Error

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1099]
### Environment

Sentry SaaS (sentry.io)

Which version of the SDK?
0.23.1

How did you install the package?
Git-URL

Which version of Unity?
2020.3.13f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android - Android Studio

### Steps to Reproduce

1. Export Android Project with IL2CPP and upload symbols enabled
2. Open on Android Studio
3. Build

### Expected Result

Upload Symbols by gradle task and build

### Actual Result

Project not building because error:

_Negative array index [-1] too large for array size 0_

on

_gradle.taskGraph.allTasks[-1]_

**Comment by bitsandfoxes** [comment]
Thanks for raising this. I'll look into this.

**Comment by bitsandfoxes** [comment]
Are you upgrading/updating the project when opening it with Android Studio? Are you modifying the `build.gradle` files?

**Comment by ArnauKokoro** [comment]
@bitsandfoxes No, I'm not. It just appears like that when I open the project.

**Comment by bitsandfoxes** [comment]
I tried exporting and building our sample project and I can't seem to reproduce the issue. Could you provide a repro? I'm mostly interested in the gradle files themselves.

**Comment by ArnauKokoro** [comment]
@bitsandfoxes Installing 2020.3.15f2 Unity version and downloading SDK 31 got it works!

I had version 2020.3.13f1 that was unable to build for SDK 31 and that's why I use Android Studio to build. Seems like the gradle version (6.1.1) I use on Android Studio was old, instead I use the gradle from Unity Editor 2020.3.15f2 (6.8) and got it works on Unity Editor and on Android Studio.

Thanks!

**Comment by bitsandfoxes** [comment]
That's great news! Glad it worked out! Good catch with the mismatching Gradle versions.
