### ISSUE TITLE
After updating Sentry iOS Symbol Upload Fails

### ISSUE THREAD

**Issue by marcos-monumental** [getsentry/sentry-unity#1105]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
We are upgrading from 17.0.

We tried to upgrade months ago to version 22.1 and ran into this issue.
Tried again now with 26.0 and 27.0 and running into the exact same issue.

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2019.4.39f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Editor, at build time, only when building for iOS. All other platforms build successfully. 

### Steps to Reproduce

1. Upgrade the git URL to go from 17.0 to a newer version (tried 22.1, 26.0, and 27.0)
2. Kick an iOS build
3. Unity-side of build completes successfully and XCode build will begin

### Expected Result

The XCode build completes and symbols are uploaded successfully.

### Actual Result

The XCode build completes, but symbols fail to upload (and the build is treated as a failure).

The build logs for the failure:

```
Uploading debug symbols and bcsymbolmaps (Bitcode enabled).
  INFO    2022-12-05 16:41:44.861780 -06:00 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
  INFO    2022-12-05 16:41:44.862689 -06:00 sentry-cli was invoked with the following command line: "./sentry-cli-Darwin-universal" "upload-dif" "--force-foreground" "--il2cpp-mapping" "--include-sources" "/Users/jenkins/Library/Developer/Xcode/DerivedData/Unity-iPhone-hauzkwhtmeovjubpaozltvvplbru/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos"
  INFO    2022-12-05 16:41:44.862710 -06:00 Issuing a command for Organization: monumentalllc Project: mythgard
error: Could not parse Info.plist file
  caused by: MARKETING_VERSION is missing
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure`

Sentry-Symbols-Upload.log:

error: Could not parse Info.plist file
  caused by: InvalidXmlSyntax (line 0, column 0)
```

I've looked at our Info.plist and it seems to be in the correct location and proper.

**Comment by bitsandfoxes** [comment]
Hey, sorry you're running into issues. Which version of Xcode are you using?

**Comment by bitsandfoxes** [comment]
It's odd. I can't reproduce the issue but I can confirm that this is coming from sentry-cli trying to parse the `Info.plist`. 
I don't really understand how or why the property is missing. Trying this locally, my `Info.plist` does not have the property either. Xcode does show it tho.
Let me get back to you with more answers once I have them.

**Comment by MarcosAlfonso** [comment]
Okay thank you @bitsandfoxes

**Comment by bitsandfoxes** [comment]
Hey @marcos-monumental, could you provide me your `Info.plist`? Feel free to send it to stefan@sentry.io

**Comment by marcos-monumental** [comment]
Hey @bitsandfoxes sorry for the delay in response, I wanted to look into a few more things and then suddenly holidays were here.

I've just sent you our plist to that email, but I don't think that's the cause of the issue.

We've realized that if we pass a plist argument to the sentry-cli command used in the SymbolUpload build phase of Xcode it will find the plist no problem and upload symbols successfully.

![image](https://user-images.githubusercontent.com/102047681/211856046-437fe8e9-2a50-44ff-bebc-23e6ce4fb206.png)

We're pretty sure this is the default location for the plist, so it seems odd we'd need to pass this in.

Do you know why sentry-cli would be failing to find it at the default location?

And if this is the proper fix, do you know if there's a place we can add this on the Unity side so it'll be automatically added to the BuildPhase instead of manually modified after the xcode project is built?

Thanks

**Comment by bitsandfoxes** [comment]
Thanks for coming back to us with this one.

> We were hoping we could pass this plist parameter via the Buildtime Options script, but from what we can tell that's not really possible.

Unfortunately, you're right. It does not work right now but it would be the ideal place to add to the arguments we pass down to cli and a very valid feature request.

We'll be looking into why sentry cli fails to find the `Info.plist` and I'll come back to you once I know more.

**Comment by marcos-monumental** [comment]
That's a great point... @bitsandfoxes, we will get you the proper project plist as soon as we can (working with another dev on this, as I'm on Windows)

**Comment by marcos-monumental** [comment]
@bitsandfoxes I have just sent you some more .plists as they appear in our xcode project folder.

**Comment by marcos-monumental** [comment]
@bitsandfoxes sorry for @ spam, but a quick follow up that I think is relevant. We enabled info level logging and this is what we see in the sentry upload logs now:

`  INFO    2023-01-19 10:27:22.116765 -06:00 sentry-cli was invoked with the following command line: "./sentry-cli-Darwin-universal" "upload-dif" "/Users/jenkins/Library/Developer/Xcode/DerivedData/Unity-iPhone-hauzkwhtmeovjubpaozltvvplbru/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos"
  INFO    2023-01-19 10:27:22.117234 -06:00 Issuing a command for Organization: monumentalllc Project: mythgard
error: Could not parse Info.plist file
  caused by: InvalidXmlSyntax (line 0, column 0)`

Is that the location that Sentry expects $BUILT_PRODUCTS_DIR to be pointing to? Its clearly not in the xcode project folder

**Comment by bitsandfoxes** [comment]
@marcos-monumental, yes. That does look like the correct `$BUILT_PRODUCTS_DIR`. That is where the build output ends up at. The Xcode's `Info.plist` is something that Sentry CLI looks for separately.
@kamilogorek is there a way to output which/where Sentry CLI gets stuck on?

**Comment by kamilogorek** [comment]
Not really, sorry. I'm more than happy to accept a PR that will improve debug logging there though :)

**Comment by bitsandfoxes** [comment]
Closing this as stale.
