### ISSUE TITLE
SentryBuildTimeOptionsConfiguration not overriding values

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1111]
### Environment
Sentry SaaS (sentry.io)

Which version of the SDK?
0.27.0

How did you install the package?
Git-URL

Which version of Unity?
2020.3.15f2

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android & iOS

### Steps to Reproduce

1. Build for iOS or Android

### Expected Result

Building executes SentryBuildTimeOptionsConfiguration and when opening the app on Sentry.io is created a new Release with OVERRIDE release name: nameOverride@version (buildNumberOverride)

### Actual Result

Building executes SentryBuildTimeOptionsConfiguration and when opening the app on Sentry.io is created a new Release with DEFAULT release name: name@version (commitHash)

### Any logs or screenshots
```
public class SentryBuildtimeOptionsConfiguration : Sentry.Unity.Editor.ScriptableOptionsConfiguration
{
    public override void Configure(SentryUnityOptions options, SentryCliOptions cliOptions)
    {
       options.Release = $"nameOverride@{Application.version}";
       options.Distribution = PlayerSettings.Android.bundleVersionCode.ToString();
    }
}
```

**Comment by bitsandfoxes** [comment]
Thanks for raising this. I'll take a look.

**Comment by bitsandfoxes** [comment]
I see that you're using the `SentryBuildtimeOptionsConfiguration`. Are you also setting the release in the `RuntimeOptionsConfiguration`?

**Comment by ArnauKokoro** [comment]
I don't use RuntimeOptionsConfiguration. But I can use it as a workaround if there is a bug on SentryBuildtimeOptionsConfiguration.

**Comment by bitsandfoxes** [comment]
That's not a workaround but the intended use.
The `BuildtimeConfiguration` give you a point of entry if you want to reach the native layer for Android, iOS, or macOS.
In most cases, running the same code in both instances is likely fine.
The [docs](https://docs.sentry.io/platforms/unity/configuration/options/) go into more detail.

**Comment by ArnauKokoro** [comment]
Fine, I can have the same code on BuildtimeScript and RuntimeScript. But, native crashes will get the default release name instead of the release name overrited on the RuntimeScript, is that right?

**Comment by bitsandfoxes** [comment]
I agree, it's not ideal to have to do it in more than one place.
If you want to override the `release` you'll have to either set it in the `Release Override` in the editor window. That will be picked up automatically.
If you want to override it from code you have to set it in both `RuntimeConfiguration` and `BuildtimeConfiguration`.
