### ISSUE TITLE
The referenced script on this Behaviour (Game Object '<null>') is missing!

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1112]
### Environment
Sentry SaaS (sentry.io)

Which version of the SDK?
0.27.0

How did you install the package?
Git-URL

Which version of Unity?
2020.3.15f2

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android, iOS

### Steps to Reproduce

1. Build Android & iOS

### Expected Result

No Warning Logs appears

### Actual Result
```
The referenced script (Unknown) on this Behaviour is missing!
    UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
    UnityEngine.ResourcesAPI:Load (string,System.Type) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:66)
    UnityEngine.Resources:Load (string,System.Type) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:117)
    UnityEngine.Resources:Load<Sentry.Unity.ScriptableSentryUnityOptions> (string) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:112)
    Sentry.Unity.ScriptableSentryUnityOptions:LoadSentryUnityOptions (Sentry.Unity.ISentryUnityInfo) (at /sentry-unity/src/Sentry.Unity/ScriptableSentryUnityOptions.cs:96)
    Sentry.Unity.SentryInitialization:Init () (at /Library/PackageCache/io.sentry.unity@b562146d73/Runtime/SentryInitialization.cs:59)

The referenced script on this Behaviour (Game Object '<null>') is missing!
    UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
    UnityEngine.ResourcesAPI:Load (string,System.Type) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:66)
    UnityEngine.Resources:Load (string,System.Type) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:117)
    UnityEngine.Resources:Load<Sentry.Unity.ScriptableSentryUnityOptions> (string) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:112)
    Sentry.Unity.ScriptableSentryUnityOptions:LoadSentryUnityOptions (Sentry.Unity.ISentryUnityInfo) (at /sentry-unity/src/Sentry.Unity/ScriptableSentryUnityOptions.cs:96)
    Sentry.Unity.SentryInitialization:Init () (at /Library/PackageCache/io.sentry.unity@b562146d73/Runtime/SentryInitialization.cs:59)
```    
    
    
### Comments

I do have both Scripts ScriptableRuntimeConfig and ScriptableBuildConfig Objects added on Sentry Editor.

**Comment by bitsandfoxes** [comment]
I assume this happened right after upgrading the Sentry package?
Could you try deleting the SentryOptions in `Assets/Resources/Sentry` and open the editor window again to recreate them?

**Comment by ArnauKokoro** [comment]
@bitsandfoxes I deleted SentryOptions to force recreated, but same happens.

After that I uninstalled the plugin, deleted Assets/Plugins/Sentry and all files in Assets/Resources/Sentry then I closed editor. Then, I opened the editor, installed the plugin, added Buildtime and Runtime scripts again, build the app but same happens.

**Comment by bitsandfoxes** [comment]
This is something that happened after the upgrade? Do you rename the options?

**Comment by ArnauKokoro** [comment]
No, I did not rename the SentryOptions asset. Yes, it happened after upgrade to 0.27.0 but right now I have a clean installation of the plugin because as I said on the last comment I uninstalled the plugin and deleted all the files related to sentry before install it again.
