### ISSUE TITLE
Please point out the documentation for this option

### ISSUE THREAD

**Issue by sebas77** [getsentry/sentry-unity#1116]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/945379/208086515-ded0dcaa-0a86-48da-abeb-c71b146b14d5.png">

I am trying to understand what the use case for upload dev symbol option

**Comment by bitsandfoxes** [comment]
This relates to `Development Build` on the build options. By default, the SDK does not upload debug symbols for those builds.
