### ISSUE TITLE
How to initialise Sentry explicitly

### ISSUE THREAD

**Issue by sebas77** [getsentry/sentry-unity#1117]
Hi,

I need to initialise Sentry at a specific point and not at startup. This means that I have to make options.ShouldInitializeSdk() return false.

I wonder:

- if this is the reason the check even exists
- what's the best way to initialise Sentry explicitly

**Comment by bitsandfoxes** [comment]
Can I ask why you need to do this? Maybe that is something we can improve in the SDK in general.

It's tricky: On iOS and Android, the native SDKs basically require getting initialized during build time.
You can disable Sentry in the editor window and call `SentryUnity.Init` when it works for you. This unfortunately means that there would be no native support.

**Comment by sebas77** [comment]
I don't think we are using building time initialization because we are still on desktop and this problem will arise only on desktop in our case.

The reason why I need it it's that we have a replacement for the standard log, it's implemented through an ILogHandler as you do in sentry, but since mine is a replacement, I need to break the chain.

if Sentry is initialised before my logger, Sentry will never intercept the logs.

At the moment we are doing this after I initialise my logger:

```
 public static void Init()
        {
            try
            {
                var sentryUnityInfo = new SentryUnityInfo();
                var options = ScriptableSentryUnityOptions.LoadSentryUnityOptions(sentryUnityInfo);
                options.Enabled = true;
                if (options.ShouldInitializeSdk())
                {
                    SentryIntegrations.Configure(options);
                    SentryUnity.Init(options);
                }
            }
            catch (Exception e)
            {
                CoreLoopLogger.GlobalException(e);
            }
        }
 
```

**Comment by sebas77** [comment]
I noticed that our current production client, that doesn't have the workaround above, still logs correctly even if by ILogHandler implementation should prevent that.

Is it possible that you have an alternative way to catch exceptions using IL2CPP? If so my workaround is then not necessary?

**Comment by bitsandfoxes** [comment]
> Is it possible that you have an alternative way to catch exceptions using IL2CPP?

We don't. The IL2CPP stuff happens in an exception processor and that relies on our `ILogHandler`. Without it, Sentry doesn't capture the exception at all.

I was going to propose embedding the package so you can modify the `SentryIntialization.cs` but thinking about it now: Can you initialize your logger inside the Configure callback? That's guaranteed to run before the SDK does anything else.
