### ISSUE TITLE
Can't Assign Runtime Options Script to SentryOptions

### ISSUE THREAD

**Issue by jelling** [getsentry/sentry-unity#1154]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?

https://github.com/getsentry/unity.git#0.28.0

How did you install the package? (Git-URL, Assetstore)

Git URL

Which version of Unity?

2021.3.14f1 Personal

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

Player

### Steps to Reproduce

Create a runtime script object using the Sentry Tools window and try to assign it. See video below.

### Expected Result

Can assign runtime config script.

### Actual Result

Can't assign run time script:

https://user-images.githubusercontent.com/1887486/214865115-f98fda10-8366-4bcc-b7dc-1963170e5880.mp4

**Comment by bitsandfoxes** [comment]
@jelling sorry about that. There is a release coming out later today to fix this faulty default behaviour. This is due to conflicting class names and you can unblock yourself you can open the created Configuration script itself and rename `SentryRuntimeOptionConfiguration` to something else.

**Comment by bitsandfoxes** [comment]
The release is out. Please let me know if the issue persists for you.
