### ISSUE TITLE
Missing C# Exception stack trace with LP2CPP

### ISSUE THREAD

**Issue by EAdemov** [getsentry/sentry-unity#1158]
### Package

Sentry

### .NET Flavor

IL2CPP

### .NET Version

4.x

### OS

Android

### SDK Version

0.28.1

### Steps to Reproduce

1. Installed Latest Sentry package
2. Setup up all required information on Sentry Editor menu. Including Debug Symbols Tab and enabled IL2CPP line numbers check.
3. throw new Exception() somewhere in the code.
4. Exception is tracked but stack trace in native code, which makes it impossible for debugging or getting any sort of useful information. 

### Expected Result

It would be very useful if I could see standard trace from my code.

### Actual Result

Currently the logs looking something like this.
<img width="1325" alt="Screenshot 2023-01-27 at 0 24 59" src="https://user-images.githubusercontent.com/45031271/214964547-3c2f0e98-ac2e-4607-a4fb-284ff330c453.png">

**Comment by EAdemov** [comment]
Hey! Small update with this issue. Apparently Debug symbols are not uploaded, even though all fields are correct in the tab menu. Alternatively I tried manually uploading the generated symbols via sentry-cli. Terminal logged:
```
> Found 3 debug information files
> Prepared debug information files for upload
> Nothing to upload, all files are on the server
```

Looking back at Debug files section in the project's setting:
 
<img width="1184" alt="Screenshot 2023-01-27 at 9 26 41" src="https://user-images.githubusercontent.com/45031271/215031456-361625f9-f570-454b-be4c-d677568594af.png">

Apparently it's uploaded correctly.

**Comment by bitsandfoxes** [comment]
Hey @EAdemov. Thanks for raising this. We are aware that there is an issue in some cases with getting back from the generated IL2CPP code to the actual C# line number. We think we have found a solution for this that should be available within the next couple of weeks.

**Comment by EAdemov** [comment]
Thanks, looking forward for that!

**Comment by bitsandfoxes** [comment]
Closed by https://github.com/getsentry/sentry-unity/pull/1165
and will be part of the next release.
