### ISSUE TITLE
How are screenshots taken in the Unity SDK?

### ISSUE THREAD

**Issue by polynatic** [getsentry/sentry-unity#1161]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Unity SDK

### Description

I was trying to find out what information could accidentally end up in a screenshot, because I want to avoid PII issues. My game itself does not display any PII, so that would not be a problem. But could notifications or other overlayed views by the OS accidentally be captured? If it is really just the application itself I would feel safe to turn it on, as it might be helpful.

### Suggested Solution

Information about whether data of other apps or the OS (notifications) could accidentally be leaked in screenshots. Thanks!

**Comment by bruno-garcia** [comment]
It's not an actual screenshot, so systems notifications won't be included. @bitsandfoxes knows in more details and can chime in

**Comment by bruno-garcia** [comment]
The outcome of this thread should go on the docs to help clarify how it works for other customers*

**Comment by bitsandfoxes** [comment]
Hi @polynatic! Good point!
The Unity SDK uses Unity's built-in [ScreenCapture](https://docs.unity3d.com/ScriptReference/ScreenCapture.html) functionality. You can take a look at the actual code here: https://github.com/getsentry/sentry-unity/blob/093569840f6cdb3c43de72d529bd1452a5ba7f41/src/Sentry.Unity/ScreenshotAttachment.cs#L70

In practical terms, this means that the screenshot only contains things visible within your game.

**Comment by bitsandfoxes** [comment]
But I think you're making a good point of adding an option to control the behavior of the native SDKs more finely and opt out of their screenshot capabilities.

**Comment by bitsandfoxes** [comment]
But @philipphofmann and @marandaneto, correct me if I'm wrong: An app cannot take a screenshot of things (i.e. popup notifications) that happen outside of it's scope/activity.

**Comment by polynatic** [comment]
Thanks! Yes, I'm almost sure it's not possible to capture anything other than what is happening in the own process. I just don't know 100% so I wanted to ask. Especially, since the documentation of the screenshot functionality mentions possible PII being captured. That made me a bit more cautious. I think it would be good to mention that this PII could only be coming from the game/app itself if it is displaying any somewhere and never notifications or OS functionality.

**Comment by philipphofmann** [comment]
Yes, the app can only take screenshots of its process. The screenshots might contain PII of your app. For example, if during registration an error happens, the screenshot could contain PII of the registration form.
