### ISSUE TITLE
View Hierarchy

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1183]
RFC: https://github.com/getsentry/rfcs/pull/33/files

- [x] Capture the currently active scene hierarchy: https://github.com/getsentry/sentry-unity/pull/1169
- [ ] Capture scenes that have been loaded additionally
- [ ] Separate UI from the View Hierarchy to make use of the wireframe

**Comment by kahest** [comment]
Depends on .NET impl https://github.com/getsentry/sentry-dotnet/pull/2163

**Comment by bruno-garcia** [comment]
THis was done throuhg: https://github.com/getsentry/sentry-unity/pull/1169
