### ISSUE TITLE
Hints

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1206]
As of right now, Screenshots (and soon View Hierarchy) get attached as attachments to the scope. We do this during initialization which means that if the user clears the scope that functionality is no longer available.
Additionally, users don't have access or control over those during the `beforeSend` callback.
Ideally, we would provide `Hints` instead.

Relevant PRs on the Java SDK seem to be
- https://github.com/getsentry/sentry-java/pull/2045/files
- https://github.com/getsentry/sentry-java/pull/2046/files

**Comment by mattjohnsonpint** [comment]
Will primarily be handled with https://github.com/getsentry/sentry-dotnet/issues/1469

**Comment by bitsandfoxes** [comment]
Closing this in favor of the .NET SDK issue.
