### ISSUE TITLE
Make ANR detection timescale agnostic

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1214]
The ANR detection right now uses a coroutine to detect if the main thread failed to update for `ANR-timeout` amount of time.
It uses `WaitForSeconds` to sleep but this is based on [`Time.timescale`](https://docs.unity3d.com/ScriptReference/Time-timeScale.html) and will therefore not update if the scale is set to 0, effectively giving false positives in those cases.

Instead of relying on `WaitForSeconds` we could calculate the sleep duration based on `Time.realtimeSinceStartup`.

**Comment by mattjohnsonpint** [comment]
Or [`Time.unscaledTime`](https://docs.unity3d.com/ScriptReference/Time-unscaledTime.html)?
