### ISSUE TITLE
"po" command fails to work after importing XCFramework

### ISSUE THREAD

**Issue by ketourneau** [getsentry/sentry-unity#1221]
We use Unity Player as a Library in swift application.
Since we add the Sentry.xcframework in the swift app, we got error when we try to debug swift application with `po` :

<img width="872" alt="Capture d’écran 2023-03-10 à 08 19 20" src="https://user-images.githubusercontent.com/39763266/224249482-fb089c05-f093-4df3-8365-6d018056e97a.png">

```bash
(lldb) po test
error: expression failed to parse:
error: virtual filesystem overlay file '/Users/runner/Library/Developer/Xcode/DerivedData/Sentry-flrkvpsjgpginqarnqzgknsbozqs/Build/Intermediates.noindex/ArchiveIntermediates/Sentry/IntermediateBuildFilesPath/Sentry.build/Release-iphoneos/Sentry.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/runner/Library/Developer/Xcode/DerivedData/Sentry-flrkvpsjgpginqarnqzgknsbozqs/Build/Intermediates.noindex/ArchiveIntermediates/Sentry/IntermediateBuildFilesPath/Sentry.build/Release-iphoneos/Sentry.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

We find some topics about this error if it's can help : 
https://github.com/facebook/facebook-ios-sdk/issues/1628
https://developer.apple.com/forums/thread/708402
https://steipete.com/posts/couldnt-irgen-expression/

Maybe you need to add `-no-serialize-debugging-options` while building frameworks ?

**Comment by bitsandfoxes** [comment]
Hey @ketourneau thanks for bringing this up and the additional context! Let me bring this to the team.

**Comment by bitsandfoxes** [comment]
Does it work if you disable `iOS native support'?

**Comment by ketourneau** [comment]
If i disable `iOS native support`, Unity build still contain `Sentry.xcframework`.

If I build Swift app without `Sentry.xcframework` and with `iOS native support disabled` in Unity, I got error : 
```
dyld[4132]: Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: <F0CAC742-247C-3DBE-B0BB-30271F33D1D5> /private/var/containers/Bundle/Application/E1104CE3-12E7-46D9-AEC4-88575B7263C5/NativeSentry.app/Frameworks/UnityFramework.framework/UnityFramework
```

And if I hade Sentry.xcframework I can't use "po" command for debugging swift app.

**Comment by bitsandfoxes** [comment]
There is a release `1.2.0` coming out later today that aims to enable (or at least stop hindering) exporting Unity games as library. The SDK no longer modifies the exported Xcode project which should take care of any duplication issues.
Please feel free to reopen this if the issue persists.
