### ISSUE TITLE
0x4200000000000000000000000000000000000042

### ISSUE THREAD

**Issue by Amitkumaroo77** [getsentry/sentry-unity#1244]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?

How did you install the package? (Git-URL, Assetstore)

Which version of Unity?

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by vaind** [comment]
Closing since this is just the issue template text without any details given.
