### ISSUE TITLE
Multiple precompiled assemblies with the same name

### ISSUE THREAD

**Issue by rosterplayer** [getsentry/sentry-unity#1245]
### Environment

Sentry Unity SDK 1.1.0

### Steps to Reproduce

After installation via UPM got errors

### Expected Result

No errors

### Actual Result

Errors:

Multiple precompiled assemblies with the same name Microsoft.Extensions.FileSystemGlobbing.dll included on the current platform. Only one assembly with the same name is allowed per platform. (Assets/Plugins/Microsoft.Extensions.FileSystemGlobbing.dll)

Multiple precompiled assemblies with the same name Microsoft.Extensions.FileSystemGlobbing.dll included on the current platform. Only one assembly with the same name is allowed per platform. (*UNITY_PROJECT*/Library/PackageCache/io.sentry.unity@3e83308f1f/Editor/Microsoft.Extensions.FileSystemGlobbing.dll)

**Comment by bitsandfoxes** [comment]
Thanks for raising this. Will be fixed asap.
