### ISSUE TITLE
Extra segfaults in multiplayer VR project for Quest 2

### ISSUE THREAD

**Issue by samiamlabs** [getsentry/sentry-unity#1252]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
1.1.0

How did you install the package?
Git-URL

Which version of Unity?
2021.2.11f

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Only on the Quest 2 nativly, not in the editor (as far as I have seen)

### Steps to Reproduce

I don't really know how to reproduce it or what is causing it :/
Run a complex app with photon PUN networking and VR things I guess...

### Expected Result
Sentry should be able to help me find logs of things that only happen when many people are using the app at the same time. This would be very useful becase I have a lot of code that only runs when there are multiple players and they do some edgecase thing.

### Actual Result
Extra segfaults that don't seem to happen anymore if i disable sentry and very little information about why the segfaults are happening.

### Any logs or screenshots
Some examples:
![image](https://user-images.githubusercontent.com/5682888/227776300-6951afe1-224a-41b0-94bf-c8d798b67e7d.png)
![image](https://user-images.githubusercontent.com/5682888/227776399-a4ca8a7d-6e36-46cb-ab6b-e8abcc4c491e.png)
![image](https://user-images.githubusercontent.com/5682888/227776429-a13cbbb9-430e-4f53-88ed-cd25224fe77e.png)
![image](https://user-images.githubusercontent.com/5682888/227777603-d02771bf-a794-4f41-b54b-2a28e745b7f6.png)

**Comment by bitsandfoxes** [comment]
Hey @samiamlabs, sorry you're running into this issue. Are you using IL2CPP as your scripting backend?

**Comment by bitsandfoxes** [comment]
Do you happen to have any logs from the time of the crash? Could you share the events with me? Either here or at stefan@sentry.io

**Comment by samiamlabs** [comment]
I can pay for "Team" and share the sentry projects with you if that works for you @bitsandfoxes
I have no other logs.

**Comment by bitsandfoxes** [comment]
You can just send me the link to the sentry event.

**Comment by samiamlabs** [comment]
https://dyno-robotics.sentry.io/issues/3710554500/events/faa88bcf81ec4ab923007dbfdd80a909/

Does that work? :)

**Comment by samiamlabs** [comment]
![image](https://user-images.githubusercontent.com/5682888/228786102-9baa296c-1679-4269-929c-e8c29eea851f.png)

The segfaults all seem to have that message.

**Comment by bruno-garcia** [comment]
@tustanivsky @bitsandfoxes any of you guys had a chance to look into this repro? curious if we can close this ticket

**Comment by samiamlabs** [comment]
I think you can close the ticket.
I have used sentry in a similar project since then without running into this issue.

**Comment by bitsandfoxes** [comment]
Thanks for the update!
