### ISSUE TITLE
BeforeSend is never called

### ISSUE THREAD

**Issue by perholmes** [getsentry/sentry-unity#1256]
### Environment

Using Sentry in a Unity app, SDK version 1.1.0, package installed from GitURL.

BeforeSend is somehow never called anymore.

It's registered in both the runtime and buildtime scripts (generated by the Sentry wizard in Unity). I simply have a log statement, which never appears in the logs when an exception is triggered. I do see all the "Sentry: {info}" log statements about the send.

```
options.BeforeSend = sentryEvent =>
{
    Debug.Log("***** Sentry level before send, BuildTime configured: " + sentryEvent.Level);
}
```

Since this doesn't work, I also reenabled the old way of initializing, which used to be called early during app init:

```
SentryUnity.Init(o =>
{
    o.BeforeSend = BeforeSend;
});

public static SentryEvent BeforeSend(SentryEvent evt)
{
    Debug.Log("***** Old BeforeSend: " + evt.Level);
}
```

I've run out of things to try.

**Comment by bitsandfoxes** [comment]
Sorry for the inconvenience. There were some breaking changes with `1.0.0`. Could you confirm that the scriptable objects are assigned in the editor window `Options Config` tab?

**Comment by perholmes** [comment]
I'm struggling a lot with the documentation. I've gone through the documentation line by line several times, and the following is not covered:

* What role does the configuration window play if I'm intending to *only* do programmatic configuration? Which settings take precedence over other settings? Do runtime config options override the dialog, or does the dialog override the options?
* How can the runtime/buildtime script selection be configured without using the window?
* What happens if the Enable checkbox is disabled? Do the runtime/buildtime options still execute? Are they still configured here? Or does all of Sentry get disabled.
* Is there a proper way to do **pure** programmatic initialization that does not in any way involve the control panel?

I'm terribly unclear on the interaction between the control panel and programmatic initialization. They seem to have about 80% overlap, and it's not clear which takes precedence or even which one runs under which circumstances.

There's also definitely a bug on the Options Config page. I've now had to delete and recreate the scripts four times. If a runtime/buildtime script is moved, it's simply impossible to get the control panel to recognize it. It cannot be dropped on the field and it can't be selected by pressing the target button. The only way to get them recognized is to create them again from scratch, copy code over from the old scripts, and then delete the old scripts.

**Comment by bitsandfoxes** [comment]
The flow looks like this:
1. The editor window creates a ScriptableObject `ScriptableSentryUnityOptions` that holds all the data set on the window.
2. The `ScriptableSentryUnityOptions` has 2 slots for user-defined ScriptableObjects - `Runtime` and `BuildTime` config
3. Triggered by the attribute `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]` the SDK starts to try to initialize itself
4. It loads the `ScriptableSentryUnityOptions` from disk and creates `SentryUnityOptions`
5. The user-defined `RuntimeConfig.Configure` callback gets invoked 
6. The callback gives the option to programmatically modify the data loaded from disk and implement i.e. the `BeforeSend` callback
7. The SDK takes back the modified `SentryUnityOptions` and if those are valid (i.e. `Enabled == true`) actually initializes itself

The sequence above is true for runtime. That includes running in the editor.

The mobile and macOS platforms are special cased in the sense that their native SDKs are set up during build-time. The Xcode and gradle projects get modified to allow for their platform specific native SDKs to initialize themselves as soon as possible (even before the Unity game itself runs).
That means it is no longer possible to make changes to the options during runtime.
To allow for programmatic changes to those settings (i.e. set the environment or release) the BuildTimeConfig get invoked during the build process in the editor. Unfortunately, if you do make programmatic changes to those options you'll need to make them on both, the `RuntimeConfig` **and** the `BuildTimeConfig`.

> What role does the configuration window play if I'm intending to only do programmatic configuration? Which settings take precedence over other settings? Do runtime config options override the dialog, or does the dialog override the options?

The runtime config options override the window options.

> How can the runtime/buildtime script selection be configured without using the window?

The runtime/buildtime configs are intended to be used in conjunction with the window.

> What happens if the Enable checkbox is disabled? Do the runtime/buildtime options still execute? Are they still configured here? Or does all of Sentry get disabled.

The runtime/buildtime configure call still gets invoked but the SDK itself will not initialize. 

> Is there a proper way to do pure programmatic initialization that does not in any way involve the control panel?

If you really want to completely disable any and all self initialization you can embed the package and delete `SentryInitialization.cs`

> There's also definitely a bug on the Options Config page. 
Thanks for reporting this. I'll try to reproduce this locally.

**Comment by perholmes** [comment]
Perfect, thank you!
