### ISSUE TITLE
Reproducible application crash when 'android native support' is enabled

### ISSUE THREAD

**Issue by JPerryOddGames** [getsentry/sentry-unity#1277]
### Environment

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which version of the SDK?**
Reproducible on 1.1.0 & 1.2.0

**How did you install the package?**
Git url via Unity's Package Manager

**Which version of Unity?**
Unity 2021.3.21f1

**Is this happening in Unity (editor) or on a player like Android, iOS, Windows?**
Occurs on Android when 'Android Native Support' is enabled. Disabling this option stops the application from crashing.
Reliably reproducible on my test device Samsung Galaxy S8 (**SM-G950F**) running **Android 9**.

### Steps to Reproduce

1. Add the reproduction script (included at the bottom of this post) to the project.
2. Create a new scene, add the script to a GameObject. Add the scene to the build settings so it's included in build.
3. Ensure 'Android Native Support' is enabled in Sentry configuration.
4. Build & run the game.
5. Triple-tap the screen to cause a crash. A debug log will appear before the crashing method is invoked.

### Expected Result

Application should not crash, and Sentry should be able to create a report about the native error.

### Actual Result

The application crashes, and no report comes through on sentry.io

### Reproduction script

```
using System.Runtime.CompilerServices;
using UnityEngine;

public class SentryCrashReproduce : MonoBehaviour
{
    [MethodImpl(MethodImplOptions.NoOptimization)]
    private void Update()
    {
        if (Input.touchCount > 0 && Input.GetTouch(0).tapCount == 3)
        {
            Debug.Log("Triple-tap detected, doing crash");

            // Accessing the '.bytes' property on a null reference produces an exception that kills Sentry
            TextAsset textAsset = null;
            var bytes = textAsset.bytes;
        }
    }
}

```

**Comment by bitsandfoxes** [comment]
Thanks again for reporting this with the repro steps. Unfortunately, even with the very same Unity version, I cannot reproduce this issue locally.

I don't see how the C# NullReferenceException could interfere with the Android Native layer other than through the scope sync and I'm wondering if you're implementing the configure callback?

**Comment by JPerryOddGames** [comment]
Thanks for the reply @bitsandfoxes. Sorry for the delay, just saw your response.

I've created fresh builds of my repro project this morning and can confirm it's definitely an issue. The reproduction project is a new blank project with only a test script. The configure callback is not implemented.

I've [provided the entire project](https://github.com/JPerryOddGames/Sentry_AndroidNativeSupport_Crash_Repro) including project settings, library files, etc (no gitignore) just in case I'm unintentionally doing something dumb or unexpected. The project include two .apk builds in the Builds folder - only one crashes and the only difference was enabling the 'Android Native Support' option.

As an aside, I'm also pretty confused about how a NullReferenceException would be problematic. Initially I found this issue working with a destroyed TextAsset and figured it was an issue with the extern call, but I can 100% confirm it's crashing when directly accessing a null object. Bizarre.

Thanks for looking into this issue. If there's any more info I can provide please let me know

**Comment by bitsandfoxes** [comment]
Thanks for the sample project. 
Update: I can repro this issue and it's isolated to building with `Mono`. Let's see what's going on there.

**Comment by bitsandfoxes** [comment]
Turns out that this never worked with truly unhandled exceptions. The native Android support is now disabled for Mono builds so as to not accidentally lead to crashes. Apologies.
We're tracking the lack of support with https://github.com/getsentry/sentry-unity/issues/1386
