### ISSUE TITLE
"Environment" variable is being ignored and data is still defaulting to "editor" and "production"

### ISSUE THREAD

**Issue by travis-tap-3d** [getsentry/sentry-unity#1303]
### Environment

How do you use Sentry?

I use the sentry.io SaaS (latest?)

Which version of the SDK?

1.2.0

How did you install the package? (Git-URL, Assetstore)

Package manager (git url)

Which version of Unity?

2021.3.23f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

Happens in both Editor or builds, always either "editor" or "production" reported

### Steps to Reproduce

1. Override environment variable like this:
            SentryUnity.Init(o =>
            {
                o.Environment = "dev";
            });
2. Send a message right after like this:
             SentrySdk.CaptureMessage("Env is dev");

### Expected Result

Environment should show up in the sentry report as "dev"

### Actual Result

Environment shows as "editor" (or "production" if in a build?)

### Any logs or screenshots
<img width="316" alt="image" src="https://user-images.githubusercontent.com/113315968/235462642-15ec06ae-9f57-43a3-a2d6-35bfbb7624d1.png">

**Comment by travis-tap-3d** [comment]
Disregard - for some reason, I have to manually set the Dsn variable as part of that block (despite already  being set in the Sentry settings) to get it to record the environment.

**Comment by bitsandfoxes** [comment]
Hey,
it looks like you want to make programmatic changes to the options object before the SDK initializes.
The recommended way to do with is to use the `Configure` callback in the [Runtime Configuration](https://docs.sentry.io/platforms/unity/configuration/options/#programmatic-configuration).
