### ISSUE TITLE
Unity Crash: Deleting config while Sentry window open

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#131]
### Environment

Unity:   2021.1.1f1
Sentry: 0.0.8

### Steps to Reproduce

1. Open Tools->Sentry
2. Delete Sentry directory in Assets/Resource/
3. Close Sentry window

### Expected Result

Not to crash. Errors / warnings / Sentry window closing itself.

### Actual Result

Unity crashes.

**Comment by semuserable** [comment]
Can't reproduce on 2019.4.18f1.

**Comment by bitsandfoxes** [comment]
closed by https://github.com/getsentry/sentry-unity/pull/196
