### ISSUE TITLE
SentryBuildtimeOptionsConfiguration & SentryRuntimeOptionsConfiguration NOT overwriting option RELEASE on v1.2.0

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1311]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
1.2.0
How did you install the package? (Git-URL, Assetstore)
Git-URL
Which version of Unity?
2020.3.15f
Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android & iOS
### Steps to Reproduce

1. Build apk or ipa

### Expected Result

RELEASE option being overwritted

### Actual Result

With v.0.28.0 SentryBuildtimeOptionsConfiguration & SentryRuntimeOptionsConfiguration were overwriting sentry default options included RELEASE option before app being builded or runned. But with v1.2.0 RELEASE option is NOT overwritted but other options are.

**Comment by bitsandfoxes** [comment]
I'll give that a try. Thanks for reporting this!

**Comment by bitsandfoxes** [comment]
@ArnauKokoro I can't reproduce this. "It works on my machine" (tm).
Can you confirm that the config call in the Scriptable Objects are getting called? Are they assigned in the editor config window? With the `1.0.0` release there were some breaking changes and the objects got unassigned.

**Comment by ArnauKokoro** [comment]
I'll re-create that scriptable scripts and I will tell you.

Thanks!

**Comment by ArnauKokoro** [comment]
It works re-creating SentryBuildtimeOptionsConfiguration and SentryRuntimeOptionsConfiguration on the editor settings and copying & pasting what I had on the old ones.

Thanks!

**Comment by bitsandfoxes** [comment]
Thanks for the update! Glad it worked out!
