### ISSUE TITLE
Could not find method implementation() for arguments [{name=sentry-android-ndk-release, ext=aar}] (Sentry-Unity-v1.2.0)

### ISSUE THREAD

**Issue by lordaku** [getsentry/sentry-unity#1317]
### Environment

Which version of the SDK?
Sentry Unity Plugin (v1.2.0)

How did you install the package? Git-URL

Which version of Unity? 2021.2.22 LTS

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
While I'm trying to generate a Build. That issue started when I changed from version 1.0.0 to version 1.2.0. With 1.0.0 version I didn't have any issue.

### Expected Result

Generating a valid apk

### Actual Result

No apk.

What actually happened. Maybe a screenshot/recording? Maybe some logs?

### Any logs or screenshots
stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/fgarcia/Documents/Development/Sim_Unity2020/Unity Project/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> Could not find method implementation() for arguments [{name=sentry-android-ndk-release, ext=aar}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<img width="688" alt="Screenshot 2023-05-10 at 08 10 00" src="https://github.com/getsentry/sentry-unity/assets/20879915/25a905dd-8447-42b2-9439-51906ed1e9d0">

**Comment by bitsandfoxes** [comment]
Thanks for reporting this. We'll fix that!
