### ISSUE TITLE
Unity DevOps - Sentry Exception for iOS

### ISSUE THREAD

**Issue by aicukltd** [getsentry/sentry-unity#1338]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) integration into Unity 2D app for iOS and Android

Which version of the SDK?
1.2.0

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2022.2.19F

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Unity Build Pipeline

### Steps to Reproduce

1. Add Sentry 1.2.0 to Unity Project
2. Commit to Unity DevOps
3. Build with xCode >14.0

### Expected Result

It builds like it has done every time successfully until right now.

### Actual Result
```
[error] [warning] [2023-05-23T13:27:27.286Z] - 7.3.12.2.7.4 - INFO: ▸ ⚠️  /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-aegfrsbcpkxswibtzephvovlecep/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/Sentry.framework/Headers/Sentry.h:18:9: double-quoted include "SentryError.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
[error] [2023-05-23T13:27:27.286Z] - 7.3.12.2.7.4 - INFO: ▸ #import "SentryError.h"
```

**Comment by bitsandfoxes** [comment]
Thanks for raising this @aicukltd. We'll look into this.

**Comment by bitsandfoxes** [comment]
It's just odd that it complains about a "random" include. Could you provide us with the full build logs?

**Comment by bitsandfoxes** [comment]
We've updated the way the SDK integrates native iOS support. Please feel free to reopen this issue if it still persists for you in version `1.5.0` or newer.
