### ISSUE TITLE
jetified-sentry-android-6.25.0-runtime.jar is missing in the map.

### ISSUE THREAD

**Issue by lordaku** [getsentry/sentry-unity#1391]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
 Sentry 1.4.1

How did you install the package? 

Git-URL

Which version of Unity?
2021.3.22   LTS

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

While Android Compilation

### Actual Result

Not valid executable. 

### Any logs or screenshots

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:dexBuilderRelease'.
> Multiple task action failures occurred:
   > Key /root/.gradle/caches/transforms-2/files-2.1/ca9e55a0bf3aa9d64c2c9dabd77764b1/jetified-sentry-android-6.25.0-runtime.jar is missing in the map.
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > No services are registered. Ensure the worker actions use IsolationMode.NONE.
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > No services are registered. Ensure the worker actions use IsolationMode.NONE.

**Comment by bitsandfoxes** [comment]
@lordaku sorry about that. We'll fix that asap.
