### ISSUE TITLE
Setting event verbosity in settings

### ISSUE THREAD

**Issue by ksenchE** [getsentry/sentry-unity#1394]
**Unity SDK version is 1.5.0**

Hi there,
Hope you are doing well! 
I have an issue with events, which is automatically sent by Sentry package (like Info, Debug and Warning). I have a lot of logs in a game and every Debug.Log, Debug.LogWarning are being sent to Sentry (which I don't need to be sent, except I'm calling SentrySdk.CaptureMessage explicitly). I know that I can set BeforeSend event to sdk, but it also filters messages from SentrySdk.CaptureMessage, so it's not an option for me.

On the top of that, it would be great if you add Verbosity toggle to Sentry settings where I can choose which log level will be sent to Sentry automatically through log handler
(like you did it for Sentry Debug Output)
![image](https://github.com/getsentry/sentry-unity/assets/136596908/fb883056-9126-4439-9ff6-88820a58d95c)

**Comment by bitsandfoxes** [comment]
Hey @ksenchE, thanks for reaching out!
The SDK should only automatically capture and send events in case of actual unhandled exceptions and instances of 
- `Debug.LogAssertion()`
- `Debug.LogError()`
- `Debug.LogException()`
Simple logs and warnings should not create a sentry event but breadcrumbs that are part of the next event.

**Comment by ksenchE** [comment]
Hi @bitsandfoxes, thanks for getting back!

Yes, but I've searched through Sentry code and figured out that it captures logs with UnityLogHandlerIntegration. Also, there are debounce options in Sentry settings, so it makes sense for me

**Comment by bitsandfoxes** [comment]
I'm not sure what it is exactly you're looking for.
If you want to disable the logging integration you can call `DisableUnityApplicationLoggingIntegration` from within the configure callback. That should give you full control over what gets sent to Senty, i.e. if you have your own `unhandled exception` handling mechanism

**Comment by ksenchE** [comment]
Thank you very much, that has helped me!
I've stumbled into another issue though. When I call **SentrySdk.Init(Action<SentryOptions>? configureOptions)** method, I get default sentry options (screenshot 1)

![image](https://github.com/getsentry/sentry-unity/assets/136596908/a0a2a90e-76b3-441b-b713-d3207e6b7108)

And this is how my options look like when I load it from scriptable object (screenshot 2)

![image](https://github.com/getsentry/sentry-unity/assets/136596908/257ca763-5b02-4077-a81b-f7b5526728ff)

I thought it shouldn't work this way, because I have to set every option from SO again. I've tried to load SO with settings and copy it's data to new SentryOptions object, but I have IOException like
`IOException: The process cannot access the file 'C:\Users\User\AppData\LocalLow\CompanyName\ProjectName\Sentry\E55976AF18EBE6031DCD7F459A5A9E954FCA4280\__processing\1690187716_-5815__-1512035672.envelope' because it is being used by another process.
System.IO.FileSystem.DeleteFile (System.String fullPath) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
System.IO.File.Delete (System.String path) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
Sentry.Internal.FileSystem.DeleteFile (System.String path) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/FileSystem.cs:44)
Sentry.Internal.Http.CachingTransport.InnerProcessCacheAsync (System.String file, System.Threading.CancellationToken cancellation) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/Http/CachingTransport.cs:350)
Sentry.Internal.Http.CachingTransport.ProcessCacheAsync (System.Threading.CancellationToken cancellation) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/Http/CachingTransport.cs:269)
Sentry.Internal.BackgroundWorker.DoFlushAsync (System.Threading.CancellationToken cancellationToken) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/BackgroundWorker.cs:286)
Sentry.Internal.BackgroundWorker.FlushAsync (System.TimeSpan timeout) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/BackgroundWorker.cs:218)
Sentry.Internal.BackgroundWorker.FlushAsync (System.TimeSpan timeout) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/BackgroundWorker.cs:234)
Sentry.SentryClientExtensions.Flush (Sentry.ISentryClient client, System.TimeSpan timeout) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentryClientExtensions.cs:89)
Sentry.Internal.Hub.Dispose () (at /sentry-unity/src/sentry-dotnet/src/Sentry/Internal/Hub.cs:487)
Sentry.SentrySdk.UseHub (Sentry.IHub hub) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentrySdk.cs:157)
Sentry.SentrySdk.Init (Sentry.SentryOptions options) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentrySdk.cs:152)
Sentry.SentrySdk.Init (System.Action`1[T] configureOptions) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentrySdk.cs:130)`

**Comment by ksenchE** [comment]
@bitsandfoxes
I've found a way to avoid this IOException by decreasing shutdown timeout to 50 ms. But I'm not sure about consequences of this move. I've also tried to manually flush queued events before re-init. Therefore I still get this IOException

**Comment by bitsandfoxes** [comment]
It sounds like the SDK might get initialized multiple times.
If you want to initialize the SDK yourself you should disable it in the editor window and then call `SentryUnity.Init` wherever you want to have it initialized. Note that the Scriptable Object is tied to the self-initializing. So if you call init then you don't need the SO.

**Comment by ksenchE** [comment]
Yes, but my concern is that I want to change one option (Sample Rate) at the game start after I get configs from our server. So I need a way to change only this option. Disabling Sentry and then initializing it somewhere sounds bad. Because there could be cases with critical errors and exceptions which is not being caught in the time gap between game start and sentry initialization

**Comment by bitsandfoxes** [comment]
That's tricky. Can you fetch the config during the configure callback in the scriptable object?

**Comment by ksenchE** [comment]
Yes, I've tried to load SO with Sentry options and pass all values to new sentry options in callback. I'm getting an exception I've mentioned above (IOException). Also, this way looks bad for project architecture, I think. Cause I need to pass all values again just to change one option...

I've found a way decreasing Shutdown timeout to zero and then calling SentrySdk.Init(SentryOptions options). Options I get with **ScriptableSentryUnityOptions.LoadSentryUnityOptions(new SentryUnityInfo())**, pass my trace limit to it and then call **SentrySdk.Init(SentryOptions options)**

**Comment by bitsandfoxes** [comment]
Alternatively, you can always [embed the Sentry package](https://docs.unity3d.com/Manual/upm-embed.html). That way you have access to the `SentryInitialization.cs` and that gives you even more control over what gets initialized when and how.
I'm closing this issue since we've strayed quite a bit from the original context. Please feel free to create a [new discussion](https://github.com/getsentry/sentry-unity/discussions) or join us in the [discord channel](https://discord.com/channels/621778831602221064/621783582628642822).
