### ISSUE TITLE
Need to be able to customize IPostGenerateGradleAndroidProject.callbackOrder

### ISSUE THREAD

**Issue by eefan000** [getsentry/sentry-unity#1411]
Some SDKs in my project will completely cover AndroidManifest.xml, so Sentry needs to be executed later

**Comment by bitsandfoxes** [comment]
Thanks for reaching out. Why is that? What exactly is causing issues?

**Comment by eefan000** [comment]
> Thanks for reaching out. Why is that? What exactly is causing issues?

Some advertising SDKs from channel providers also use IPostGenerateGradleAndroidProject to modify AndroidManifest.xml, but the implementation is relatively poor, directly covering the entire file instead of adding modifications.

This resulted in the AndroidManifest.xml modified by Sentry being overwritten.

Ultimately, it leads to a lack of dependencies or configuration in the packaged version

**Comment by bitsandfoxes** [comment]
Could you provide a sample of what a completely overhauled `AndroidManifest.xml` looks like so we can make sure it'll work?
