### ISSUE TITLE
Transaction/Span.StartTimestamp is set to 01.01.0001 00:00:00 +00:00 instead of DateTime.UtcNow

### ISSUE THREAD

**Issue by BaalEvan** [getsentry/sentry-unity#1431]
# Edit:
### Environment

How do you use Sentry?
SentryIO.

Which version of the SDK?
1.5.1

How did you install the package? (Git-URL, Assetstore)
GitURL (Package)

Which version of Unity?
2021.3.17

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Editor

### Steps to Reproduce
1. I Created new transaction like this:
`_buildTransaction = SentrySdk.StartTransaction("ApplicationContext.Build", "Build");`
2. after few seconds i finished it.
3. _buildTransaction.StartTimestamp is equal to 01.01.0001 00:00:00 +00:00;

### Expected Result

Transaction.StartTimestamp should be equal to DateTime.UtcNow;

### Actual Result

Transaction.StartTimestamp is equal to: "Jan 1, 0001 00:00:00 UTC (-62135596800)"
![image](https://github.com/getsentry/sentry-unity/assets/1843494/c776e9c5-b57d-48b4-b454-6f3161bf3da5)
same problem with default transactions:
![image](https://github.com/getsentry/sentry-unity/assets/1843494/b80f2d44-4f98-4c71-bfdc-dc21ec3d2f77)
![image](https://github.com/getsentry/sentry-unity/assets/1843494/bae502bf-db88-44c1-9ab0-1e25752f66b2)
![image](https://github.com/getsentry/sentry-unity/assets/1843494/dce858e7-041b-4446-bc81-87a46068dadd)

**Comment by BaalEvan** [comment]
I tested it in comparsion to pure .net Framework using code like this:
```
            Console.WriteLine("Hello, World!");

            SentrySdk.Init(options =>
            {
                options.Dsn = "REDACTED"
                options.Debug = false;
                options.AutoSessionTracking = true;
                options.IsGlobalModeEnabled = true;
                options.EnableTracing = true;
                options.TracesSampleRate = 1;
            });
            SentrySdk.CaptureMessage("Something went wrong");
            var lenght = new Random().Next(0, 2137);
            var secondLenght = new Random().Next(0, 2137);
            var transaction = SentrySdk.StartTransaction(
                "test-transaction-name",
                "test-transaction-operation"
            );

            Console.WriteLine(transaction.StartTimestamp); 
            Thread.Sleep(lenght);
            var span = transaction.StartChild("test-child-operation");
            Thread.Sleep(secondLenght);
            span.Finish(); 
            transaction.Finish();
            Console.WriteLine($"Waited for: {lenght}");
            Console.WriteLine($"Then waited for: {secondLenght}");
```
and i got text like this in console 
```Hello, World!
02.09.2023 13:43:34 +00:00
Waited for: 1051
Then waited for: 1522```

Same code used in Awake in unity (console.writeline changed into debug.logs)
returns this: 
![image](https://github.com/getsentry/sentry-unity/assets/1843494/943b42cf-d4d2-4fbd-a36a-a6063a3007ec)

**Comment by BaalEvan** [comment]
Replacing package 1.5.1 with Sentry.dll from nuget package 3.36 (net461) + adding bunch of dlls from microsoft as dependency:

```
Sentry.dll
-System.Text.Json.dll
--Microsoft.Bcl.AsyncInterfaces.dll
--System.Collections.Immutable.dll
--System.Reflection.Metadata.dll
--System.Runtime.CompilerServices.Unsafe.dll
--System.Text.Encodings.Web.dll
```
Allowed me to get a correct timestamp, but it will also cause problems with the build process for different platforms, so this is a no-go for me, BUT I hope this will help you to resolve the issue, as we know that sentry.dll for Windows is most likely a culprit.

![image](https://github.com/getsentry/sentry-unity/assets/1843494/bb22e6fd-6018-48fa-a928-59e20a36fdd5)

I created example project for comparsion with steps to compare net461 dll from nuget to package:
[SentryTransactionTest.zip](https://github.com/getsentry/sentry-unity/files/12504188/SentryTransactionTest.zip)

Open scene: `Scenes/SampleScene`
Sentry Loader is on scene, press play to get logs.
For now it is using dll from sentry 3.36.0 for net 4.6.1 so timestamp will be correct

If you want to replace with package follow this steps:
1: Add https://github.com/getsentry/unity.git#1.5.1 to package manager
2: Go to `Plugins` directory and delete `Sentry461Nuget` directory
3: Press play
4: Now you can see wrong timestamp in console

**Comment by HarshitPersona** [comment]
How to fix this issue in Unity if I am using Sentry version 1.5.1 added through the git url as mentioned in the Sentry Unity doc?

**Comment by bitsandfoxes** [comment]
Sorry about that and thanks for raising it! The next release will contain the fix.

**Comment by HarshitPersona** [comment]
Thanks for the update!

**Comment by bitsandfoxes** [comment]
The `1.5.2` contains the bumped .NET SDK version. Thanks again!

**Comment by HarshitPersona** [comment]
Hey @bitsandfoxes , 1.5.2 seems to be working fine, thanks for the quick fix to the issue. Will let you know in case of any other issues.
