### ISSUE TITLE
Xcode Cloud Build error

### ISSUE THREAD

**Issue by hjupter** [getsentry/sentry-unity#1435]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
SaaS

Which version of the SDK?
1.5.2

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.12f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Xcode Cloud Build only

### Steps to Reproduce

1. Make a build with GameCI using GH actions
2. Send it to Xcode cloud
3. Build fails due to missing path

### Expected Result

Build succeed just like it does with manual builds

### Actual Result
Missing path (/Volumes/workspace/repository/ClubEternalBridge/iOS/Frameworks/Sentry.xcframework/ios-arm64/dSYMs) from XCFramework 'Sentry.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file

### Any logs or screenshots
<img width="1030" alt="image" src="https://github.com/getsentry/sentry-unity/assets/1037359/01e53317-b261-4950-a5aa-f14fb4df6e73">

**Comment by bitsandfoxes** [comment]
Hey there, sorry you're running into issues.
It looks to me like there are parts of the `xcframework` missing? Do you have access to the project's files?
The `Sentry.xcframework` should look like this:
```
Sentry.xcframework
├── Info.plist
├── ios-arm64
│   ├── BCSymbolMaps
│   ├── Sentry.framework
│   └── dSYMs
│       └── Sentry.framework.dSYM
└── ios-arm64_x86_64-simulator
    ├── Sentry.framework
    └── dSYMs
        └── Sentry.framework.dSYM
```

**Comment by hjupter** [comment]
> Hey there, sorry you're running into issues. It looks to me like there are parts of the `xcframework` missing? Do you have access to the project's files? The `Sentry.xcframework` should look like this:
> 
> ```
> Sentry.xcframework
> ├── Info.plist
> ├── ios-arm64
> │   ├── BCSymbolMaps
> │   ├── Sentry.framework
> │   └── dSYMs
> │       └── Sentry.framework.dSYM
> └── ios-arm64_x86_64-simulator
>     ├── Sentry.framework
>     └── dSYMs
>         └── Sentry.framework.dSYM
> ```

Looks like when making the build with GameCI it doesn't generate the dSYMs folders
<img width="302" alt="image" src="https://github.com/getsentry/sentry-unity/assets/1037359/67033b89-45f2-4eca-a26f-48768d1414b9">
Any ideas?

**Comment by bitsandfoxes** [comment]
The `xcframework` is prebuilt and already contains them when you install the SDK. The directory gets copied "as is" to the generated Xcode project. I wonder if GameCI is ignoring/omitting them.
