### ISSUE TITLE
Unity Android Upload Symbols Proguard

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1439]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
1.5.2

How did you install the package?
Git-URL

Which version of Unity?
2020.3.15

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Proguard Automatically Upload Symbols

### Expected Result

Symbols related to a version

### Actual Result
Sentry Setting/Proguard Mapping list

All symbols says:

"No releases associated with this proguard mapping file"

### Any logs or screenshots
<img width="852" alt="Captura de pantalla 2023-09-09 a las 11 34 15" src="https://github.com/getsentry/sentry-unity/assets/80262126/d35050db-3e0c-42af-92ba-c76906fa5c32">

**Comment by bitsandfoxes** [comment]
Thanks for raising this issue!
Is this something that broke with an update of the SDK? Can you confirm that it previously worked?

**Comment by ArnauKokoro** [comment]
No, was not working either on other versions of the SDK.

**Comment by ArnauKokoro** [comment]
This is what Sentry generates on my gradle:

`sentry {
    // Disables or enables the handling of Proguard mapping for Sentry.
    // If enabled the plugin will generate a UUID and will take care of
    // uploading the mapping to Sentry. If disabled, all the logic
    // related to proguard mapping will be excluded.
    // Default is enabled.
    // includeProguardMapping = true

    // Whether the plugin should attempt to auto-upload the mapping file to Sentry or not.
    // If disabled the plugin will run a dry-run and just generate a UUID.
    // The mapping file has to be uploaded manually via sentry-cli in this case.
    // Default is enabled.
    // autoUploadProguardMapping = true

    // Experimental flag to turn on support for GuardSquare's tools integration (Dexguard and External Proguard).
    // If enabled, the plugin will try to consume and upload the mapping file produced by Dexguard and External Proguard.
    // Default is disabled.
    // experimentalGuardsquareSupport = false

    // Disables or enables the automatic configuration of Native Symbols
    // for Sentry. This executes sentry-cli automatically so
    // you don't need to do it manually.
    // Default is disabled.
    uploadNativeSymbols = true

    // Does or doesn't include the source code of native code for Sentry.
    // This executes sentry-cli with the --include-sources param. automatically so
    // you don't need to do it manually.
    // Default is disabled.
    includeNativeSources = true

    ignoredBuildTypes = ["debug"]
}`

**Comment by bitsandfoxes** [comment]
These are options set for the [Sentry Android Gradle Plugin](https://github.com/getsentry/sentry-android-gradle-plugin) which the Unity SDK does not rely on.

**Comment by bitsandfoxes** [comment]
Fixed by #1626
