### ISSUE TITLE
Feedback wanted: Experimenting with 'sentry.unity' SDK based on Sentry .NET SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#15]
The experiment is in this branch: 
https://github.com/getsentry/sentry-unity/tree/feature/sentry-unity

Basically it's the [Sentry .NET SDK](https://github.com/getsentry/sentry-dotnet) with a few customization via C# scripts which are compiled with the Editor and possible to be edited by the user.

The goal is to see if this is a feasible replacement of the `sentry.unity.lite` SDK which we currently offer in the `main` branch.

Limitation: Requires .NET 4.x or .NET Standard 2.0 scripting backend. Hence it needs Unity 2018.1+.

To clarify:
* Is it worth initializing the SDK via `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]` which requires a static method? That means that the shutdown of the SDK is awkward as it's based on a `MonoBehavior` which hopefully was initialized so that it can Close the SDK.
* If using the static init, how to take configurations from the editor? How is the user expected to pass the `DSN`? Right now it's just hard-coded in the script.
* IL2CPP test in release mode didn't work (link.xml not picked up?)
* Builds (release builds) are not grouped because stack trace includes mem addr as module name

Would the approach of the current `sentry.unity.lite` SDK be better? Keeping in mind that the Initialization of the SDK is itself static, and ideally Unity would expose a static callback to dispose the SDK but I'm unaware of any.

https://github.com/getsentry/sentry-unity/blob/e1b69e1460e8555b86a856ca2022ac3553b8eda3/Assets/Sentry/Scripts/SentrySdk.cs#L35-L65

The samples in the dashboard:

![image](https://user-images.githubusercontent.com/1633368/51266665-295cbb80-19bc-11e9-9985-5d4179022c08.png)

**Comment by demacianult** [comment]
I like this a lot! It is much cleaner than the current implementation. Here are my notes:
- I would stick to the singleton pattern http://wiki.unity3d.com/index.php/Singleton as it will solve a lot of the static init/uninit problems you describe
- I have had issues with bytecode stripping in release mode https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html as it can be over-aggressive so you may need to create "fake" references to ensure those symbols do not get stripped
- Code stripping here is really where this shines. We get the full features of the C# SDK while Unity can remove all the extra code we do not use for us. I think this is the best of both worlds

👍

**Comment by chrisse27** [comment]
I agree with the comments of @demacianult . Here are my comments:

> Is it worth initializing the SDK via [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)] which requires a static method? That means that the shutdown of the SDK is awkward as it's based on a MonoBehavior which hopefully was initialized so that it can Close the SDK.

Have a look at [SentryInitialization.cs](https://github.com/chrisse27/sentry-unity/blob/feature/static-initialization/Assets/Sentry/Scripts/SentryInitialization.cs). I have separated the initialization from the behaviour.

> If using the static init, how to take configurations from the editor? How is the user expected to pass the DSN? Right now it's just hard-coded in the script.

Have a look at [SentrySettings.cs](https://github.com/chrisse27/sentry-unity/blob/feature/static-initialization/Assets/Sentry/Scripts/SentrySettings.cs). The settings can reside in asset that is per default in the Resources folder of the Unity project.

IL2CPP test in release mode didn't work (link.xml not picked up?)

> This worked in my [branch](ttps://github.com/chrisse27/sentry-unity/blob/feature/static-initialization), so it should not be an effect of the static initialization.

**Comment by Stormy102** [comment]
@bruno-garcia Instead of using RuntimeInitializeOnLoadMethod, you can instead set the default script execution order through the `[DefaultExecutionOrder]` attribute which is discussed [here](https://forum.unity.com/threads/undocumented-but-public-defaultexecutionorder-attribute.530618/). Surely this would be a lot less cumbersome?

**Comment by RDeluxe** [comment]
Sounds great, I'm going to try this !

I join the other remarks, with the Singleton pattern (which makes sense here) and the `[DefaultExecutionOrder]` flag it should be perfectly fine

**Comment by RDeluxe** [comment]
I'm getting some issues making this work: I deleted the Newton soft dlls as I'm using a custom version (from there: https://github.com/jilleJr/Newtonsoft.Json-for-Unity#readme) 

> Error - Error while processing event: System.TypeLoadException: Could not load type of field 'Sentry.Internal.JsonSerializer:StringEnumConverter' (0) due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none>
  at Sentry.Internal.Http.HttpTransport+<CaptureEventAsync>d__5.MoveNext () [0x0001e] in <2e5a0891b22a4160bd1261a87d88cb3c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at Sentry.Internal.BackgroundWorker+<WorkerAsync>d__14.MoveNext () [0x00211] in <2e5a0891b22a4160bd1261a87d88cb3c>:0 . #0024d8093edd4087bde44a7f0e227122 in queue. - 

I'm not quite sure if the version is the problem (as I have jsondotnet 12.0 and not 11.0), but that's a weird error. I don't have the dll twice in my project

**Comment by bruno-garcia** [comment]
With the compiled code against json.net of a specific version with a specific strong name I wouldn't expect it to be possible to replace it. I don't think even with .NET Framework and binding redirects this would be possible.
So for using a custom json.net build, the only solution is to build the SDK against the custom json.net as you figured out.

**Comment by RDeluxe** [comment]
I've been testing this branch and everything seems pretty smooth with mono.

However after building with IL2CPP I don't get any information about the errors. I'm not quite sure what to do from there.

![firefox_2019-11-13_11-12-06](https://user-images.githubusercontent.com/2767681/68754185-81794400-0606-11ea-9965-d181cd946588.png)

**Comment by bruno-garcia** [comment]
Thanks @RDeluxe of giving a try.
Is it possible the exception data is being throw out by the linker? Maybe try to add it to `link.xml`.

**Comment by RDeluxe** [comment]
Thank you for your answer.

I'm not quite sure what you mean by "exception data" to add to my `link.xml`. I added everything linked to Sentry to be sure that is was not stripped

**Comment by bruno-garcia** [comment]
I meant the `Exception` class itself but if that's thrown (as in `throw new MyType()`) the linker should be dropping anything. We'd need to investigate this further.

**Comment by tfedor** [comment]
Hi, I'm wondering what's the state of this project. It seems like there was no major development, is the plan still to replace current master?

Could I maybe ask for at least a HOW TO to compile sentry-dotnet to try and play with it? After all, included libraries are a year old now.

Also, did you by any chance figure out the state of IL2CPP? Is it working or is it not?

**Comment by chrisse27** [comment]
We are using this library within an IL2CPP project.

**Comment by bruno-garcia** [comment]
@chrisse27 Thanks for confirming it works with IL2CPP. I haven't tried it yet myself.

@tfedor We haven't prioritized this yet. But having feedback here is a good way to see if there's demand.

>Could I maybe ask for at least a HOW TO to compile sentry-dotnet to try and play with it? After all, included libraries are a year old now.

The [.NET SDK repo](https://github.com/getsentry/sentry-dotnet) can be built with `dotnet build` but there are scripts for macOS/Linux and Windows.

A simpler solution is to download the latest package from nuget.org. You need to go after all the dependencies though and get those DLLs. Ideally a script would be built to do that but that doesnt' exist yet.

If anyone's willing to contribute with PRs, I'd be happy to work with you!

**Comment by RDeluxe** [comment]
I still did not find a solution for my issue though, I still have `<unknown>` errors with IL2CPP

**Comment by tom-willmowski** [comment]
> 
> 
> I still did not find a solution for my issue though, I still have `<unknown>` errors with IL2CPP.
> I can confirm however that except from that it seems to work quite nicely

I've added following lines to link.xml, and it seems to work now :)
`    <assembly fullname="Sentry" preserve="all"/>
    <assembly fullname="Sentry.Protocol" preserve="all"/>
    <assembly fullname="Sentry.PlatformAbstractions" preserve="all"/>`

**Comment by bruno-garcia** [comment]
For IL2CPP I also have this [gist saved which I tested 2 years ago to work with Newtonsoft.Json](https://gist.github.com/bruno-garcia/d550b3d57985d4ed2fd403865175caac).

**Comment by RDeluxe** [comment]
Hello there !

It seems things are going well, so when can we expect this to be merged ?

**Comment by bruno-garcia** [comment]
hey folks! Moved the code (based on the .NET SDK) to this repository, as a WIP SDK.
It is built on top of the experiment on that branch.

I've announced the changes here: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222
