### ISSUE TITLE
Display an onboarding Window after package installation

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#151]
After installing the package, users (that don't come from Sentry's in-product wizard) would need to follow instructions offline.

One way to improve the experience here is to open a window in the editor walking the user through setting things up. Including getting a DSN from Sentry and getting started.

- [ ] The window shall be displayed right after clicking: Install package
- [ ] There should be a way to open this window on demand (from `SentryWindow` perhaps): Covers the use case where users dismisses this window but would like to continue later
- [ ] A button for: Go away now! I know what I'm doing
- [ ] Either a clarification on how to get a DSN, or ideally: Login to Sentry, browse projects, get DSN. 
- [ ] Nice to have: Wizard to select features/configure: Performance monitoring sample rate.

**Comment by bitsandfoxes** [comment]
This has been superseded by the introduction of the wizard in https://github.com/getsentry/sentry-unity/pull/780
