### ISSUE TITLE
Expose hostnameVerifier in the Unity SDK settings

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-unity#1513]
The solution for errors like:

```
The application code defines a custom HostnameVerifier or ‘X509HostnameVerifier’ that may not sufficiently validate the hostnames. This could make the application vulnerable to network attacks.
```
[Example](https://github.com/getsentry/sentry-unity/issues/613)

Is to set [hostnameVerifier](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java#L1317-L1319) in the Android SDK. This requires disabling android native support and manually initialising the Android SDK with this option. Which is a troublesome process that is prone errors and misconfigurations.

Ideally this option can be set in the Unity SDK and passed down to the underlaying Android SDK.

**Comment by bitsandfoxes** [comment]
Currently, there is no straight forward way to access this from the Unity SDK as this is not getting read from the manifest.
