### ISSUE TITLE
Why can't I report on the SENTRY platform on the Crash log by iOS

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1519]
Why can't I report on the SENTRY platform on the Crash log by iOS

Unity：Unity2021.3.26f1
sentry：v1.7.1

just error report, not crash report
![Uploading image.png…]()

**Comment by WeiLingQiang** [comment]
![企业微信截图_17026324419770](https://github.com/getsentry/sentry-unity/assets/103353466/c9655eed-53c3-46e8-a1a6-0749d25f26a0)

**Comment by bitsandfoxes** [comment]
Hey @WeiLingQiang! You're using the samples and crashing the iOS application with a native sample but the crash does not show up on the dashboard? Do I get that right?

**Comment by WeiLingQiang** [comment]
Not sure if it is my environmental problem, such as xcode, unity settings, etc.
Can you provide me with a Unity Demo to test the iOS crash, based on the UNITY2021.3.26f1 version。
Thank you very much, I really need to solve this problem

**Comment by bitsandfoxes** [comment]
If you add the Sentry Unity package to an empty 2021.3.26f1 project you can import the samples from the packagemanager. These contain native iOS crash samples in the `Native Samples` scene.

**Comment by WeiLingQiang** [comment]
Yes, I did this, but my Sentry platform could not receive the Crash information

I do not know why it has to be like this

**Comment by WeiLingQiang** [comment]
Can you provide me with a complete unityDemo project that can run? Let me check this question

**Comment by bitsandfoxes** [comment]
What exactly does not work? Could you enable `Debug = true;` and share some logs with me? Either through the config window or in code.

**Comment by WeiLingQiang** [comment]
![企业微信截图_17029913629488](https://github.com/getsentry/sentry-unity/assets/103353466/6522a37e-380a-4bd5-8c89-43e88abf1134)
![企业微信截图_17029913321287](https://github.com/getsentry/sentry-unity/assets/103353466/58d7a3dd-4ccd-400f-a118-980524f82ae0)
![企业微信截图_1702991253264](https://github.com/getsentry/sentry-unity/assets/103353466/e2e34121-c7a3-43da-b3fe-4838ba6d41bd)

**Comment by WeiLingQiang** [comment]
![企业微信截图_17029913629488](https://github.com/getsentry/sentry-unity/assets/103353466/fd3525e8-54fb-4327-80af-fc2dffdafb92)
![企业微信截图_17029913321287](https://github.com/getsentry/sentry-unity/assets/103353466/0f82f5c8-c3fb-4eee-b60c-b63d21eb955c)
![企业微信截图_17029916081898](https://github.com/getsentry/sentry-unity/assets/103353466/a4aa8b42-c729-4716-80e3-99e8bc0dd4a1)

**Comment by WeiLingQiang** [comment]
Config window Just modified DSN, Neither Android and PC are fine, The Error/Exception of iOS can be captured, only the Crash of iOS cannot be captured

**Comment by WeiLingQiang** [comment]
![企业微信截图_17030378781153](https://github.com/getsentry/sentry-unity/assets/103353466/952b4e1f-dd8e-4e3a-993b-ae394b37bad3)

This is the Xcode simulator log. After clicking "Force Crash "-> Restart the game -> initialization Sentry

**Comment by bitsandfoxes** [comment]
Can you try launching the app in the simulator outside of Xcode? AFAIK Xcode will intercept the crash.

**Comment by WeiLingQiang** [comment]
![企业微信截图_17026324419770](https://github.com/getsentry/sentry-unity/assets/103353466/e0d1ced5-172c-4657-b46a-4e6c9ce52d23)

**Comment by WeiLingQiang** [comment]
![企业微信截图_17032268019310](https://github.com/getsentry/sentry-unity/assets/103353466/b7140a3b-40be-4e79-a5b6-04e7847cc0a5)
![Uploading 企业微信截图_17032267773866.png…]()
![Uploading 企业微信截图_17026324419770.png…]()
After the test results, I found that the DSN address captured by the Crash only reads the configuration in SentryOptions
If you use the SentryruntimeConfiguration to modify the DSN, the address of the Crash capture will not change, and error or abnormal capture will change.
Can you try it? See if the results are consistent, Only for iOS

**Comment by WeiLingQiang** [comment]
![企业微信截图_17026324419770](https://github.com/getsentry/sentry-unity/assets/103353466/6af5bda1-219c-4568-93e4-8eb2119b8230)
![企业微信截图_17032267773866](https://github.com/getsentry/sentry-unity/assets/103353466/f0a092bf-0587-4be2-b3de-da9634afe91e)
![企业微信截图_17032268019310](https://github.com/getsentry/sentry-unity/assets/103353466/8dbdf5d1-e52e-430f-9b70-ac6602b2c4fc)

After the test results, I found that the DSN address captured by the Crash only reads the configuration in SentryOptions
If you use the SentryruntimeConfiguration to modify the DSN, the address of the Crash capture will not change, and error or abnormal capture will change.
Can you try it? See if the results are consistent, Only for iOS

**Comment by bitsandfoxes** [comment]
If you want to modify the DSN programmatically you have to change it in both `SentryRuntimeConfiguration` and `SentryBuildTimeConfiguration`.
The native support on iOS relies on the options being set during build-time.

**Comment by WeiLingQiang** [comment]
Thank you very much, using `SentryBuildtimeConfiguration`  to solve this problem.
Can you help me see this problem again? [https://github.com/getsentry/sentry-unity/issues/1526](url) There is a problem with the Crash stack analysis #1526

**Comment by bitsandfoxes** [comment]
Anytime!
Let's continue in #1526
