### ISSUE TITLE
Android: Kotlin conflict with Firebase 11.6.0 

### ISSUE THREAD

**Issue by caseypugh** [getsentry/sentry-unity#1521]
Android builds fail due to multiple `kotlin-stdlib` versions being included at runtime. 

### Environment

**How do you use Sentry?**: `Sentry SaaS (sentry.io)`
**Which version of the SDK?**: `1.7.1`
**How did you install the package?** `Git-URL`
**Which version of Unity?** `2021.3.32f1`
**Platform**: `Android`

### Steps to Reproduce

1. Install and configure Sentry 1.7.1 and Firebase 11.6.0 (latest: https://firebase.google.com/download/unity). I have Firebase Analytics, RemoteConfig, and Messaging installed.
2. Build the app

### Expected Result

Expect the app to build successfully.

### Actual Result

Build fails with the following exception

```
Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class kotlin.ArrayIntrinsicsKt found in modules kotlin-stdlib-1.4.31.jar (org.jetbrains.kotlin:kotlin-stdlib:1.4.31) and org.jetbrains.kotlin.kotlin-stdlib-1.7.10.jar (org.jetbrains.kotlin.kotlin-stdlib-1.7.10.jar)
  ```

Firebase is using kotlin 1.7.10 but Sentry is trying to include 1.4.31 and creating a conflict... or maybe I'm doing something wrong. Is there a way for me to specify Sentry to use a different version?  Any advice here would be great.

**Comment by caseypugh** [comment]
I had spent a couple of days on this before posting issue, but all of a sudden ... it's all working?? I switched to another git branch that didnt include my Sentry changes, and then switched back and it magically resolved itself. I couldn't tell you why, but I guess I'll close this...

**Comment by bitsandfoxes** [comment]
It is suspicious to see this resolve itself. Please reach out if this shows up again!
