### ISSUE TITLE
There is a problem with the Crash stack analysis

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1526]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?
1.7.1

How did you install the package? (Git-URL, Assetstore)
Git-URL, UPM

Which version of Unity?
Unity2021.3.26f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
iOS

### Steps to Reproduce
``` UnityEngine.Diagnostics.Utils.ForceCrash(ForcedCrashCategory.FatalError);```

There is a problem with the Crash stack analysis，Unable to parse the Crash log stack
Symbol has been uploaded

### Any logs or screenshots

![企业微信截图_20231227110913](https://github.com/getsentry/sentry-unity/assets/103353466/e0947034-b4b3-4de5-8669-61a6834fa2bb)
![企业微信截图_20231227110928](https://github.com/getsentry/sentry-unity/assets/103353466/b9b0f46f-76f6-4262-9ce8-d89e42a027cc)

**Comment by bitsandfoxes** [comment]
Thanks for reaching out. I'm checking,

**Comment by bitsandfoxes** [comment]
I've been trying to reproduce this issue but it's limited to force crash. Are you running into similar issues when causing a crash on the native layer in a different way?

**Comment by WeiLingQiang** [comment]
I haven't tried different ways to Crash. Can you provide an example?

**Comment by WeiLingQiang** [comment]
I try to call ``Throw: Object C``、``ThrowCpp``  All are calling interfaces in demo
Why is it collected:
``WatchDogTermination``
``The olminedog terminated your app, posssiBly BeCAUSE it overused ram.``
![企业微信截图_17046816327661](https://github.com/getsentry/sentry-unity/assets/103353466/46f18a21-22e5-41df-b327-aa84b4724edb)

**Comment by bitsandfoxes** [comment]
The demo includes samples and snippets to C/C++ crashes. You can find them in `2_NativeSupport` scene.
- CPlugin
- CppPlugin
- ObjectiveCPlugin
I expect them to work.

The watchdog termination is something specific to the Apple platforms and based on heuristics. We have some documentation [here](https://docs.sentry.io/platforms/apple/guides/ios/configuration/watchdog-terminations) going into more details

**Comment by WeiLingQiang** [comment]
For WatchDog Terminings, I don’t quite understand,
Can I close it so that it can show the Crash Stack normally?

**Comment by bitsandfoxes** [comment]
The watchdog termination is a different kind of issue. The operating system terminated the app and the SDK makes an educated guess as to why that happened.

**Comment by WeiLingQiang** [comment]
Excuse me, Whether iOS supports EnableBitCode = NO ?
![企业微信截图_17071858896973](https://github.com/getsentry/sentry-unity/assets/103353466/eb5472e9-39ea-46af-83eb-b9c9ee0df010)

**Comment by bitsandfoxes** [comment]
Bitcode has been deprecated by Apple and can be ignored.

**Comment by WeiLingQiang** [comment]
Why parside the Crash of iOS is a symbol table generated by BitCode?

![企业微信截图_170726016328](https://github.com/getsentry/sentry-unity/assets/103353466/cdd9531a-7b87-44cc-b7b7-afacc783d3ef)
![企业微信截图_17072603686866](https://github.com/getsentry/sentry-unity/assets/103353466/73ac241c-2ef8-4219-b3c0-4d9db28ca6af)

**Comment by WeiLingQiang** [comment]
If I set up bitcode = no, I can't find the symbol table analysis

**Comment by bitsandfoxes** [comment]
I'm not sure what it is that is not working for you. The way it is set up right now sentry cli will only upload debug symbols if `bitcode = no`.

**Comment by WeiLingQiang** [comment]
I use the sentry-cli command line to upload manually, is it correct?

![企业微信截图_17083088921455](https://github.com/getsentry/sentry-unity/assets/103353466/43567444-80fa-4b68-b822-a4e526a451d4)

**Comment by WeiLingQiang** [comment]
Test results: Just upload the symbol table as shown in the figure (generated by BitCode)
The three symbols generated by non-BitCode are useless

![企业微信截图_17083374141176](https://github.com/getsentry/sentry-unity/assets/103353466/15766dc3-2c4e-4255-9e4f-cc09d9654ebd)

**Comment by bitsandfoxes** [comment]
It looks like it is working out for you?

**Comment by WeiLingQiang** [comment]
Yes，`bitcode = yes`  effective for me，and the `bitcode = no` cannot analyze the Crash log

**Comment by WeiLingQiang** [comment]
My problem has not been solved yet，I need to set up `bitcode = no`, but this has caused it to be unable to analyze the Crash stacktable

**Comment by WeiLingQiang** [comment]
The screenshot shows that there are uploading symbols, but there is no normal analysis Crash stack

![企业微信截图_17085036749134](https://github.com/getsentry/sentry-unity/assets/103353466/343f5895-80db-4951-b91d-8d5d601f82a5)

![企业微信截图_17085036936960](https://github.com/getsentry/sentry-unity/assets/103353466/1597c9d4-646f-4b95-aeb5-33e4e7b5fa23)

**Comment by bitsandfoxes** [comment]
I have to correct myself. The SDK dropped checking for `bitcode` in version `1.5.0`. The SDK adds a script to the build phase that will automatically upload the relevant symbols for you.
Could you provide me with a small repro so I can test what's going on locally?
