### ISSUE TITLE
Samples broken on 0.0.13

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#157]
![image](https://user-images.githubusercontent.com/2175097/117856887-d5fd8e00-b294-11eb-972e-bbf46388d6bb.png)

By clicking on `Import into Project`, the following error displays

```
DirectoryNotFoundException: Could not find a part of the path 'C:\Projects\Unity\pf_01\Library\PackageCache\io.sentry.unity@29f404fabd\Samples~\unity-of-bugs'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath)
```

**Comment by bruno-garcia** [comment]
We've identified this to be an issue with craft's release process. The sample is inside the unity package but it wasn't pushed to the upm repo

**Comment by bitsandfoxes** [comment]
The issue was a wrongly configured global .gitignore for '~'. (it affected both Documentation~/ and Sampes~/)
