### ISSUE TITLE
DefaultTags in SentryBuildTimeOptionsConfiguration don't show up

### ISSUE THREAD

**Issue by polynatic** [getsentry/sentry-unity#1573]
### Environment

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
2.0.0

How did you install the package? (Git-URL, Assetstore)
UPM Git-URL

Which version of Unity?
2022.3.20

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
iOS player, no other platform tested

### Steps to Reproduce

1.
```C#
public class SentryBuildTimeConfiguration : SentryBuildTimeOptionsConfiguration
{
    public override void Configure(SentryUnityOptions options, SentryCliOptions cliOptions)
    {
        options.DefaultTags.Add("branch", GetGitBranch());
    }
}
```
2. Create Build
3. Run on Device

### Expected Result

The branch tag appears on all Sentry events coming from this build.

### Actual Result

The tag is not present on any Sentry events.

**Comment by bitsandfoxes** [comment]
Sorry for the confusion.
The build-time options are purely used during build-time. They give you a place to hook into the CLI options and to modify mobile (iOS & Android) specific options that cannot be modified during runtime. I.e. environment or release.
Tags will get propagated to all layers when set during runtime so adding those to the runtime options should do the trick.

**Comment by polynatic** [comment]
Alright, thanks! It would be nice if the documentation would be more clear on what properties can be set during build time, which can't be set and which ones must be set there.

**Comment by bitsandfoxes** [comment]
Very true. We'll update those asap.

**Comment by bruno-garcia** [comment]
@bitsandfoxes did we update the docs? Can we close this?

**Comment by bitsandfoxes** [comment]
Superseded by https://github.com/getsentry/sentry-unity/issues/1621
