### ISSUE TITLE
Metrics onboarding in-product doesn't show code snippet for Unity

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#1588]
Notice it's grayed out:

![image](https://github.com/getsentry/sentry-unity/assets/1633368/6be0aa6b-ddbf-4ba2-9327-3d7d8480a179)

Shows for .NET though

![image](https://github.com/getsentry/sentry-unity/assets/1633368/35503db7-fe89-4fdb-a5da-60542d7b544d)

**Comment by bitsandfoxes** [comment]
Fixed by https://github.com/getsentry/sentry-docs/pull/9421
