### ISSUE TITLE
SIGSEGV errors on old Android devices when Sentry is enabled.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-unity#1591]
### Environment

How do you use Sentry?
Sentry SaaS 

Which version of the SDK?
>=1.7.0

Which version of Unity?
2022.3.13f1

### Steps to Reproduce
Reproduction app is available in the internal issue. 

### Expected Result
The application runs with no errors on all devices. 

### Actual Result
Android 5 and older devices experience a SIGSEGV error. Link to event also in the internal ticket.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2127) by [Unito](https://www.unito.io)

**Comment by rodolfoBee** [comment]
@bitsandfoxes @kahest the affected user is asking for an update, is there any?

**Comment by kahest** [comment]
@rodolfoBee I don't have any updates, I'm not working on this currently

**Comment by bitsandfoxes** [comment]
I think we're a bit lost here without a proper way to reproduce this.
It is possible that the changes that have been made to get rid of our custom sigaltstacks in `sentry-native` could cause an increase in reported `SIGSEGV`. But for that to happen there needs to be a signal first. So basically: Sentry is crashing while capturing a crash.

**Comment by Talibt** [comment]
Hey @bitsandfoxes 
Thank you!
Yeah sure, that would be easy to do.

**Comment by bitsandfoxes** [comment]
Hi @Talibt,
I've created an "experimental" package with the rollback on the sentry-native [here](https://drive.google.com/file/d/1SXDZ6I2g_nO6Q8FtlPV2LMyHA6hbbk-4/view?usp=sharing).
This is strictly intended to work on and for those old Android devices. If you could give that a try and see if it has any effect on the crashes you're seeing, that'd be hugely appreciated.

**Comment by Talibt** [comment]
Hey @bitsandfoxes, 
sorry to inform you that the hand-made package didn't work as expected. The lower-end devices are still crashing. 
However, we also tested your Unity Lite EPK, available here: https://github.com/getsentry/sentry-unity-lite, 
and it worked smoothly. 
What do you think is needed to move forward with fixing this issue?

**Comment by bitsandfoxes** [comment]
One thing you could do immediately to unblock yourself from those issues on low-end devices is to disable android-native support. That way you get all of the offerings the Unity SDK has without having to rely on the Lite package.
Could you provide us with a build that keeps crashing?

**Comment by Talibt** [comment]
Yeah I'm pretty sure that we won't like to skip over the native support,
which pretty sucks.
However you can find the build that keeps crashing using the "experimental" package that you supplied,
[here](https://drive.google.com/file/d/19jAgC3GgQ4L4AjjFliwTdlRnv487NvRm/view?usp=drive_link).

**Comment by bitsandfoxes** [comment]
Thanks! We'll take a look!

**Comment by WeiLingQiang** [comment]
Is there a solution? I also encountered the same problem, my version is 2.0.1

**Comment by bitsandfoxes** [comment]
Hey, I really need some help here.
Did this break with an upgrade to `>1.7.0`? 

> However you can find the build that keeps crashing using the "experimental" package that you supplied,

Are there any events getting sent to Sentry from the build? Could you confirm the reporting SDKs version number (that can be found all the way at the bottom of the issue page)

Are there any logs at all you can provide us?

**Comment by bitsandfoxes** [comment]
Could you help me out here? Could you give that a try with an "empty" Unity project with Sentry added? As a minimal repro? Does that crash as well?

**Comment by WeiLingQiang** [comment]
> Could you help me out here? Could you give that a try with an "empty" Unity project with Sentry added? As a minimal repro? Does that crash as well?

Yes, I did this, and will crash

**Comment by bitsandfoxes** [comment]
Thanks for confirming. We've got a lead.
