### ISSUE TITLE
C++ exception & std::terminate() support in iOS

### ISSUE THREAD

**Issue by etnlGD** [getsentry/sentry-unity#1628]
1. Now when a C++ exception is thrown in iOS, sentry cannot collect the call stack of the exception thread, but can only collect the stacks of other unrelated threads. This issue has been mentioned in following issues: 
- https://github.com/getsentry/sentry-cocoa/issues/551
- https://github.com/getsentry/sentry-unity/issues/1273

I tried [the solution proposed by eakoli](https://github.com/getsentry/sentry-cocoa/issues/551#issuecomment-684089619) but still didn't solve the problem. However, I'm inspired from his solution. We can export a `__sentry_cxa_throw` function in sentry.framework:
![img_v3_02a3_5173ea99-aa0f-41ec-b698-38f8ce4e32fg](https://github.com/getsentry/sentry-unity/assets/3226182/6c0d663a-af31-451e-8026-2e5e811cd39b)

And then add the following code through unity’s c++ plugin mechanism to ensure that all c++ exceptions thrown in UnityFramework can be collected by sentry:
```
// This file should be added into UnityFramework target in xcode
#include <dlfcn.h>


typedef void (*cxa_throw_type)(void *, std::type_info *, void (*)(void *));

extern "C" 
{
    void __cxa_throw(void *thrown_exception, std::type_info *tinfo, void (*dest)(void *)) __attribute__((weak));

    void __cxa_throw(void *thrown_exception, std::type_info *tinfo, void (*dest)(void *))
    {
        static cxa_throw_type orig_cxa_throw = NULL;
        if (orig_cxa_throw == NULL)
        {
            orig_cxa_throw = (cxa_throw_type)dlsym(RTLD_DEFAULT, "__sentry_cxa_throw");

            if (orig_cxa_throw == NULL)
                orig_cxa_throw = (cxa_throw_type)dlsym(RTLD_NEXT, "__cxa_throw");
        }
        orig_cxa_throw(thrown_exception, tinfo, dest);
        __builtin_unreachable();
    }
}
```

2. In addition, calling `std::terminate()` directly in C++ cannot be correctly captured by sentry. I investigate the sentry-cocoa logs, found that sentry tried to re-throw the current exception while processing terminate(`CPPExceptionTerminate`), but the re-throwed exception was not captured correctly. Because there is currently no exception. Here's a solution I've tested that works:
![img_v3_02a3_641d4482-b9b9-46c3-8878-6925559e38cg](https://github.com/getsentry/sentry-unity/assets/3226182/79b74026-6e89-4701-83a5-42ac6657916d)

**Comment by bitsandfoxes** [comment]
Hey @etnlGD, this is awesome! Thanks for all the investigative work! We'll make sure to put it to good use!

**Comment by WeiLingQiang** [comment]
请问下，`UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)` 这个抛出的崩溃 你的Sentry能捕获到吗？

**Comment by etnlGD** [comment]
> 请问下，`UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)` 这个抛出的崩溃 你的Sentry能捕获到吗？

这个没问题

**Comment by WeiLingQiang** [comment]
我用Demo跑也没问题，但是接入到我的项目中 就捕获不到了。
另外也崩溃堆栈也解析不了，符号表有上传 并且我自己用命令解析是没问题的（如图）
这个抛出的`UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.FatalError`
![image](https://github.com/getsentry/sentry-unity/assets/103353466/454c41b3-4f89-4a9d-8f06-15b8f6254269)

**Comment by WeiLingQiang** [comment]
我调用这个API `UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)` 
Sentry捕获到的是这样的：`WatchdogTermination`，您知道是什么问题吗？
![image](https://github.com/getsentry/sentry-unity/assets/103353466/ae6d82a9-ec57-4aa2-9260-70e1c00bc16e)

这个是链接：https://sausage-client-sentry.sausage.xd.com/share/issue/af563b7a7cd24481918f1b8abde45317/

> > 请问下，`UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)` 这个抛出的崩溃 你的Sentry能捕获到吗？
> 
> 这个没问题

**Comment by etnlGD** [comment]
> 我调用这个API `UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)` 
> 
> Sentry捕获到的是这样的：`WatchdogTermination`，您知道是什么问题吗？
> 
> ![image](https://github.com/getsentry/sentry-unity/assets/103353466/ae6d82a9-ec57-4aa2-9260-70e1c00bc16e)
> 
> 
> 
> 这个是链接：https://sausage-client-sentry.sausage.xd.com/share/issue/af563b7a7cd24481918f1b8abde45317/
> 
> 

我估计是其他库注册了signal handler导致的，你可以调用signal查询下当前注册的函数

**Comment by WeiLingQiang** [comment]
> > 我调用这个API `UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation)`
> > Sentry捕获到的是这样的：`WatchdogTermination`，您知道是什么问题吗？
> > ![image](https://private-user-images.githubusercontent.com/103353466/325945487-ae6d82a9-ec57-4aa2-9260-70e1c00bc16e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjM0NTAsIm5iZiI6MTcxNDQ2MzE1MCwicGF0aCI6Ii8xMDMzNTM0NjYvMzI1OTQ1NDg3LWFlNmQ4MmE5LWVjNTctNGFhMi05MjYwLTcwZTFjMDBiYzE2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwNzQ1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTc1YjM0MWQwZGUzZjAwZjcxOGJkM2MwOGRkNDM3MjRhMmYyMjdjZDVjN2Q2MmU5NmQ3MjBlOTVjNTAxN2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.USz30Tu1iPaDblwFLpHeq3oEbAnHTlclPf66r-vFUZc)
> > 这个是链接：https://sausage-client-sentry.sausage.xd.com/share/issue/af563b7a7cd24481918f1b8abde45317/
> 
> 我估计是其他库注册了signal handler导致的，你可以调用signal查询下当前注册的函数

非常感谢，这个问题解决了。
是其他库注册了signal handler导致的

**Comment by WeiLingQiang** [comment]
我还遇到另一个问题：ios的崩溃无法解析（安卓没问题，ios符号表也上传了）
https://sausage-client-sentry.sausage.xd.com/share/issue/b3a194bb577e42b2a4526a508d5cf576/
![image](https://github.com/getsentry/sentry-unity/assets/103353466/b9e6cba9-ca2f-4273-9b9f-beafcde0eb2b)
![image](https://github.com/getsentry/sentry-unity/assets/103353466/2695b0d9-7629-4c01-916d-384e5984f3db)

**Comment by munkiki7** [comment]
Hey, @etnlGD .

We are currently trying to implement the proposed changes, but this new __cxa_throw hook is not actually called.

Can you, please, tell us where exactly you have added the hook code to make it work?

**Comment by etnlGD** [comment]
The new files can be found here: [SentryIntegration.zip](https://github.com/getsentry/sentry-unity/files/15328756/SentryIntegration.zip).
And I put the new files in this directory: Assets/Plugins/iOS/SentryIntegration/.

You can edit some il2cpp generated file to throw a C++ exception from a monobehaviour's Start function, and then set a breakpoint at the new __cxa_throw function.

**Comment by munkiki7** [comment]
@etnlGD , this is the same approach that you have described earlier.
I thought I was missing something, but this is actually what I have been doing, too.

We have a demo function that throws a cpp exception on button click, but the breakpoint in the hook function is never reached.


![Image](https://github.com/getsentry/sentry-unity/assets/41358286/cba4a667-3640-486e-b6f2-89517916949d)

I am using Unity 2021.3.33f.



![Image](https://github.com/getsentry/sentry-unity/assets/41358286/95b2155b-8c5c-453c-8cd8-5e26056a418a)

**Comment by etnlGD** [comment]
@munkiki7 Is the `throw_cpp` function inside the UnityFramework module? This hook can only catch c++ exceptions thrown from UnityFramework.

**Comment by munkiki7** [comment]
@etnlGD , no, it is not. It's located in a similar cpp file like a plugin.

Shouldn't this fix apply to all c++ exceptions?

**Comment by etnlGD** [comment]
@munkiki7 No, it won't apply to all. If you want to capture exceptions from other modules, you have to add custom `__cxa_throw` to these modules.

**Comment by munkiki7** [comment]
@etnlGD, so this solution will only capture the Unity's c++ exceptions, and will not work with any third-party plugins' exceptions or the user's extensions? It will only work for the Unity's own c++ exceptions?

**Comment by etnlGD** [comment]
@munkiki7  There might be something wrong. By default, Unity’s cpp plugin and static native libraries should be linked into the UnityFramework module. Can you provide the xcode project?

**Comment by munkiki7** [comment]
@etnlGD You can download it here: https://drive.google.com/file/d/1eaEwddEEM6APWvIp5GEHMLROGnppj2C1/view?usp=sharing

**Comment by etnlGD** [comment]
@munkiki7 This is because your demo calls `__cxa_rethrow` instead of `__cxa_throw`, so we need an additional hook `__cxa_rethrow` to handle this situation. If you call `throw std::runtime_error("test")` directly in `throw_cpp`, it will work.
![img_v3_02au_faf3eafc-7ac5-4d8c-b308-ecd4db43b73g](https://github.com/getsentry/sentry-unity/assets/3226182/4ad14a02-beb4-4824-8444-b37a5ea68a87)
![img_v3_02au_0e3ea4ef-741e-4bf5-87a1-9b4082934cdg](https://github.com/getsentry/sentry-unity/assets/3226182/524eef84-fb56-435f-af8c-8b83f16c3ca8)

**Comment by munkiki7** [comment]
Yes, with your method body it worked, @etnlGD .

However, it still does not work with this:


![Image](https://github.com/getsentry/sentry-unity/assets/41358286/9d3f0f86-f965-4af5-9657-30c00958047d)

**Comment by etnlGD** [comment]
> Yes, with your method body it worked, @etnlGD .
> 
> However, it still does not work with this:
> 
> ![Image](https://private-user-images.githubusercontent.com/41358286/331220382-9d3f0f86-f965-4af5-9657-30c00958047d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Njc0OTAsIm5iZiI6MTcxNTg2NzE5MCwicGF0aCI6Ii80MTM1ODI4Ni8zMzEyMjAzODItOWQzZjBmODYtZjk2NS00YWY1LTk2NTctMzBjMDA5NTgwNDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEzNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjFkMTJjYWM3OTZiYWI1Mjk2OWNiNWM0MzkwZDM1ZjY3NjQwZGI1MmU3N2QzNmIwOGRlZGU5NDRhYmIxZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PkjXQjZ_QkSdbTHceM1L-MfE9AhoePnxr0O3MxnI2aE)

I guess this is because the substr function is implemented in libc++abi.dylib. As mentioned before, only exceptions thrown in UnityFramework can be caught.

**Comment by munkiki7** [comment]
Oh, I see.

Thank you for your help.
I will now try to implement the _cxa_rethrow call in a similar manner.
