### ISSUE TITLE
Automatic Performance Instrumentation for `UnityWebRequest`

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1630]
It'd be really neat to have automatic performance instrumentation for Unity's [WebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html).

**Comment by bitsandfoxes** [comment]
Ideas how to get there:
1. Building a `SentryUnityWebRequest` that act like a wrapper. Doing the instrumentation for us.
2. IL Weave instances of `UnityWebRequest`

**Comment by bruno-garcia** [comment]
Came across this commit: https://github.com/getsentry/sentry-unity/commit/be0388e9c24a95e2e8987d3ddc7b2e594cd5baaa

from [this branch](https://github.com/getsentry/sentry-unity/tree/UnityWebRequest)

**Comment by bruno-garcia** [comment]
Is this a dupe of?:
* https://github.com/getsentry/sentry-unity/issues/737

**Comment by bitsandfoxes** [comment]
> Is this a dupe of #737 

Yes
