### ISSUE TITLE
Validate stacktrace and line numbers on `2023`

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1640]
With the opt-in of line numbers now provided in the build settings we need to validate whether we can use that OOTB and can skip out of our reverse engineered IL2CPP processor.

- [x] Does the stacktrace still look oke?
- [x] Do line numbers still work?
- [x] Does it work with the flag enabled?
- [x] Does it work with Sentry IL2CPP support disabled but Unity line numbers enabled?

**Comment by munkiki7** [comment]
![Image](https://github.com/getsentry/sentry-unity/assets/41358286/ad8b6329-2dd4-4192-aefc-7db178b9ee24)


Capture message IL2CPP release build with Unity line numbers enabled.

**Comment by munkiki7** [comment]
![Image](https://github.com/getsentry/sentry-unity/assets/41358286/aea5b1a0-e92b-4ea9-80f1-b314bfca32b4)

Capture message IL2CPP release build with Unity line numbers disabled.

**Comment by munkiki7** [comment]
![Image](https://github.com/getsentry/sentry-unity/assets/41358286/047a9801-0087-4934-bc79-19a695026eba)

Exception stacktrace is unchanged if Unity line numbers are disabled.

**Comment by munkiki7** [comment]
![Image](https://github.com/getsentry/sentry-unity/assets/41358286/b65c35ef-d528-48e8-8251-3abf84af927b)

Exception with Unity line numbers enabled and IL2CPP line numbers in Sentry disabled.

**Comment by munkiki7** [comment]
![Image](https://github.com/getsentry/sentry-unity/assets/41358286/1b53b3ad-7d4c-461a-adeb-15f304b34947)

Capture message with Unity line numbers enabled and IL2CPP line numbers in Sentry disabled.

**Comment by bitsandfoxes** [comment]
Looks like it works! Just a bit better with the option enabled. 🎉
