### ISSUE TITLE
Some APIs were marked as Pivate API by App Store

### ISSUE THREAD

**Issue by KinSyourin24** [getsentry/sentry-unity#1646]
SDK Version: Sentry unity 2.0.2

Platform :macOS

It seems like those of API are marked as private API :

__NSCFConstantString
__NSDate
__NSCFNumber
__NSArrayI
__NSArrayM
__NSCFArray
NSCFArray
__NSCFString

**Comment by bitsandfoxes** [comment]
Hey @KinSyourin24, could you provide more context here?

**Comment by bitsandfoxes** [comment]
Closing this as I don't see any actionable thing to do here.
