### ISSUE TITLE
Don't report `ServerName`

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#165]
Proposed solution: filter ServerName on EvenProcessor
i.e. evt.ServerName = null

**Comment by semuserable** [comment]
I'm not sure I understood the problem.

**Comment by bruno-garcia** [comment]
Updated the title/description

**Comment by semuserable** [comment]
`SentryEvent.ServerName` is not reported from Unity (ie `@event.ServerName` is `null`). Checked on latest `main` (Editor and `il2cpp` builds). Is there some other places where it's reported? I'm checking the `TAGS` section on web UI.
