### ISSUE TITLE
Performance problems, Memory growth 30-40MB

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1651]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?
v2.0.4

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.33f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Just install and setup the sentry.
2. Compared with the memory growth before and after access, after it was found that the memory increased by 30-40MB after the `Init SentrySDK`

### Expected Result

Memory growth is only within 10MB

### Actual Result

I try with an "empty" Unity project with Sentry added, After discovering the initial SENTRYSDK, the memory increased by 30-40MB

**Comment by bitsandfoxes** [comment]
Hey! What do you mean with "memory"? Appsize? Or memory used during runtime?

**Comment by WeiLingQiang** [comment]
> Hey! What do you mean with "memory"? Appsize? Or memory used during runtime?

memory used during runtime, 
`TotalPss`
Use adb command:  `adb shell dumpsys meminfo <package_name>`

**Comment by bitsandfoxes** [comment]
Admittedly, 30-40 MB sounds like a lot but there's a whole bunch of things the SDK does. I'd be much more wary about the SDK's behavior over the game's lifecycle. 
Looking at an empty project's memory profile I'm not sure I see the problem yet.
![Screenshot 2024-05-15 at 15 42 48](https://github.com/getsentry/sentry-unity/assets/25725783/25b1719f-d7b2-4c89-b7e5-840bd6268c5f)
What makes you think there is one?

**Comment by WeiLingQiang** [comment]
You should check the memory in the Android APK package instead of unity. 
You can try to use the ADB command to compare the empty project and SentryDemo project
`adb shell dumpsys meminfo <package_name>`

**Comment by WeiLingQiang** [comment]
![企业微信截图_17158253682831](https://github.com/getsentry/sentry-unity/assets/103353466/f7536b9d-d030-4bb5-a3c4-95461c1c1b49)
![企业微信截图_17158252665697](https://github.com/getsentry/sentry-unity/assets/103353466/cc879318-9554-4c62-b43f-9885d46bc5fa)

The above is a screenshot of the ADB command `adb shell dumpsys meminfo <package_name>`

**Comment by bitsandfoxes** [comment]
I don't doubt that you are right about the increase. I just tried to illustrate what that memory layout looks like. I'm not convinced that the SDK's memory footprint is an actual issue.

**Comment by WeiLingQiang** [comment]
Excuse me, is there a way to reduce memory occupation

**Comment by bitsandfoxes** [comment]
Can you share your configuration of the SDK?

**Comment by WeiLingQiang** [comment]
[SentryOptions.txt](https://github.com/getsentry/sentry-unity/files/15387844/SentryOptions.txt)

You turn the file to the .asset suffix

**Comment by bruno-garcia** [comment]
@WeiLingQiang Did you have a chance to try without the native Android support?

We also made a lot of changes since then, have you had a chance to peek at the memory usage again?

**Comment by bitsandfoxes** [comment]
Closing this as stale. We've made quite the effort to improve memory consumption, especially on the .NET SDK side of things. Please feel free to reopen this issue if it persists for you.
