### ISSUE TITLE
About Apple privacy manifest files

### ISSUE THREAD

**Issue by Hamjoon** [getsentry/sentry-unity#1656]
Starting May 1, 2024, apps that don’t describe their use of required reason API in their privacy manifest file aren’t accepted by App Store Connect. Is the latest version of sentry-unity prepared for this issue, and if not, do you have a plan to prepare for it?

**Comment by bitsandfoxes** [comment]
Hey @Hamjoon, thanks for reaching out!
The latest version of the Unity SDK `2.0.5` uses the Cocoa SDK `8.25.2` and complies with the privacy manifest.

**Comment by Hamjoon** [comment]
My project does not use the native support feature, so the iOS framework folder is not extracted. If so, do I need to manually add the items included in version 2.0.5 to the privacy manifest of my xcode project?
