### ISSUE TITLE
Flag `Simulator` based on `Application.editor`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#166]
https://github.com/getsentry/sentry-unity/blob/a6fc21f32350efb7d821dacbfe23a74da52fef2d/src/Sentry.Unity/UnityEventProcessor.cs#L119-L124

Needs to be changed to `IApplication` which should abstract the static Application class (for testability)

**Comment by bitsandfoxes** [comment]
closed by https://github.com/getsentry/sentry-unity/pull/184
