### ISSUE TITLE
CI stuck in edit mode tests

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1663]
The Unity editor returns with `Unity finished successfully. Time taken: 00:00:08.697` but the step itself is stuck until timeout.
Sample: https://github.com/getsentry/sentry-unity/actions/runs/9217983681/job/25367272391

**Comment by bruno-garcia** [comment]
Is this still relevant?

**Comment by bitsandfoxes** [comment]
Could not observe any more stucks.
