### ISSUE TITLE
Whether to support timely reporting of Native crashes?

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1667]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?
v2.0.6

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.33f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
ALL

### Steps to Reproduce

1. Trigger Native crash reporting to Sentry platform
2. After Native crashes, it cannot be reported in time. It will not be reported until the second time the application is opened.

### Expected Result

Report Native immediately after it crashes instead of waiting until the second time you open the app.

**Comment by bitsandfoxes** [comment]
The native crash reporting relies on the respective native SDK. This means `sentry-cocoa` for macOS and iOS, `sentry-jave` for Android, and `sentry-native` for Windows and Linux. Those SDKs handle crash reporting slightly differently.
- On iOS and macOS: `sentry-cocoa` tries to send the crashreport but might fail to do so. It will guarantee to report the crash during the startup tho.
- On Android: the crash gets persisted to disk and picked up during restart.
- On Windows: We add a crashpad handler to your game and crashes will get sent immediately
- On Linux:  As there is no standalone crashhandler we rely on breakpad to send the report during the next startup
