### ISSUE TITLE
Events not captured from Unity WebGL build after scene change

### ISSUE THREAD

**Issue by MobikTech** [getsentry/sentry-unity#1678]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
2.0.6

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.32f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
It is happening on WebGL build(dont know if on another platforms also, did not tested). In Editor bug is NOT reproduced

### Steps to Reproduce

1. Integrate Sentry SDK events/messages/errors/unhandledExceptions capturing on first and second scenes via SentrySdk.Capture[] methods. 
2. Capturing executed from UniTask loop in custom non MonoBehaviour classes.
2. Make game build on WebGL platform(dev/usual, doesn't matter)
3. Run build on any browser(tested on Chrome and Firefox, both reproduced bug).

### Expected Result
All calls of SentrySdk.Capture[] methods and unhandled exceptions will be gathered and displayed on sentry.io.

### Actual Result
While first scene is loaded and active all events sending to cloud correctly. But after a moment of second scene loaded all events stops to send. After this, each sending try throws NullReference exception to browser console from internal SentrySDK code(see the screenshots).
![image](https://github.com/getsentry/sentry-unity/assets/62842262/3db5fe13-a927-402c-9eae-cd1bd5b3a192)

Exceptions thrown from internal DoSendEvent method and catched by try/catch block.
![image](https://github.com/getsentry/sentry-unity/assets/62842262/f57531a0-7780-4986-976a-b8ce3b3e2298)

### Any logs or screenshots
SentryConfiguration on which build was tested:
![image](https://github.com/getsentry/sentry-unity/assets/62842262/54d88630-8e3a-4ce0-a339-2b8624327e74)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/8f6986b9-fe5c-4f6e-aa30-8f230952c365)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/567ffaf1-c045-4fd5-819c-96d8dce04efa)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/25cc866d-5a19-4691-8413-650785bf6020)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/cf7eab93-dc72-440c-97e1-9fb085794293)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/487027fd-8e48-4f35-a0d9-462829f7692d)
![image](https://github.com/getsentry/sentry-unity/assets/62842262/ec487663-98cc-4a8e-8970-436e992edc6d)

Detailed log of Error message:
![image](https://github.com/getsentry/sentry-unity/assets/62842262/d3ef6118-0c16-49d4-9979-47ba2d72009a)

**Comment by bitsandfoxes** [comment]
Thanks for reaching out and for the detailed issue! We'll have to process this but it should be fairly straight forward to reproduce!

**Comment by munkiki7** [comment]
@MobikTech , we have tested the scene-changing part within our demo level, and everything works fine even after several scene changes.

Can you, please, send us a minimal example to reproduce the issue?

**Comment by MobikTech** [comment]
@munkiki7 I prepared sample project with error reproduce, you can download it by the link: https://drive.google.com/file/d/1D-wTsWaUVdOY5R2GwMZS90WVQQzjNOfA/view?usp=sharing

**Comment by bitsandfoxes** [comment]
Thanks for the repro @MobikTech, much appreciated. We'll be taking a look!
