### ISSUE TITLE
Jenkins Unity build failes because of: Sentry: (Error) sentry-cli: error: API request failed

### ISSUE THREAD

**Issue by bkostrowiecki** [getsentry/sentry-unity#1684]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
2.0.6

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2022.3.5f1 LTS

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
In Unity Editor after the build process on Windows

### Steps to Reproduce

1. Create a script to build a game using command lines Unity tools
2. Configured Jenkins to run a script using the command lines Unity, and run it in batch-mode.
3. Run build
4. The build failed because of an error from Sentry.

### Expected Result

The post-build script from Sentry should have worked.
Alternatively, I would expect more information from the Sentry post process to detect the issue somehow.

### Actual Result

The logs show me that sentry-cli tried to send an API request, but I have no information on what failed here.
```
16:34:38 *** Tundra build success (85.45 seconds - 0:01:25), 69 items updated, 2049 evaluated
16:34:38 ExitCode: 0 Duration: 1m:25s
16:34:39 Total cache size 80003228
16:34:39 Total cache size after purge 80003228
**16:34:39 Sentry: (Error) sentry-cli: error: API request failed** 
16:34:39 UnityEngine.StackTraceUtility:ExtractStackTrace ()
16:34:39 UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
16:34:39 UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
16:34:39 Sentry.Unity.UnityLogger:Log (Sentry.SentryLevel,string,System.Exception,object[]) (at /sentry-unity/src/Sentry.Unity/UnityLogger.cs:33)
16:34:39 Sentry.Unity.Editor.Native.BuildPostProcess/<>c__DisplayClass3_0:<UploadDebugSymbols>b__2 (object,System.Diagnostics.DataReceivedEventArgs) (at /sentry-unity/src/Sentry.Unity.Editor/Native/BuildPostProcess.cs:257)
16:34:39 System.Diagnostics.Process:ErrorReadNotifyUser (string)
16:34:39 System.Diagnostics.AsyncStreamReader:FlushMessageQueue ()
16:34:39 System.Diagnostics.AsyncStreamReader:GetLinesFromStringBuilder ()
16:34:39 System.Diagnostics.AsyncStreamReader:ReadBuffer (System.IAsyncResult)
16:34:39 System.IO.Stream/ReadWriteTask:InvokeAsyncCallback (object)
16:34:39 System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
16:34:39 System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
16:34:39 System.IO.Stream/ReadWriteTask:System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task)
16:34:39 System.Threading.Tasks.Task:FinishContinuations ()
16:34:39 System.Threading.Tasks.Task:FinishStageThree ()
16:34:39 System.Threading.Tasks.Task:FinishStageTwo ()
16:34:39 System.Threading.Tasks.Task:Finish (bool)
16:34:39 System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
16:34:39 System.Threading.Tasks.Task:ExecuteEntry (bool)
16:34:39 System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
16:34:39 System.Threading.ThreadPoolWorkQueue:Dispatch ()
16:34:39 System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
16:34:39 
16:34:39 (Filename: /sentry-unity/src/Sentry.Unity.Editor/Native/BuildPostProcess.cs Line: 257)
16:34:39 
16:34:40 DisplayProgressNotification: Build Failed
```

**Comment by bitsandfoxes** [comment]
Hey there! Sorry to see you run into issues. But there's good news (sort of). With `2.0.7` the SDK now properly logs sentry-cli errors to the console and builds don't fail due to uploading errors.
A thing to be aware tho, you do need those debug symbols uploaded if you want your issues to be properly symbolicated.
Could you give version `2.0.7` a try?

**Comment by bitsandfoxes** [comment]
@munkiki7, thinking about it now: Maybe we should put a flag around this on the CLI options whether the build should fail or not in case of sentry-cli failing to upload.

**Comment by bkostrowiecki** [comment]
> Hey there! Sorry to see you run into issues. But there's good news (sort of). With `2.0.7` the SDK now properly logs sentry-cli errors to the console and builds don't fail due to uploading errors. A thing to be aware tho, you do need those debug symbols uploaded if you want your issues to be properly symbolicated. Could you give version `2.0.7` a try?

I'll give it a shot.

Somehow I managed to build my game properly on version `2.0.6`. I disabled `Sctrict Mode` in build options, so I guess sentry-cli still fails under the hood, but because it runs in the post build hook it doesn't influence the build result and Unity is closed with 0 exit code. I'll try to test it on `2.0.7`.

**Comment by bitsandfoxes** [comment]
Thanks! We'll improve on that behaviour in the next release.

**Comment by bitsandfoxes** [comment]
We're now pulling the sentry-cli logs into the editor console as well. And there is an opt-out of causing the build to fail based on the upload!
