### ISSUE TITLE
Can Debug.LogError() display the complete call stack information?

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1697]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Sentry SaaS

Which version of the SDK?
v2.0.7

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
Unity2021.3.33f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

Call `Debug.LogError("xxxxxx");`
Can Debug.LogError() display the complete call stack information?

### Expected Result

![image](https://github.com/getsentry/sentry-unity/assets/103353466/c9c01bdd-d90a-44a7-8124-1cbd210e5890)

### Actual Result

![image](https://github.com/getsentry/sentry-unity/assets/103353466/fc75c5ed-8197-4f19-aa2d-df4c9a79fec4)

**Comment by bitsandfoxes** [comment]
Unfortunately, not as of right now. Right now, the fetching of the callstack relies on an exception object.
We're tracking this as a future improvement here: https://github.com/getsentry/sentry-unity/issues/1608
