### ISSUE TITLE
SocketException Access Denied when errors are attempted to upload on Meta Quest 3

### ISSUE THREAD

**Issue by emrys90** [getsentry/sentry-unity#1700]
Unity 2022.3.31f1
Sentry Unity 2.0.7

Errors do upload correctly on Windows and Android phone builds, but on the Meta Quest 3 VR headset I get the following error in logcat when Sentry attempts to upload an error:
```
2024/06/21 08:05:26.437 5385 7125 Error Unity Sentry: (Error) Failed to send cached envelope:
System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: ConnectFailure (Access denied) ---> System.Net.Sockets.SocketException: Access denied
2024/06/21 08:05:26.437 5385 7125 Error Unity   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00000] in <00000000000000000000000000000000>:0 
2024/06/21 08:05:26.437 5385 7125 Error Unity   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00000] in <00000000000000000000000000000000>:0 
2024/06/21 08:05:26.437 5385 7125 Error Unity   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncImpl[TArg1] (System.Func`4[T1,T2,T3,TResult] beginM
```

**Comment by munkiki7** [comment]
@emrys90 , please, check this [thread](https://forum.unity.com/threads/unity-removes-android-permission-internet-in-the-build-apk-after-build-is-completed.1466654/#post-9185654)

**Comment by emrys90** [comment]
I'm not using OpenXR, I'm using the Oculus Plugin, and it does not have that setting. Also, as mentioned above, I do have internet access already. I can connect to my multiplayer servers and other REST APIs.
![image](https://github.com/getsentry/sentry-unity/assets/20632855/fe71b2cd-fae7-41f0-8000-00625a0a9a02)

**Comment by munkiki7** [comment]
If I remember correctly, http error would look like this: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

But you can test the solution from this issue.

**Comment by emrys90** [comment]
Thanks for the link! I'll give that a shot if I can't figure out the https setup.

**Comment by emrys90** [comment]
I confirmed this was an http issue, switching the self hosted URL to https fixed it.
