### ISSUE TITLE
Can the dashboard count crash rates and error rates?

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry-unity#1707]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
self-hosted

Which version of the SDK?
Sentry 23.11.2
v2.0.7

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
Unity2021.3.33f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

### Steps to Reproduce

Can the dashboard count crash rates and error rates?
![企业微信截图_17195648045652](https://github.com/getsentry/sentry-unity/assets/103353466/26dacd2d-9782-433a-b0b0-2468da153abd)

### Expected Result

The crash rate can be counted normally

### Actual Result

The statistical crash rate is abnormal

**Comment by bitsandfoxes** [comment]
Hey @WeiLingQiang, could you go into more detail about what you're seeing and how that's different from what you expect?

**Comment by WeiLingQiang** [comment]
![image](https://github.com/getsentry/sentry-unity/assets/103353466/cc3556aa-174a-439d-974a-cabb2b45eb1c)

Uncountable crash rate, The statistical crash rate is abnormal

**Comment by WeiLingQiang** [comment]
![企业微信截图_17198178108597](https://github.com/getsentry/sentry-unity/assets/103353466/95acbc21-5106-455e-a517-e5118eccea6a)

Thanks. I found the problem, I need to set `options.AutoSessionTracking = true;` and `option.Release = "1.0.0";`

**Comment by bitsandfoxes** [comment]
Glad this worked out for you!

**Comment by WeiLingQiang** [comment]
![image](https://github.com/getsentry/sentry-unity/assets/103353466/270f6162-aae1-423f-84f4-1c585d905480)
There is an error:
I throw an exception: `throw new InvalidOperationException("xxx")`
It is considered a `crashed`, 
Shouldn't it be an `errored` ?
