### ISSUE TITLE
Error in sdk initial configuration

### ISSUE THREAD

**Issue by Thanor-mg** [getsentry/sentry-unity#1716]
ArgumentException: Invalid DSN: No public key provided.
```
Sentry.Dsn.Parse (System.String dsn) (at /sentry-unity/src/sentry-dotnet/src/Sentry/Dsn.cs:104)
Sentry.SentrySdk.InitHub (Sentry.SentryOptions options) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentrySdk.cs:46)
Sentry.SentrySdk.Init (Sentry.SentryOptions options) (at /sentry-unity/src/sentry-dotnet/src/Sentry/SentrySdk.cs:192)
Sentry.Unity.SentryUnitySdk.Init (Sentry.Unity.SentryUnityOptions options) (at /sentry-unity/src/Sentry.Unity/SentryUnitySDK.cs:50)
Sentry.Unity.SentryUnity.Init (Sentry.Unity.SentryUnityOptions options) (at /sentry-unity/src/Sentry.Unity/SentryUnity.cs:38)
Sentry.Unity.SentryInitialization.Init () (at ./Packages/io.sentry.unity/Runtime/SentryInitialization.cs:88)
```
Unity 2022.3

**Comment by bitsandfoxes** [comment]
Hey there @Thanor-mg! Thanks for reaching out!
This is intentional and by design. A DSN is the minimal requirement for the SDK to work at all. Our thinking is: If you installed the package then you want to use it. So we've opted for an admittedly fairly aggressive approach to require the DSN from you.
If you do not want to provide a DSN right now you can disable the SDK via the configuration window `Tools -> Sentry` and uncheck: `Enable SDK`.

**Comment by Thanor-mg** [comment]
I actually downloaded the SDK from the Asset Store, reviewed its documentation, started the initial setup, and copied the DSN that the website provided, replacing the default one. What could I have done wrong?

**Comment by bitsandfoxes** [comment]
Did you go through the wizard process that pop up the first time you open the window?

> copied the DSN that the website provided

The docs? Are you logged into Sentry? You can find your DSN on Sentry.io within the projects setting:

![Screenshot 2024-07-09 at 16 08 08](https://github.com/getsentry/sentry-unity/assets/25725783/c5ec3cbc-23a0-4873-a582-e3006276858c)

**Comment by Thanor-mg** [comment]
i take from there, but don´t work

**Comment by bitsandfoxes** [comment]
You've set it in the editor config window? Are you overwriting it by any chance in one of the config scriptable objects?
