### ISSUE TITLE
Metrics not being attached to Spans

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-unity#1718]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?

`2.1.0+8492ce278d15cf71ccaafc6a2f13cdee70cd869b`

How did you install the package? (Git-URL, Assetstore)

Git-URL

Which version of Unity?

`2022.3.36f1`

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

editor

### Steps to Reproduce

1. Create custom transaction on scope
2. Emit a metric within the custom transaction
3. Open the transaction in Discover and see that it is missing an `Emitted Metrics` section.

I saw that the current unity sdk uses dotnet 4.7.0, so I tried the same transaction in the dotnet 4.7.0 and it works as expected there.

The Metrics themselves do seem to send, but only if I move the `SentrySdk.Metrics.Increment()` outside of the transaction, where it does get sent but without any Span Samples

### Expected Result

The transaction should contain that section, and the spans should be associated with the Metric

### Actual Result

Spans are not associated with Metrics

### Any logs or screenshots

This is the transaction I used for both dotnet and unity.  

```
                var transaction = SentrySdk.StartTransaction(
                    "UnityCustomScopeTransaction",
                    "testScopeOperation"
                );
                SentrySdk.ConfigureScope(scope => scope.Transaction = transaction);

                SentrySdk.Metrics.Increment("ButtonClicked",
                tags: new Dictionary<string, string> { { "region", "us-west-1" } }
                );

                transaction.Finish();
```

**Transaction in Unity sdk without Emitted Metrics section -**

<img width="1243" alt="Screenshot 2024-07-09 at 10 27 00 AM" src="https://github.com/getsentry/sentry-unity/assets/96670625/dbd027f3-a8e6-4daf-8f4f-66b8a2dbe415">

**Transaction in dotnet sdk with the Emitted Metrics section -**

<img width="1232" alt="Screenshot 2024-07-09 at 10 28 29 AM" src="https://github.com/getsentry/sentry-unity/assets/96670625/da518cae-2d11-448a-9eab-5f1d87fbb884">

**Comment by bitsandfoxes** [comment]
That is really odd. The Unity SDK does not have any custom handling of metrics and uses the .NET SDK as-is. We'll have to investigate. Thanks for letting us know!

**Comment by Fwang36** [comment]
hey @bitsandfoxes,

Have you had a chance to take a look at this?  A user has written in asking for an update.

**Comment by bitsandfoxes** [comment]
Since it's not entirely clear how metrics are going to be sent in the near-ish future we've put this on the backlog until we know what we're building before going in and fixing it.
Sorry to have not any more helpful updates.

**Comment by bitsandfoxes** [comment]
Metrics have been deprecated and we don't fix this. You can read more about this on https://github.com/getsentry/sentry-dotnet/issues/3597
