### ISSUE TITLE
Android build&run fails when symbol-upload config is left at default in the sample

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#1734]
### Environment

current master, windows, unity 2019

### Steps to Reproduce

Android "Build and Run"

### Expected Result

run the app on device

### Actual Result

Build fails, likely due to missing symbol-upload config (actual symbol-upload checkbox is enabled by default)

### Any logs or screenshots

![Image](https://github.com/user-attachments/assets/854184b1-8a44-44f0-8f5d-1ab075cce113)

**Comment by bitsandfoxes** [comment]
We seem to have fixed that somewhere along the way. Cannot reproduce this any more.
