### ISSUE TITLE
WebGL freeze during SDK closing

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1761]
Calling `unityInstance.Quit()` causes the SDK to dispose the hub here https://github.com/getsentry/sentry-unity/blob/9b749d455aa664993b6d7e54982de46df7690532/src/Sentry.Unity/SentryUnitySDK.cs#L95
where the site hosting the webGL player then gets stuck.

**Comment by bitsandfoxes** [comment]
This can easily be reproduced with out samples game and clicking the `Quit` button.

**Comment by ziggyeye** [comment]
This is a severe issue impacting us from launching soon.  Please give us an update soon and prioritize this.
