### ISSUE TITLE
WebGL exception during IL2CPP processing

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1783]
Reported on [Discord](https://discord.com/channels/621778831602221064/1246915557731860511/1278277335615012935)

Triggering an exception causes the IL2CPP backend to throw one of its own.

![Image](https://github.com/user-attachments/assets/618934e0-95a9-4272-bd53-4f88b923ad31)
![Image](https://github.com/user-attachments/assets/966c9fde-ce77-4f99-9ee9-f89d2633c1c6)

We might need to disable the automatic integration of the IL2CPP exception processor for WebGL.

**Comment by tustanivsky** [comment]
Users can encounter this issue if the `Enhanced` stack trace mode not supported in IL2CPP builds was set via options. Even though the corresponding property is hidden for  `SentryUnityOptions` one can still access it via the `SentryOptions` base class and accidentally modify its value. The solution that should prevent users from changing the default Unity's stack trace mode can be found in a linked PR.
