### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by faysalfdt** [getsentry/sentry-unity#1784]
We love using Sentry on our iOS, Mac and Windows apps, we'd like to use it for our hololens application but am missing the ability to support UWP, any chance we could get support for it?

**Comment by bitsandfoxes** [comment]
Hey @faysalfdt, we'd like the SDK to support ALL the platforms. Do you have any specifics on what's not working for you? Have you checked the [troubleshooting docs](https://docs.sentry.io/platforms/unity/troubleshooting/#universal-windows-platform---events-not-sent)?

**Comment by bruno-garcia** [comment]
Please feel free to reopen if you have specific issues with UWP. As Stefan said we'd like to make sure it works on all platforms but we're unaware of limitations with UWP at this time.
