### ISSUE TITLE
IndexOutOfRangeException when throwing unity errors.

### ISSUE THREAD

**Issue by lucasmontec** [getsentry/sentry-unity#18]
Hey sentry devs, how are you?
Welcome to Unity.

Sentry sdk for Unity is throwing an exception when non-formatted exceptions occur. The SDK expects exceptions to have a ':' separator. Some of the exceptions in Unity don't have the ':' characters, specially because Unity has a Debug.logError method that throws strings as exceptions.

To fix this, change the code at line 185 and its surroundings in the sentry sdk package, to check if the exc array has enough length.

**Comment by Leinnan** [comment]
I've proposed fix here: https://github.com/getsentry/sentry-unity/pull/28

**Comment by bruno-garcia** [comment]
Fixed in #28
