### ISSUE TITLE
Report unstructured OS name/version as raw_description

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#182]
Currently the OS reported on Android doesn't show nicely neither groups nicely:

![image](https://user-images.githubusercontent.com/1633368/118324432-0a10c300-b4d0-11eb-876f-7ed334447399.png)
We can parse this in the SDK or rely on the server, if we report it at `raw_description`.

**Comment by bruno-garcia** [comment]
If we parse it on the server, it'll fix for all orgs already using Sentry with Unity Lite.
@jan-auer thoughts?

**Comment by jan-auer** [comment]
Agreed, assuming there's no API returning the OS like in the other mobile SDKs we have. Even though this is a platform-specific concern which by design would be best solved in the SDK, it's more reasonable to normalize this from raw_description.

**Comment by bruno-garcia** [comment]
Relay has already deployed support for parsing `raw_description` with the format's we've communicated through getsentry/relay#1004

We need to release a version now moving the reported data from `Name` to `RawDescription`
