### ISSUE TITLE
android 7: AndroidJavaException: java.lang.ClassNotFoundException: io.sentry.Sentry

### ISSUE THREAD

**Issue by kkfrank2** [getsentry/sentry-unity#1831]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
1.7.1

How did you install the package? (Git-URL, Assetstore)
Git UPM

Which version of Unity?
2020.3.42f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
android 7 not work, others is ok

### Steps to Reproduce
Empty project
Add sentry via UPM
Build and run on device (android 7)

### Expected Result
It works

### Actual Result
![Image](https://github.com/user-attachments/assets/64854273-823f-47b2-a6ec-d766a4093d9c)

**Comment by bitsandfoxes** [comment]
Hey @kkfrank2, sorry for the delay. Did you manage to resolve this?
