### ISSUE TITLE
Release CI completes without the test suite

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#1844]
Release 2.2.1 went out.
The `release/2.2.1` branch didn't seem to run the tests:

https://github.com/getsentry/sentry-unity/actions/runs/11335211101

![Image](https://github.com/user-attachments/assets/96ac0f15-3ae4-4ed3-ba77-c38831e39915)

**Comment by bruno-garcia** [comment]
Seems related to:
* https://github.com/getsentry/sentry-unity/issues/1845

The release with version `version` has the full CI run:
* https://github.com/getsentry/sentry-unity/actions/runs/11263831196
![Image](https://github.com/user-attachments/assets/d033fbcf-ea9e-4196-9099-9ca7b60be10b)

The release with `release/version` doesn't:
* https://github.com/getsentry/sentry-unity/actions/runs/11261339740
![Image](https://github.com/user-attachments/assets/61487028-4eb0-4de0-9315-1f79932d26e7)


Also note the two different bots involved

**Comment by bitsandfoxes** [comment]
For context: This was done intentionally. The idea was: If `main` is green it should not take two hours for a release to go through. But as the team is growing we should rethink such a "by convention" processes.

**Comment by bruno-garcia** [comment]
> For context: This was done intentionally. The idea was: If `main` is green it should not take two hours for a release to go through. But as the team is growing we should rethink such a "by convention" processes.

I see, that makes sense. But do we have safeguards to make sure the build from the branch (not just `main`) that we're releasing from is green and hence the release build doesn't need CI?

Also, even package validation doesn't run? If we make any mistake during the release flow (bumping versions, etc) no visibility

**Comment by bitsandfoxes** [comment]
> Also, even package validation doesn't run?

`Build` and `Package Validation` are part of the `Release` run.

![Image](https://github.com/user-attachments/assets/16339ede-d220-435b-8d0e-374976156b3d)
