### ISSUE TITLE
I just updated to 2.2.1 and now I'm see a NullReferenceException error on launch in Unity Editor (Windows)

### ISSUE THREAD

**Issue by lcnvdl** [getsentry/sentry-unity#1846]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?
2.2.1

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2021.3.34f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Windows

### Steps to Reproduce

1. Hit "play" in my project. 

### Actual Result

I'm getting an error in Unity console. I had my version 2.2.0, but because of the known issue https://github.com/getsentry/sentry-unity/issues/1841#issuecomment-2412366272 I decided to upgrade it to 2.2.1.

This is the error in 2.2.1:
```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.PropertyEditor.DrawEditors (UnityEditor.Editor[] editors) (at <0a81bd77f3334bdfa5d31008229edcac>:0)
UnityEditor.PropertyEditor.RebuildContentsContainers () (at <0a81bd77f3334bdfa5d31008229edcac>:0)
UnityEditor.InspectorWindow.RedrawFromNative () (at <0a81bd77f3334bdfa5d31008229edcac>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object) (at /sentry-unity/src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs:63)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

It happens every time I start my project in Unity Editor.

![Image](https://github.com/user-attachments/assets/37370504-f084-4c71-a23f-e7a662dfa993)

**Comment by bitsandfoxes** [comment]
Hey @lcnvdl, sorry to see you run into issues. I've tried ever which way to reproduce this in a fresh project but fail to do so.
I'm not even sure this is caused by the SDK. The SDK's loghandler integration is part of the callstack because it forwards the logs.
A workaround/fix that comes to mind is to delete and recreate the `Library` folder inside your project.

**Comment by lcnvdl** [comment]
> Hey [@lcnvdl](https://github.com/lcnvdl), sorry to see you run into issues. I've tried ever which way to reproduce this in a fresh project but fail to do so. I'm not even sure this is caused by the SDK. The SDK's loghandler integration is part of the callstack because it forwards the logs. A workaround/fix that comes to mind is to delete and recreate the `Library` folder inside your project.

Thanks for your answer.

This happened exactly when I upgraded Sentry.

Yesterday I deleted Library folder, re-open my project, and that solved the problem.

**Comment by bitsandfoxes** [comment]
Thanks for the update!
We'll look into better supporting the upgrade process as part of https://github.com/getsentry/sentry-unity/issues/1847
