### ISSUE TITLE
Missing crashpad_wer.dll in windows platform

### ISSUE THREAD

**Issue by etnlGD** [getsentry/sentry-unity#1866]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK?
1.8.0

How did you install the package? (Git-URL, Assetstore)
Git-URL

Which version of Unity?
2020.3.11f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Windows

### Steps to Reproduce

Native crash in some win32 thread. 

### Expected Result

All crashes can be captured.

### Actual Result

Crash happened in unity main thread can be captured, but crash that happened in some native win32 thread can't be captured.

### Any logs or screenshots

There will be a sentry warning log: `crashpad WER handler module not found`

### Solution

Copy crashpad_wer.dll and crashpad_handler.exe together into the final output directory.

**Comment by bitsandfoxes** [comment]
Hey @etnlGD, thanks for raising this! We'll see how we can update our build setup to support this.

**Comment by bruno-garcia** [comment]
Are these files not part of the game final build?
not sure there's much more we can do other than document that

**Comment by bitsandfoxes** [comment]
I don't think the `WER handler` specifically is.

**Comment by bruno-garcia** [comment]
is this a new thing we got from bumping sentry native?

I thought WER wasn't a thing before with crashpad?
