### ISSUE TITLE
Breadcrumb category handling

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#188]
We don't assign categories for breadcrumbs from Unity. It means that if user tries to use `options.BeforeBreadcrumb` based on the [docs](https://docs.sentry.io/platforms/dotnet/enriching-events/breadcrumbs/) (Customize Breadcrumbs section) then he/she might find a non-expected behaviour.

_Not expected stuff based on current docs_

* categories which are `null` displayed as `generic` on web UI, if the user tries to configure Sentry like this...
```csharp
SentryUnity.Init(options =>
{
    options.Enabled = true;
    options.Dsn = "<MY_DSN>";
    options.BeforeBreadcrumb = breadcrumb => breadcrumb.Category == "generic" ? null : breadcrumb;
});
```
... events **won't** be ignored on web UI, because .NET side doesn't set category to `generic`

* exception breadcrumbs are also ignored by `options.BeforeBreadcrumb` API
![image](https://user-images.githubusercontent.com/2175097/118700070-ec6a9300-b81a-11eb-956f-e14c7a5b23c1.png)

_What needs to be done_

* Assign categories for normal breadcrumbs. We need to come up with a list of possible categories for all `.AddBreadcrumb` calls

**Comment by bruno-garcia** [comment]
> We don't assign categories for breadcrumbs from Unity. 

We should set a category such as `unity.logger`

`generic` is set by Sentry if the SDK didn't send any.

Also we can just change the docs to show a different use case for `BeforeBreadcrumb` such as:

```
    options.BeforeBreadcrumb = breadcrumb => breadcrumb.Message?.StartsWith("bad crumb") ? null : breadcrumb;
```

**Comment by semuserable** [comment]
Do you want to add `_hub.AddBreadcrumb` functionality into `UnityLogger`?

**Comment by bruno-garcia** [comment]
I believe the same category is fine.
