### ISSUE TITLE
Simulator flag set to `false` when running on a iOS Simulator

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#189]
The PR #184 fixed a bug but introduced a new one.
When `isEditor` is false, it doesn't necessarily mean it's simulator false. The game could be running on an Android emulator or an iOS simulator.

The logic there needs to be: If it's in the editor, then we know it's `simulator=true`. Otherwise, we can't safely set a value for simulator.

**Comment by bitsandfoxes** [comment]
When we can't safely set a value we don't? Or do we fall back to false?
