### ISSUE TITLE
System.DllNotFoundException in ReinstallBackend

### ISSUE THREAD

**Issue by ivankosdy** [getsentry/sentry-unity#1903]
### Environment

_How do you use Sentry?_

Sentry SaaS (sentry.io)

_Which version of the SDK?_

2.3.0 (but it's been happening since 2.1.3, which was the first version that we used)

_How did you install the package? (Git-URL, Assetstore)_

Git-URL (https://github.com/getsentry/unity.git#2.3.0)

_Which version of Unity?_

2022.3.38f1, 2022.3.52f1

_Is this happening in Unity (editor) or on a player like Android, iOS, Windows?_

This error occurs in our linux player build. We currently build it on our mac building machine with linux as target OS.

### Steps to Reproduce

Game running on Linux (using our linux build on SteamOS/SteamDeck or e.g. latest version Ubuntu 24.04.1 LTS)
5 seconds after game starts sentry logs this error:

System.DllNotFoundException Sentry.Unity.Native.SentryNativeBridge in ReinstallBackend
SentryNativeBridge.cs in ReinstallBackend at line 106
internal static void ReinstallBackend() => sentry_reinstall_backend();

https://devopea.sentry.io/share/issue/93d24e4508dc4c0eb342ec5d126c2a6c/

### Expected Result

_What you thought would happen._

I wouldn't expect this error on probably every run/start of our game on linux.

### Actual Result

Game does not crash, it continues to run.

### Any logs or screenshots
Link to a random instance of this error:
https://devopea.sentry.io/share/issue/93d24e4508dc4c0eb342ec5d126c2a6c/

**Comment by bitsandfoxes** [comment]
Hey @ivankosdy, thanks for reaching out. We put a stop to that in https://github.com/getsentry/sentry-unity/pull/1898 and that'll be part of the next release coming out later today!
