### ISSUE TITLE
CI is on a infinite retry

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#1920]
The CI for [this PR](https://github.com/getsentry/sentry-unity/pull/1919) got into a infinite retry.
Tries to open a command that doesn't exist and instead of failing the build, it keeps on retrying forever

See:

> [2019 Android 27 Run Smoke Test / try-1 / try-1](https://github.com/getsentry/sentry-unity/actions/runs/11990191620/job/33427780053?pr=1919#logs)

![Image](https://github.com/user-attachments/assets/3f609bfd-8bf1-4d2d-9e7a-6e23b998c494)

**Comment by bitsandfoxes** [comment]
Should also be addressed by https://github.com/getsentry/sentry-unity/pull/1865

**Comment by bruno-garcia** [comment]
Fixed by:
* https://github.com/getsentry/sentry-unity/pull/1936
