### ISSUE TITLE
SDK configuration via window and manual setup at the same time throws System.ObjectDisposedException after error event is sent

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#193]
_Problem:_

If user has `Tools/Sentry` configured (ie `Enabled` and `Dsn` is set) **and** Sentry is initialized via `SentryUnity.Init` (ie `Enabled` and `Dsn` is set), any produced error will be throwing `System.ObjectDisposedException: Cannot access a disposed object`

_Repro steps:_
* `git checkout bug/object-dispose`
* click `Play`
![image](https://user-images.githubusercontent.com/2175097/119006448-0f22b600-b999-11eb-8c1e-addf4ba19e3d.png)

_Discussion:_
Does it mean that `SentrySdk.Init` doesn't correctly close/dispose a `hub`? Do we need to check if Sentry is initialized via window and dispose of it in some way if the user configures SDK manually? Let's discuss.

**Comment by semuserable** [comment]
@bruno-garcia your suggestion about implementing `IInternalSdkIntegration` worked! I made it public for testing purposes and implemented in all integrations. I also noticed that we should `FlushAsync` and not `Dispose` (with `Dispose` I've got `StackOverflowException`).

So, should we make `IInternalSdkIntegration` public or sign all Unity related dlls so we can use internals from Sentry SDK?

**Comment by semuserable** [comment]
Although, I found `Hub.Dispose` implementation where `Unregister` is called. Hm..

**Comment by bruno-garcia** [comment]
> So, should we make `IInternalSdkIntegration` public or sign all Unity related dlls so we can use internals from Sentry SDK?

On the next major yeah, I raised an issue in the .NET repo for that already.

**Comment by semuserable** [comment]
So, I tried something like 

```csharp
if (!_hub.IsEnabled) { }
```

but yeah, didn't work out. I guess `Hub` is enabled for both cases.
