### ISSUE TITLE
CaptureException not included in SDK?

### ISSUE THREAD

**Issue by bdrelling** [getsentry/sentry-unity#20]
I can see on the docs [here](https://docs.sentry.io/error-reporting/capturing/?platform=csharp) that `CaptureException` is included in the default C# SDK, but it appears to be stripped from this one. What should I do instead? I can only `CaptureEvent` and `CaptureMessage`, but I'm used to being able to send exceptions with data, identify users, determine the log level of an exception or message, etc.

**Comment by bruno-garcia** [comment]
The current Unity offer is a 'lite' SDK so not really compliant with the Unified API.
We are considering a full Unity SDK based on the .NET SDK (would love [your feedback on this](https://github.com/getsentry/sentry-unity/issues/15)).

**Comment by bruno-garcia** [comment]
Clarifications on this post: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222

Releases of this repository now are based on the .NET SDK and will contain `CaptureException`. So I'm going to close this, please follow the repository for releases:

![image](https://user-images.githubusercontent.com/1633368/102942330-12b21f80-4483-11eb-9cd8-59e05dcda50a.png)
