### ISSUE TITLE
Unity UPM: Error when executing git command. fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master'

### ISSUE THREAD

**Issue by loeffel-io** [getsentry/sentry-unity#228]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/getsentry/unity.git#0.2.0]:
  Error when executing git command. fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master': trying to write non-commit object da99aa1cad2a463e9254b186159a8e1b7411b788 to branch 'refs/heads/master'

**Comment by loeffel-io** [comment]
maybe: https://issuetracker.unity3d.com/issues/package-resolution-error-when-using-a-git-dependency-referencing-an-annotated-tag-in-its-git-url

**Comment by bitsandfoxes** [comment]
Hey! I encountered this issue too. (In particular with 2020.1.1) Could you maybe provide which Unity version you're on?

**Comment by bruno-garcia** [comment]
We found a [related forum issue on Unity's Forum](https://forum.unity.com/threads/git-url-revision-not-found-still-in-unity-2021-1-5f1.1105612/).

And [their issue tracker](https://issuetracker.unity3d.com/issues/package-resolution-error-when-using-a-git-dependency-referencing-an-annotated-tag-in-its-git-url)

>  there should be a fix in 2020.3.11f1 if you want to stay on 2020.3

**Comment by bruno-garcia** [comment]
Closing this because it's a Unity UPM issue and not really Sentry related.

We should add this to the troubleshooting section of the docs.

**Comment by bruno-garcia** [comment]
For reference:

Unity has fixed this bug on the following versions:

> Not reproducible with - 2019.4.23f1,2020.3.1f1,2021.1.0f1,2021.2.0a8
