### ISSUE TITLE
Make Sentry SDK more suited to Unity

### ISSUE THREAD

**Issue by Stormy102** [getsentry/sentry-unity#23]
What I feel is the biggest flaw in the Sentry Unity SDK at the moment is how difficult it is to add custom data to events. The previous Raven API allowed us to add custom tags, breadcrumbs with different levels of feedback and other features which simply aren't available.Being able to add custom tags, etc without making big changes to the core Sentry Unity SDK file is virtually impossible.

Given that this plugin is solely for use with Unity, I believe that the direction this SDK should be taken in is one that is more suited to it. This would include a custom editor, singleton maangement, a wider array of methods which allow the user to customise the reports sent to Sentry etc.

I'm happy to make my necessary changes in a pull request and demonstrate the improvements I believe would help. I'm just not sure what the direction is of this project as there seems to be little development or progress on any of the branches. It's a good foundation but needs a lot more improvement before I believe it can successfully replace the Raven .NET API.

**Comment by bruno-garcia** [comment]
@Stormy102 Thank you for your feedback! You are right the API of `sentry.unity.lite` is limited. 

But just to clarify a few things:
There's a _new_ (a year old now) SDK for .NET in [getsentry/sentry-dotnet](http://github.com/getsentry/sentry-dotnet). It's part of the [unified API across Sentry SDKs](https://blog.sentry.io/2018/08/08/new-sdk-unified-api-feedback-requested). That SDK is the replacement of `SharpRaven`.

The SDK maintained in this repository was an an initial C#6-only offer to get customer feedback. It's limited in API but it supports virtually all types of targets Unity supports. It also supports Unity as early as 5.6.

With regards to the future of the Unity support, please refer to issue #15 where we started a discussion over using the new [Sentry SDK](https://www.nuget.org/packages/Sentry) as the base.
We believe that'd be the way forward for Sentry Unity and we're looking for feedback before getting it out.

**Comment by Stormy102** [comment]
Excellent I'll offer feedback there.
