### ISSUE TITLE
Logging not working on the Android device

### ISSUE THREAD

**Issue by ludwo** [getsentry/sentry-unity#236]
I'm using Sentry SDK for Unity with self-hosted Sentry. 
The application in editor mode is logging issues correctly. I can see all my errors in the Sentry project issues page.
But when I run my application on the Android device, no logs are logged into Sentry.
I tried to debug my app directly on the device, but it seems like Sentry SDK is not enabled.

I followed documentation for installing Sentry SDK for Unity and installed it by the latest git link (v0.2.0).
I tried to configure Sentry SDK for my project by Edtor (Unity->Tools->Sentry) and also programatically.

Are there any additional steps required to get it working on the Android/iOs/iPhone devices?
I'm using custom AndroidManifest.xml, maybe I'm missing something (package) there...

### Environment

How do you use Sentry?
Self-hosted/on-premise, version Sentry 21.6.0.dev0 f96037f
sentry-unity 0.2.0
Unity 2019.4.18

Device:
Samsung Galaxy Note 20, Android 11

### Steps to Reproduce

1. Run your app in the Unity editor and log something with Debug.LogError or CapturerMessage
2. Check project issues on the Sentry server
3. All errors and messages are present in the list
4. Run your application on the (Android) device
5. No new errors/messages are  logged into the Sentry server 
6. Do it again using Unity editor as in step 1
7. All errors are logged again with new timestamps

### Expected Result

Errors and messages are logged into Sentry from Android device.

### Actual Result

Errors and messages are logged into Sentry only from Unity editor.

**Comment by bitsandfoxes** [comment]
Thanks @ludwo for raising this issue.
A fix is already in the works: https://github.com/getsentry/sentry-unity/pull/237.

**Comment by ludwo** [comment]
Are there any known workarounds for this issue?
I tried to 
- disable "Strip Engine Code" in player settings
- move link.xml to the different folders 
- remove link.xml
- fallback to version 0.0.13

It is still nbot working :/

**Comment by bitsandfoxes** [comment]
If you're on 0.2.0 you should not have a 'link.xml'. Which one are you moving?

The new release should land today (fingers crossed) but for testing purposes, you could use Mono as Scripting Backend instead of IL2CPP.

**Comment by ludwo** [comment]
I'm on 0.2.0. Link.xml was there from previous version. It is removed now.
I don't have link.xml in my Assets folder.

I'm not sure if my issue is related to the stripping issue.
I tried to switch to the Mono backend. Unity editor logging is working, device logging is not.

Below is the Init code I use
```cs
SentryUnity.Init(cfg =>
        {
            cfg.Enabled = true;
            cfg.Dsn = "$$$";
            cfg.Debug = true;
            cfg.DiagnosticLevel = SentryLevel.Info;
            cfg.DiagnosticLogger = new ConsoleDiagnosticLogger(SentryLevel.Debug);
            cfg.RequestBodyCompressionLevel = CompressionLevelWithAuto.NoCompression;
            cfg.CaptureInEditor = true;
        });
```

**Comment by bitsandfoxes** [comment]
Could you try adding `cfg.DebugOnlyInEditor = false,`?

**Comment by ludwo** [comment]
After switching to the Mono backend, I can see one important line hidden in the bunch of info messages.
It is not marked as error message in Unity console window and not logged at all when I use IL2CPP backend!

```
Error: Failed to send cached envelope: System.Net.Http.HttpRequestException: An error occurred while sending the request 
---> System.Net.WebException: Error: TrustFailure (One or more errors occurred.) 
---> System.AggregateException: One or more errors occurred. 
---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. 
---> Mono.Security.Interface.TlsException: Handshake failed - error code: UNITYTLS_INTERNAL_ERROR, verify result: UNITYTLS_X509VERIFY_FLAG_NOT_TRUSTED
```

So it seems that I have an issue with SSL certificate.
What is the difference between Sentry/Unity certificate validation in editor and on the device?
Why is it not the same behavior?

**Comment by bruno-garcia** [comment]
> So it seems that I have an issue with SSL certificate.
> What is the difference between Sentry/Unity certificate validation in editor and on the device?
> Why is it not the same behavior?

TLS is often relied on by the platform. So Unity on Mono on the editor will use one implementation and when you build with IL2CPP and run that on Android, it'll rely on another.

What version of Unity is this related to? And what platform and version of the target device?

**Comment by ludwo** [comment]
We are using self hosted Sentry with certificate failing on this test [whatsmychaincert.com](https://whatsmychaincert.com/)
So we have to fix our certificate first to get Sentry logging to work properly on our Android/iOS devices.
Thx for your help ;)
