### ISSUE TITLE
Change approach for Unity main thread retrieval

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#238]
We have the following line in `ApplicationAdapter`

```csharp
public bool IsMainThread => Thread.CurrentThread.ManagedThreadId == 1;
```

It seems we cant rely on `ManagedThreadId == 1`, suggested approach https://stackoverflow.com/questions/26452609/find-out-if-im-on-the-unity-thread. From Unity answers https://answers.unity.com/questions/62631/i-wonder-about-thread-id-plz-answer-me.html

Also, should we store this info on `IApplication` or put it somewhere else?

**Comment by semuserable** [comment]
After investigating for a bit, I think it's quite "safe" to rely on `ManagedThreadId == 1`.

```csharp
Debug.Log($"[ThreadId.Main] {Thread.CurrentThread.ManagedThreadId}"); // always 1
Task.Run(() => Debug.Log($"[Thread.TaskRun] {Thread.CurrentThread.ManagedThreadId}")); // differs
new Thread(() => Debug.Log($"[Thread.ThreadStart] {Thread.CurrentThread.ManagedThreadId}")).Start(); // differs
```

**Comment by semuserable** [comment]
After investigating for a bit, we can "save" the thread in any `MonoBehaviour.Start`. As a possible approach, we can create `GameObject` during `SentryInitialization.Init`, assign our `MonoBehaviour` and "save the thread" from there (`static` holder?).

cc @bruno-garcia

**Comment by bruno-garcia** [comment]
That sounds like a good plan. We have a MonoBehavior that @bitsandfoxes created. We discussed renaming it to a more generic thing like `SentryUnityMonoBehavior` or something. And have `event` we can subscribe/unsubscribe from the SDK to do things.

I see we have `SentryBehavior` already in. Is that used?

Keeping the reference to the main thread from a MonoBehavior is a good approach. It would need to be nullable and while processing events we'd need consider the fact that the field wasn't set yet (MonoBehavior wasn't called yet or failed to hook)

**Comment by semuserable** [comment]
`SentryBehaviour` is not used, no. Ok, will try to cook something up :)
