### ISSUE TITLE
SentryInitialization.Init is always called in tests

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#251]
`SentryInitialization.Init` is called even for the simplest test because of `RuntimeInitializeOnLoadMethod` attribute.

```csharp
public void AssertPass()
  => Assert.Pass();
```

I encountered some not expected side effects while I was writing tests for `UnityEventProcessor`.

**Comment by bruno-garcia** [comment]
Not sure how we can skip it just for tests. [Doesn't look like there's compilation directive ](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html)set when compiling for tests which makes sense since you might just run tests on a normal build.

**Comment by bitsandfoxes** [comment]
We could disable the SDK selectively for those tests where we Initialize the SDK as part of the test by loading and disabling the ScriptableOptions within the editor?

**Comment by vaind** [comment]
Hmm, why is it `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]`? Looks like something called multiple times even during normal runtime? Maybe we should instead use another event, for example this one sounds about right: [AfterAssembliesLoaded](https://docs.unity3d.com/ScriptReference/RuntimeInitializeLoadType.AfterAssembliesLoaded.html)

**Comment by bitsandfoxes** [comment]
I think think this was due to `AfterAssembliesLoaded` and `BeforeSplashScreen` not being called in the Editor.

**Comment by bitsandfoxes** [comment]
Disabling self-initialization during tests with [this](https://github.com/getsentry/sentry-unity/blob/main/test/Sentry.Unity.Tests/DisabledSelfInitializationTests.cs)
If individual test classes are supposed to be executed with self-initialization disabled they should inherit from this.
