### ISSUE TITLE
Only print to console when Debug=true

### ISSUE THREAD

**Issue by AndreiSalamon** [getsentry/sentry-unity#26]
Hey.

First off loving the SDK. Really simple to use and understand.
The only issue is that I am getting ready to release a patch of my app and I can't seem to disable the on screen logging and it shows every single Debug.Log event that I have in some scripts for internal use. I assumed that it was the UnityDebug.Log function but I set the Debug variable to false both in the script (SentrySdk) and in the editor (just in case) and it's still printing all the logs on-screen. What am I missing here?

**Comment by AndreiSalamon** [comment]
Found it.
Change line 161 in OnGUI from
        if (_lastErrorMessage != "")
to
        if (_lastErrorMessage != "" && Debug)

**Comment by bruno-garcia** [comment]
Thanks for raising this. We should add this condition to the SDK so that you don't need to edit the source in the editor. PRs are welcomed btw! :)

**Comment by bruno-garcia** [comment]
I've opened a PR. Just need to test this in the editor first and we could merge. Thanks for raising.
