### ISSUE TITLE
Errors on new install

### ISSUE THREAD

**Issue by michaeleconomy** [getsentry/sentry-unity#265]
### Environment

How do you use Sentry?
to catch and report exceptions

Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
saas

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

unity 2020 lts

### Steps to Reproduce

1 follow install instructions

### Expected Result

no errors

### Actual Result
errors:

Assembly for Assembly Definition File 'Packages/io.sentry.unity/Editor/io.sentry.unity.editor.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,string[])

Assembly for Assembly Definition File 'Packages/io.sentry.unity/Runtime/io.sentry.unity.runtime.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,string[])

(this next one appears 5 times)
File couldn't be read
UnityEditor.AssetDatabase:Refresh ()
Sentry.Unity.Editor.SentryWindow:CopyLinkXmlToPlugins ()
Sentry.Unity.Editor.SentryWindow:OnEnable ()
UnityEditor.EditorWindow:GetWindow (System.Type)
Sentry.Unity.Editor.SentryWindow:OpenSentryWindow ()

An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Assets/Plugins/Sentry/link.xml

UnityEditor.AssetDatabase:Refresh ()
Sentry.Unity.Editor.SentryWindow:CopyLinkXmlToPlugins ()
Sentry.Unity.Editor.SentryWindow:OnEnable ()
UnityEditor.EditorWindow:GetWindow (System.Type)
Sentry.Unity.Editor.SentryWindow:OpenSentryWindow ()

**Comment by michaeleconomy** [comment]
Sentry does appear to work.

**Comment by bitsandfoxes** [comment]
Hey @michaeleconomy and thanks for bringing this up.
I can reproduce the Assembly Definition warnings and will take a look into them. 
For the others: Are you by any chance using version 0.3.1 or older?

**Comment by michaeleconomy** [comment]
unity: 2020.3.11f1
sentry-unity: 0.4.3

**Comment by bruno-garcia** [comment]
@michaeleconomy were you upgrading from a previous version of the SDK? Wondering if we had dropped the link.xml in your project earlier and the new SDK is trying to do this again

**Comment by michaeleconomy** [comment]
Nope, just added sentry for the first time to this project.


Again, just so we're clear: the errors have not resurfaced and just
occurred the once.

**Comment by bruno-garcia** [comment]
> Again, just so we're clear: the errors have not resurfaced and just occurred the once.

Thanks for clarifying, at least doesn't seems a blocker. We'll keep this open in case someone else is affected and can help us repro.

**Comment by michaeleconomy** [comment]
🎉🥳🎉
