### ISSUE TITLE
Incompatibility with other packages

### ISSUE THREAD

**Issue by loeffel-io** [getsentry/sentry-unity#266]
Hey, 

version: 0.2

today we stopped using the sentry package - the reason for this, is that you include the System.Buffers.dll and many more. 

example:

`Multiple precompiled assemblies with the same name System.Buffers.dll included or the current platform. Only one assembly with the same name is allowed per platform`

Please split this up

**Comment by bitsandfoxes** [comment]
Hey @loeffel-io , sorry to hear you ran into this issue. We are aware that this is a pain for users to deal with and we are very open to suggestions on how to better deal with this.
Unfortunately, the Unity package manager does not provide a resolution for conflicting imports like these and they have to be managed by hand. For a workaround please take a look [here](https://docs.sentry.io/platforms/unity/troubleshooting/#precompiledassemblyexception-multiple-precompiled-assemblies-with-the-same-name).

**Comment by bruno-garcia** [comment]
Adding a label to help us track this. It's not the first time it happened and the work around is quite a lot of work on the side of the user ([see docs](https://docs.sentry.io/platforms/unity/troubleshooting/#precompiledassemblyexception-multiple-precompiled-assemblies-with-the-same-name)), sadly.

**Comment by bruno-garcia** [comment]
We resolved this on version 0.7.0.
Thanks for raising this and please let us know if you have any other issues.

**Comment by bruno-garcia** [comment]
We wrote a blog post about how we solved this problem: https://blog.sentry.io/2022/02/24/alias-an-approach-to-net-assembly-conflict-resolution
