### ISSUE TITLE
Make debouncing configurable

### ISSUE THREAD

**Issue by perholmes** [getsentry/sentry-unity#294]
Hi,

The 1-second debouncing is a problem. It seems to have been invented with an app in mind with extremely spammy logging, and then this huge hammer was invented to "solve it". But the problem is that it makes it hard to do proper logging in a disciplined app that doesn't just burb randomly to Debug.Log, because it cripples the sequence of events.

At the very least, this should be configurable. It might be a great quick fix for an undisciplined app. But a disciplined app shouldn't be forced to have entries randomly removed.

**Comment by bruno-garcia** [comment]
Agree debouncing should be configurable. We accept PRs if you'd like to contribute to the SDK

**Comment by bitsandfoxes** [comment]
Hey @perholmes. We now have a toggle to at least disable debouncing. We're looking into options to make it even more configurable in the future.
