### ISSUE TITLE
Sentry SDK incompatible with Unity 2021.2 Beta 9 (worked in Beta 7)

### ISSUE THREAD

**Issue by perholmes** [getsentry/sentry-unity#302]
It appears that Sentry SDK ships a DLL that's bundled from 2021.2 Beta 9 and upwards, making it impossible to use Sentry SDK because of conflicting DLLs:

`Multiple precompiled assemblies with the same name System.Runtime.CompilerServices.Unsafe.dll included on the current platform. Only one assembly with the same name is allowed per platform. (D:/Unity/*********/Library/PackageCache/io.sentry.unity@e308cb7b87/Runtime/System.Runtime.CompilerServices.Unsafe.dll)`

**Comment by perholmes** [comment]
I'll be doing the troubleshooting steps at https://docs.sentry.io/platforms/unity/troubleshooting/#precompiledassemblyexception-multiple-precompiled-assemblies-with-the-same-name to resolve it.

But consider that since this is now a conflict with a built-in Unity package starting in Beta 9, this conflict will become standard.

**Comment by bruno-garcia** [comment]
We don't test the SDK with the beta versions at this point. It's not on the plan as of yet.

**Comment by SimonCropp** [comment]
Unfortunately we dont currently have the bandwidth to actively track all betas. 

> Multiple precompiled assemblies with the same name System.Runtime.CompilerServices.Unsafe.dll included on the current platform. 

this should be fixed in version 0.7.0 (should be release in the couple of days)

**Comment by SimonCropp** [comment]
given this is tracked here https://github.com/getsentry/sentry-unity/issues/300, i will close this one
