### ISSUE TITLE
Library not loaded: @rpath/Sentry.framework/Sentry, Reason: image not found

### ISSUE THREAD

**Issue by ketourneau** [getsentry/sentry-unity#304]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
sentry-unity 0.5.1

### Steps to Reproduce

1. Create new empty project with Unity 2020.3.17f1 LTS (target ios platform)
2. Install sentry-unity 0.5.1 with upm
3. Build for ios
4. Open build result with XCode
5. Deploy on ipad

### Expected Result

App start and can use sentry-unity library.

### Actual Result

App crash and got "Library not loaded: @rpath/Sentry.framework/Sentry ... Reason: image not found".

`2021-09-06 16:13:31.972514+0200 DebugSentry[869:160732] Error loading /var/containers/Bundle/Application/49BD94D0-0A4E-41DF-9BBA-4865582FCE56/DebugSentry.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/49BD94D0-0A4E-41DF-9BBA-4865582FCE56/DebugSentry.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: /private/var/containers/Bundle/Application/49BD94D0-0A4E-41DF-9BBA-4865582FCE56/DebugSentry.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found`

**Comment by bruno-garcia** [comment]
Is this building for a real device or simulator? I ask because simulator isn't supported yet (#297)

**Comment by ketourneau** [comment]
I build and run it in real device

**Comment by bruno-garcia** [comment]
Would you please be able to provide us with a small repro? 

I've added the SDK to [this game](https://github.com/getsentry/sentry-defenses), same version 0.5.1 with Unity 2020.3.15f2 LTS and it's working properly.

**Comment by ketourneau** [comment]
@bruno-garcia It works in your game sample but not when I create new unity project.

[I add a repo project](https://github.com/ketourneau/DebugSentry/tree/master).

**Comment by ketourneau** [comment]
I found the problem, the app crash if dsn is empty.
We set sentry dsn at runtime from script.

**Comment by bitsandfoxes** [comment]
Thanks for the repo! I'll take a look. 
And double thanks for digging further and the DSN hint. That does sound like a bug.
