### ISSUE TITLE
[Windows] Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#309]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
Windows Editor
Unity 0.5.1

### Steps to Reproduce

1. Play on Editor

### Expected Result

No error occurred

### Actual Result

```
Assembly 'Packages/io.sentry.unity/Editor/iOS/Sentry.Unity.Editor.iOS.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
```

This error occurs on Unity Editor Windows and Android platform selected. On Unity Editor macOS did not occur.

**Comment by bruno-garcia** [comment]
Seems like it'll depend on the iOS build tools regardless of what platform you've currently selected.
As a work around, even though it doesn't make sense on Windows, is it possible to install the iOS build tools?

Does it result in a console error only? Does this block you from building an Android player or playing in the editor?

**Comment by ArnauKokoro** [comment]
Hi @bruno-garcia unfortunately we cannot install iOS build tools on Windows.

Yes, it results as a console error and makes a crash so it stops the playing editor.

Thanks!!

**Comment by bruno-garcia** [comment]
Thanks for the info. We're trying to find a solution for this

**Comment by bitsandfoxes** [comment]
Hey @ArnauKokoro, thanks again for bringing this to our attention. We've excluded everything iOS related from the Win platform and the next release will contain a fix for this issue!
