### ISSUE TITLE
Use GHA `concurrency` to lock a single run per license used

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#312]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

Currently two pushes will trigger two concurrent builds where the second fails due to license issues

**Comment by vaind** [comment]
I've had a look at this after the painful start of the week with a lot of license failures... Currently `concurrency` doesn't provide an option to limit to a specific number, it only enforces "one" for a given group name. I was also thinking of using a modulus operator to construct the group name based on a job run ID - not ideal but kinda what we need, but there's no `%` in expressions either, so it would need to be a manually composed disgustingly-long expression composed of ternary operations to emulate the "modulus 6" (the current number of available licences)
