### ISSUE TITLE
Enforce code format via GHA

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#313]
Comes from: https://github.com/getsentry/sentry-unity/pull/296#discussion_r699415892

**Comment by bruno-garcia** [comment]
I also added to the .NET repo, so maybe we run both in the same action:

https://github.com/getsentry/sentry-dotnet/blob/main/.github/workflows/format-code.yml

**Comment by bruno-garcia** [comment]
We really need to consider canceling the previous builds after we push to the branch any code formatting. I'm afraid we'll always build twice, for each PR:

1. The original commit
2. The reformatting push

There's no built-in way to have a new push to a PR cancel any running builds to 'make room' for the new one. But I found this: https://github.com/marketplace/actions/cancel-workflow-action
