### ISSUE TITLE
Automate Android symbol upload

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#336]
* Document the need to enable the 'Create symbols.zip`:
  * ![image](https://user-images.githubusercontent.com/1633368/134593940-c0dc1011-1048-4beb-8025-7d897db1c37d.png)
  * On Unity 2021 this is a drop down. Clarify which option is needed
* Validate if the resulting `zip` contains the same/all symbols Sentry Gradle plugin would find
  * ![image](https://user-images.githubusercontent.com/1633368/134593920-025d02c0-56e3-485c-88c7-30b4be313172.png)
* Consider the approach from [`sentry-wizard`](https://github.com/getsentry/sentry-wizard) but being aware it currently adds a `sentry.properties` with an auth token we likely don't want to check-in to vcs

**Comment by bitsandfoxes** [comment]
We do not require the `Create symbols.zip` flag anymore as we grab the symbols from the `Temp` directory itself or copy them to the exported project to upload them later.
