### ISSUE TITLE
Document support for Objective-C exceptions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#343]
The SDK can capture Objective-C exceptions.
There's a sample for it. But it requires changing the xcode project to opt-in for Objective-C Exceptions:

![image](https://user-images.githubusercontent.com/1633368/134990025-92f78e2c-b9fb-493c-a0f0-75a31467a228.png)

The sample can deal with the lack of this property, by printing:
```
2021-09-27 17:50:07.956591-0400 unity-of-bugs[15263:4925126] Objective-C Exceptions are disabled. Consider enabling it in the Xcode project: GCC_ENABLE_OBJC_EXCEPTIONS
```

The property within xcode is: `GCC_ENABLE_OBJC_EXCEPTIONS`

Alternatively we could have an advanced option in the native SDK configuration that automatically makes this configuration when creating the xcode project. See: https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/issues/87#issuecomment-375904634

**Comment by bitsandfoxes** [comment]
Closed by #718 and https://github.com/getsentry/sentry-docs/pull/4992
