### ISSUE TITLE
UPM package should reference dependencies instead of including them

### ISSUE THREAD

**Issue by judithgull** [getsentry/sentry-unity#354]
When installing the sentry package via UPM, a few dependencies are included as dlls in the package (e.g. System.Threading.Task.Extension.dll).

This leads to problems, if some of the dependencies already exist (from other packages).

In our case System.Threading.Task.Extension.dll is provided by sentry and NSubstitute.

See also forum post: https://forum.sentry.io/t/replace-dependency-dll-files-in-upm-package-with-external-dependencies/15109

**Comment by bitsandfoxes** [comment]
Hey @judithgull and thank you for raising this. We are aware of this issue and the potential for friction it causes.
We are currently looking into a solution to this by merging our dependencies either into the SentrySDK or its own DLL (tracked here: https://github.com/getsentry/sentry-unity/issues/300)

**Comment by judithgull** [comment]
Great, that should work, thank you!

**Comment by bruno-garcia** [comment]
We wrote a blog post about how we solved this problem: https://blog.sentry.io/2022/02/24/alias-an-approach-to-net-assembly-conflict-resolution
