### ISSUE TITLE
Replace template manifest with our Sentry's to improve builld times

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#365]
We have a chicken-egg situation: We need to open a Unity project to restore the Library to get the TestRunner.dll but if we open the samples-project undesired thing happen as for example .meta files get deleted. We need that dll to build Sentry.

1. Create 'Temp' project (Unity creates the project by opening it and that takes time)
2. Replace the default package.json with our custom one
3. Reopen 'Temp' project so Unity can load/restore the Library
4. Copy what we need to where we need it.

For that, we need to open up the 'Temp' project twice. 

ALTERNATIVE:
An alternative would be to modify the template manifest file at `Application/Unity/Hub/Editor/{VersionNumber}/Unity.app/Contents/Resources/PackageManager/Editor/manifest.json` (for mac) to include the TestRunner (and maybe exclude a bunch of things we don't need).

**Comment by bitsandfoxes** [comment]
Alternatively: Custom Template

**Comment by vaind** [comment]
Do I understand this correctly that this is "just" for development/CI? Not affecting lib users?

**Comment by bitsandfoxes** [comment]
Yes. It's just manipulating the dev environment and would not affect the user in any way. The only caveat is that this would modify the package setup globally. 
I'd much more prefer to create our own template and add it to the hub but unfortunately, there don't seem to be any arguments to pass it from command line.
