### ISSUE TITLE
Sentry super-picky about assembly versions

### ISSUE THREAD

**Issue by perholmes** [getsentry/sentry-unity#367]
Admittedly, I'm on 2022.1.0a11, but Sentry is extremely picky about assembly versions. And because of the problem with shipping Sentry with DLLs that duplicate Unity DLLs, it becomes basically impossible -- not just annoying -- to use Sentry outside of the extremely narrow configuration it's compiled for:

Here's Sentry 0.6.0 on Unity 2022.1.0a11:

`Assembly 'Packages/io.sentry.unity/Runtime/Sentry.dll' will not be loaded due to errors:
Sentry references strong named System.Buffers Assembly references: 4.0.2.0 Found in project: 4.0.3.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"`

One thing is to not officially support Unity versions than the current official one. It's quite something else if the library is compiled in such a way that it basically sabotages use outside of this one Unity version.

The very ugly and dangerous solution is to disable Assembly Version Validation in Player Settings. But this is terrible.

I feel like you should either fix the DLL problem, or not be so rigid about library versions. The alternative is to hack the Unity Searcher package, which is usually where Unity ships these official DLLs in a version Sentry doesn't like.

I hope you can see that these two problems together makes Sentry incredibly brittle in real-life situations.

**Comment by bruno-garcia** [comment]
We resolved this on version 0.7.0.
Thanks for raising this and please let us know if you have any other issues.

**Comment by bruno-garcia** [comment]
We wrote a blog post about how we solved this problem: https://blog.sentry.io/2022/02/24/alias-an-approach-to-net-assembly-conflict-resolution
