### ISSUE TITLE
Support iOS builds with bitcode enabled

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#384]
User on this [YT video](https://www.youtube.com/watch?v=bHc4QMlV8bM) mentioned:

> .. on iOS, I am able to make local build & check, but Archiving the build is getting failed. If I disable BitCode in XCode Build-Settings, archive is happening. But I need BitCode Enabled for some of my other libraries. Can you let me know how I can use it along with BitCode-Enabled & also archive successfully. Lot of thanks in advance...

**Comment by bitsandfoxes** [comment]
I have not encountered any issue when building with `bitcode` enabled so far. And it's enabled by default on all Unity versions. And I did some extensive building now that we have symbol upload with and without bitcode.
