### ISSUE TITLE
Report `environment=editor` when running in the editor

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#39]
The environment reported with the events should be `editor` so it can be easily picked out from `production` or others.

**Comment by semuserable** [comment]
Can be done via `Application.isEditor`. Where should we put this info from `Sentry API` perspective?

**Comment by bruno-garcia** [comment]
> Can be done via `Application.isEditor`. Where should we put this info from `Sentry API` perspective?

The place today is the `UnityEventProcessor` but we can revisit this later. That also needs to be tested
