### ISSUE TITLE
Crash touching screen while changing scene (ANDROID)

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#392]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Unity 0.6.0 (ANDROID)

### Steps to Reproduce

1. Touching screen when loading scene

### Expected Result

App not crashing

### Actual Result

Touching screen when changing scene crash the app and throws an error log on Android:
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 31846 (UnityMain), pid 31670

Searching on google seems to be a memory violation.

Uninstalling Sentry this is not happening.

**Comment by bruno-garcia** [comment]
Thank you for the update. We'll try to reproduce it again.

**Comment by bitsandfoxes** [comment]
@ArnauKokoro I've been trying to reproduce it but no luck so far. I tried using the videoplayer a couple of different way like material override or render texture and placing it inside the UI. Are you doing anything special to it? Is it Unity's built in videoplayer or maybe a native plugin? That maybe might explain the native conflict? Is there any kind of behaviour attached to touching the videoplayer?

**Comment by bruno-garcia** [comment]
It would really help us find this issue if you could share a reproduction repo. Perhaps trimming down your current project by removing your code (while ensuring the issue still happens)?

**Comment by ArnauKokoro** [comment]
@bruno-garcia yes, as soon as we can, we will give you a brief example of code to reproduce it. Thanks.

**Comment by ArnauKokoro** [comment]
Seems to be fixed on 0.6.2. Closing this issue. I will reopen if we see it happens again and we have some test project to reproduce it.
