### ISSUE TITLE
Enable dSYMs generation on iOS builds

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#393]
The default on Unity (tested on 2019.4) is to build release apps without generating dSYMs. During our xcode manipulation, where we add the SDK, we should adjust this setting to make sure dSYM's are created.

**Comment by bitsandfoxes** [comment]
A bit more context:
- - Bitcode is enabled by default (so we have to check if it's disabled before we try doing anything with the symbols)
- Debug Information Format has to be set to DWARF with dSYM file
- If dSYMs get generated they end up somewhere here: `~/Library/Developer/Xcode/DerivedData/BUILD_ID/Build/Products/BUILD_TYPE/.`

**Comment by bitsandfoxes** [comment]
With https://github.com/getsentry/sentry-unity/pull/443 we now set the Debug Information Format to `DWARF with dSYM file` irrespective of the build type.
