### ISSUE TITLE
"Library not loaded: @rpath/Sentry.framework/Sentry, Reason: image not found" if project built on Windows

### ISSUE THREAD

**Issue by TigerHix** [getsentry/sentry-unity#400]
### Environment

Sentry Unity SDK 0.6.0, installed with UPM
Unity Editor 2019.4.32f1 Personal

### Steps to Reproduce

1. Build iOS project with Sentry on Windows.
2. Copy project to a Mac and build with Xcode.
3. The app builds successfully; however, when run on a device (not an emulator), the app crashes on launch. Xcode shows this message: `Library not loaded: @rpath/Sentry.framework/Sentry, Reason: image not found`

I then copied the Unity project to the Mac, build it in Unity and Xcode - this time it works flawlessly.

Another plugin that I use, [Lunar Console](https://github.com/SpaceMadness/lunar-unity-console), also had [this issue](https://github.com/SpaceMadness/lunar-unity-console/wiki/Troubleshooting#xcode-interface-builder-could-not-open-the-document-because-it-does-not-exist) (i.e., framework not copied to output project if building on Windows instead of Mac). This is how they [fixed it](https://github.com/SpaceMadness/lunar-unity-console/blob/67f0e241a243024b572dd9d53a4e1d5e9cdab967/Project/Assets/LunarConsole/Editor/BuildPostProcessor.cs#L60). Hope that helps!

**Comment by TigerHix** [comment]
> @TigerHix Are you building an iOS player on Windows? Where do you get this message, in Unity's console? What version of Unity are you using?

I am updating the post now with relevant details :) I accidentally pressed on the submit button right after I typed the title.

**Comment by TigerHix** [comment]
Updated the post.

**Comment by TigerHix** [comment]
I would also mention that although the current Sentry Unity SDK [troublshooting] page mentions this issue, the solution it provides did not work in my case (I already installed Sentry with UPM).

**Comment by bruno-garcia** [comment]
Thanks for all the details, we'll look into it asap

**Comment by bitsandfoxes** [comment]
Thanks for reporting this and also providing a link to the fix @TigerHix. I was able to reproduce this and a PR will be up shortly.
I'm curious, is that your regular dev workflow? You export the Xcode project on Windows and just build on a mac?

**Comment by TigerHix** [comment]
> Thanks for reporting this and also providing a link to the fix @TigerHix. I was able to reproduce this and a PR will be up shortly.
> I'm curious, is that your regular dev workflow? You export the Xcode project on Windows and just build on a mac?

Yes, this is indeed my regular dev workflow. Building the iOS project on Windows is much quicker (I don’t have a M1 Max Mac, so 😛); also, Unity sometimes messes up the scene MonoBehavior serialization when project is reimported on a different platform - it actually happened to me this time: after copying and reimporting the project on a Mac, some values serialized in the scene were lost, and I have to manually serialize those values again. So it’s much preferable to have a fix for building on Windows.

**Comment by bitsandfoxes** [comment]
I see. The scene serialization issue made me want to flip a table or two too. 😅 
What I also noticed, did you manually enable the Sentry.Unity.Editor.iOS for Windows? We had it disabled due to dependency issues with the iOS module not being found on Windows. So Sentry shouldn't be making changes to the Xcode generation in the first place.

**Comment by TigerHix** [comment]
> I see. The scene serialization issue made me want to flip a table or two too. 😅 What I also noticed, did you manually enable the Sentry.Unity.Editor.iOS for Windows? We had it disabled due to dependency issues with the iOS module not being found on Windows. So Sentry shouldn't be making changes to the Xcode generation in the first place.

What is Sentry.Unity.Editor.iOS? If you meant the native support for iOS checkbox in the Sentry configuration pane, yes I do have that checked.

**Comment by bitsandfoxes** [comment]
I mean the .dll responsible for adding Sentry to the Xcode project should be disabled on Windows. Sentry shouldn't try to add itself and the build output shouldn't fail because it shouldn't be looking for the .framework in the first place. I'm just trying to recreate your steps how you got it to do so anyway.

![Screenshot 2021-11-05 at 22 52 24](https://user-images.githubusercontent.com/25725783/140583167-36a4065c-15ed-40f0-be4a-bdf12901d2ae.png)

**Comment by hesham-akmal** [comment]
In Unity, from the windows environment, install sentry as an asset instead of UPM, navigate to the framework and click, then check "Add to Embedded Binaries" in the inspector (Only in newer unity versions, might be from 2018+), this will add the framework in the "Embed Frameworks" in the xcode. Which will prevent app from crashing on startup. However my app is not catching native iOS exceptions, only unity errors. I'm not sure yet if it's due to the building from windows yet.

**Comment by hesham-akmal** [comment]
![image](https://user-images.githubusercontent.com/22731896/142281117-4554526a-ac48-4cf4-88db-8bb0d5be9085.png)
![image](https://user-images.githubusercontent.com/22731896/142281154-a8a0a2db-8c98-457d-bf99-351f99d95a96.png)

I think I have successfully caught those exceptions (Which I believe are native iOS ones) By building xcode from unity on windows environment, and actually building ipa from iOSBuilder asset which also runs on windows.

How I did that is by doing the above ^ post steps, then copying src code of the post build process and commenting out some lines:

![image](https://user-images.githubusercontent.com/22731896/142282473-638963f5-5c49-415c-92e7-5da337436c67.png)
![image](https://user-images.githubusercontent.com/22731896/142282551-54b16352-bf86-45e9-8ca0-e7386282efd5.png)

"options?.Validate()" Is probably important but as it's not possible to run on windows, it's the only workaround for now

**Comment by bitsandfoxes** [comment]
Hey @TigerHix, we addressed exporting issue on Windows, and the fix is available in the 0.8.0 release. We would greatly appreciate you checking it out and feel free to reach out if you're running into any issues.

**Comment by bruno-garcia** [comment]
We've made some changes on [version 0.10.0](https://github.com/getsentry/sentry-unity/releases/tag/0.10.0) because this was causing too many issues

See PR https://github.com/getsentry/sentry-unity/pull/559 for more details
