### ISSUE TITLE
Release package: Device/Simulator framework missing

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#406]
`package-dev/Plugins/iOS` contain .frameworks for `Device` and `Simulator` but they do not get copied over to the release package.

**Comment by bruno-garcia** [comment]
Just ran this locally `dotnet build && pwsh ./scripts/pack.ps1` and I go:

![image](https://user-images.githubusercontent.com/1633368/140585933-46cd3a7c-eb7a-4d75-a800-0be8365c2ca9.png)

Maybe I'm missing something?

**Comment by bitsandfoxes** [comment]
It should work. The 0.6.0 on `/unity` does not match with the 0.6.0 on `/sentry-unity`. There must have been an issue in the release process. The changelogs don't match. 
One has the iOS simulator support and the other doesn't.

**Comment by bruno-garcia** [comment]
This is resolved in latest builds so on 0.6.1 it'll be fixed.
