### ISSUE TITLE
Debug Symbols

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#415]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Unity 0.6.1

### Steps to Reproduce

_To upload debug symbols for Android, just make sure Create symbols.zip is enabled in the build settings. Unity will generate them in the same directory as the build output, and sentry-cli accepts .zip files._

1. Generate that Create symbols and uploading them to Sentry. We can see the files uploaded.
Do we need to link that files to the Release Version on Sentry dashboard??

### Expected Result

More details on Sentry logs because Debug Symbols are uploaded.

### Actual Result

We can see the same Stacktrace that I have when Debug Symbols where not uploaded. Just Debug.Log() we have and the class and method where that occurs, but it is not showing as the file, just the name of the file.

Can we expect more details like the line where the errors happen?

Many thanks!!

**Comment by bitsandfoxes** [comment]
Hey @ArnauKokoro! What additional details are you missing? The symbols you uploaded do not contain the file itself if that's what you're asking. They "just" help translate back into a human readable format.
On Sentry it'll look like this:  
![symbolication](https://user-images.githubusercontent.com/25725783/141829675-51dd76ba-d50e-4bf2-b4a1-6a0499ae3a87.gif)

And instead of i.e. <unknown> it shows the actual error on the issues page.

Maybe I'm missing the point, can you give me a link to the issue on Sentry so I can take a look?

**Comment by ArnauKokoro** [comment]
I see, so we have all can see.

Thanks!!

**Comment by ArnauKokoro** [comment]
Hi guys, re-open to ask.

I have the BCSymbolsMaps for iOS uploaded to sentry and debug symbols for android generated from Unity also uploaded.

And I can see the method where the exception happens but no the line.

<img width="509" alt="sentry_logs" src="https://user-images.githubusercontent.com/80262126/143573754-56bb3759-6487-4672-8273-28d712421791.png">

Some help?

**Comment by bruno-garcia** [comment]
That's a C# method and unfortunately Unity doesn't support line number in builds with IL2CPP so u til they add support, there's nothing Sentry can do.

**Comment by ArnauKokoro** [comment]
Thanks!!

For iOS is there any similar? Because I have the same error log (that screenshot) on iOS also and I can't see the line either.

**Comment by bruno-garcia** [comment]
@ArnauKokoro Currently, the Sentry SDK for Unity can give you line numbers for code written in Objective-C, C, C++, Kotlin, Java. C# too, if you're running Mono. If you're using Unity 2020.2, or higher, IL2CPP's debug builds also include it. But it's unlikely you're shipping a debug build to your customers.

Until Unity creates a way to symbolicate stack traces on the backend, or allows for Release builds with line numbers, there's nothing we can do. That's the case for any IL2CPP player. Desktop, Console, Mobile, etc.

More info on their forum: https://forum.unity.com/threads/il2cpp-missing-line-numbers-in-stack-trace.808500/
