### ISSUE TITLE
Empty Sentry.Framework folder in 0.6.1

### ISSUE THREAD

**Issue by ketourneau** [getsentry/sentry-unity#416]
Folder "Plugins/iOS/Device/Sentry.framework/" and "Plugins/iOS/Simulator/Sentry.framework/" is empty in 0.6.1 package release.

**Comment by bruno-garcia** [comment]
We'll release 0.6.2 with a fix soon

**Comment by bruno-garcia** [comment]
![image](https://user-images.githubusercontent.com/1633368/141835666-3987f9a5-2a51-463d-a90a-0ce046765b9e.png)
