### ISSUE TITLE
Sentry/Sentry.h not found

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#418]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Unity 0.6.1

### Steps to Reproduce

1. Build iOS

### Expected Result

Build not failing

### Actual Result

On version 0.6.1 on Frameworks folder there is a symbolic link to Sentry.framework (it is empty) and on version 0.6.0 there is a symbolic link to io.sentry.unity folder. Seems to be the problem because it can't finds Sentry/Sentry.h when building with 0.6.1.

**Comment by ArnauKokoro** [comment]
I found the problem. It is because Sentry.framework inside Frameworks folder is empty. I solved it copying files inside Sentry.framework from Xcode Project with 0.6.0 sentry plugin and paste them to Frameworks/Sentry.framework folder.

**Comment by bitsandfoxes** [comment]
Apologies for the inconvenience. This should be resolved by https://github.com/getsentry/sentry-unity/pull/417 and the new 0.6.2 release. When we added windows to our CI the final artifact we used for release got mixed up and was missing the framework. Thanks for raising this!

**Comment by jesusonoro** [comment]
Hi @bitsandfoxes , I'm using the last version, imported Sentry for my Unity project today but this bug keeps showing up. What should I do?

**Comment by bitsandfoxes** [comment]
@jesusonoro did you export the Xcode project on Windows? Can you see `Frameworks/Sentry.framework`inside of Xcode?
