### ISSUE TITLE
Define Repository Structure

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#44]
The current structure is suboptimal. We need to address:

Parts of the repo:
* Unity sample project
* Actual package (installable through UPM (blocks #43)) - needs to be on the root?
  * maybe `~` to ignore some directories we use for dev or samples?
* Folder for source code
* Git submodules
* Add codeowners and issue_template (to indicate Unity version)

...

* Sample project
  * So we can build the `.sln` and get updated bits into Unity and test it out.
  * [Add this project as a sample](https://github.com/bruno-garcia/unity-of-bugs)
  * [Delete these unused files](https://github.com/getsentry/sentry-unity/tree/main/test/samples)

**Comment by semuserable** [comment]
Closed by https://github.com/getsentry/sentry-unity/pull/51
