### ISSUE TITLE
Setup GH actions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#45]
Configure GH actions:

* Restore submodule
* build the sln (which copies dlls into Unity folders)
* Build sample game

Min LTS: 2019.4.16f1

**Comment by Tyrrrz** [comment]
For reference: https://game.ci/docs/github/getting-started

**Comment by Tyrrrz** [comment]
It seems like setting up the CI is rather trivial because UTF supports running tests from CLI.
Essentially, as soon as #54 is implemented, this issue comes down to putting the correct command in a GHA workflow.

**Comment by bruno-garcia** [comment]
Just merged another PR so it looks like we're ready for CI. There's a test project already too.

The idea is that the release flow can be basically a bash script under `scripts` that deletes all content of `package` and copies all files from `package-dev` into `package`.

The installation instructions is to use UPM pointing to `package`.

**Comment by Tyrrrz** [comment]
There is a test project, but no tests yet from what I can tell.
Have we decided on a testing strategy already? I remember discussing testing via a button on a scene.

**Comment by bruno-garcia** [comment]
Let me GitHub that for you: https://github.com/getsentry/sentry-unity/blob/0d9dfa75621b00736a8ff8fcbfdbd92fb5424806/src/Sentry.Unity.Tests/SimpleTests.cs

:trollface:

**Comment by bruno-garcia** [comment]
> There is a test project, but no tests yet from what I can tell.
> Have we decided on a testing strategy already? I remember we were discussing something about testing via a button in a scene.

I believe we'll have some unit tests going on but definitely we need a scene and some UI/E2E tests going on.

I briefly talked about this with @semuserable today on a call, maybe tomorrow you two can sync?
