### ISSUE TITLE
Sentry .NET Enhanced stacktrace breaks on Mono

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#46]
> Path.GetFileName throws on Mono for "<2138123765123>" values, while on .net 5 doesn't throw.

https://github.com/getsentry/sentry-dotnet/blob/4e41189a211a4b60a20180edd3bfe113dc7030e3/src/Sentry/SentryOptions.cs#L446

Work around is to use `StackTraceMode.Original` for now (milestone 0.1.0)

But we can change the .NET SDK to special case `<mvid>` and not call `Path.GetFileName` or any other API that breaks. In a future milestone.

**Comment by semuserable** [comment]
Should this one be removed from `0.1.0` milestone?
