### ISSUE TITLE
Native support and using BeforeSend to enrich events

### ISSUE THREAD

**Issue by CodinRonin** [getsentry/sentry-unity#476]
**Problem:**
I'd like to enrich all the events send by sentry using custom data that is relevant for the state of the app, but at the same time I'd like to use Native Support.

Native support requires Sentry to be configured for "automatic" initialization using the configuration from SentryOptions.asset, but this way of initializing does not support using the _BeforeSend_ hook that's available if you Init programatically. 

**Question:**
Is there a way to achieve this, that I maybe am not aware of? If no, is there maybe plan to allow this in the future?

_On another note: Is there maybe a more appropriate place to open discussions like these (like forum, direct e-mail, etc..)?_

**Comment by bitsandfoxes** [comment]
Hey @CodinRonin, we have a discord channel you're more than welcome to join: https://discord.gg/D95kcPsp

We are acutely aware of the current limitation our config window and automated initialization for native support imposes on users. We plan on adding native support with the programmatic approach and to support the before-send functionality in combination with the config window, we're just not quite there yet.
On the plus side: We're very happy and open to any insights and inputs you might have on that topic.

**Comment by oddgames-david** [comment]
Is there an ETA on when programmatic init with native support will work?

**Comment by bitsandfoxes** [comment]
Unfortunately, I can't give you an ETA yet. I'll bring it up with the team.

**Comment by bruno-garcia** [comment]
This is something we want to look at very soon. We're considering #511 as a solution

**Comment by oddgames-david** [comment]
Send attachment file/folder, name etc to native sdk when scope.AddAttachment is called and have the native sdk remember it and send those files (if they still exist) when an exception occurs. Compression support would be very handy, use case for me is just pointing at our database location which is multiple files.

**Comment by vaind** [comment]
Programmatic options configuration has landed in [v0.10.1](https://github.com/getsentry/sentry-unity/releases/tag/0.10.1)
