### ISSUE TITLE
No line numbers on IL2CPP stack traces

### ISSUE THREAD

**Issue by AndreiSalamon** [getsentry/sentry-unity#486]
So I came to find that everything works fine in the editor but in non-developer builds there are no line numbers in the stack trace, only the function name that throws the exception.
Does anyone have a solution for this that does not involve the developer build mode?

**Comment by vaind** [comment]
This is in progress, right? 

And related to #614?

**Comment by bitsandfoxes** [comment]
Yes.

**Comment by bruno-garcia** [comment]
For reference, the il2cpp flag needed:

https://github.com/Unity-Technologies/UnityCsReference/blob/79d86f859b8454fcacc96962eb6e455cf6cd4f45/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs#L829-L830

**Comment by bruno-garcia** [comment]
Part of it done here: https://github.com/getsentry/sentry-unity/pull/683

**Comment by bruno-garcia** [comment]
Sentry can give you line numbers on C# exceptions with IL2CPP backend.

Update the SDK to 0.22.0 or later and give it a try: https://docs.sentry.io/platforms/unity/configuration/il2cpp/

Please raise a new issue if you encounter any problems
