### ISSUE TITLE
Add Unity Context

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#49]
Values that could be part:

[`Application.stackTraceLogType`](https://docs.unity3d.com/ScriptReference/StackTraceLogType.html): Key `stackTraceLogType` and value should be its value to indicate what's being logged.

i.e: 

```
`@event.Contexts["Unity", new {
"stackTraceLogType": stackTraceLogType
};
```

There's a lot more context data that Unity surfaces via an API, we need to find out what's useful for troubleshooting and add to events:

![image](https://user-images.githubusercontent.com/1633368/107130901-174e5e00-68a0-11eb-95d7-2c9380ab5fb6.png)

Move all the `Extra` stuff into the context:
![image](https://user-images.githubusercontent.com/1633368/107230041-8b961800-69ec-11eb-882f-e7d0b8b222f5.png)

Consider that some inforamation Unity provides already fits our current protocol. For example `device.online` could be set based on Unity's `internetReachability`

Spec for protocol types: https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context

**Comment by bruno-garcia** [comment]
Suggestion for a breakdown of data;

```
### Device Context

* Application.genuine
* Application.internetReachability

### Application Context

### Unity Context
* Application.isEdtor

```

We can also consider low cardinality values to be used as tags. Such as `Application.internetReachability` which would help identify crashes that only happen when the device is offline, for example.

**Comment by semuserable** [comment]
# [Existing context] Device

* [New] ProcessorCount - SystemInfo.processorCount
* [New] ProcessorType - SystemInfo.processorType
* [New] ProcessorFrequency - SystemInfo.processorFrequency
* [New] SupportsVibration - SystemInfo.supportsVibration
* [New] DeviceType - SystemInfo.deviceType
* [New | Unity] BatteryStatus - SystemInfo.batteryStatus
* [New] DeviceUniqueIdentifier - SystemInfo.deviceUniqueIdentifier
* [New] MaxTextureSize - SystemInfo.maxTextureSize
* [New] SupportsAccelerometer - SystemInfo.supportsAccelerometer
* [New] SupportsGyroscope - SystemInfo.supportsGyroscope
* [New] SupportsAudio - SystemInfo.supportsAudio
* [New] SupportsLocationService - SystemInfo.supportsLocationService
* [New] SupportsComputeShaders - SystemInfo.supportsComputeShaders
* [New] SupportsGeometryShaders - SystemInfo.supportsGeometryShaders

# [Existing context] Gpu

* [New] GraphicsShaderLevel - SystemInfo.graphicsShaderLevel
* [New] SupportsDrawCallInstancing - SystemInfo.supportsInstancing
* [New] SupportsRayTracing - SystemInfo.supportsRayTracing (Ray tracing support depends on the following: operating system support, GPU, graphics drivers and graphics API.)

# [Existing context] OperatingSystem

* [New] Family - SystemInfo.operatingSystemFamily

# [New context] Unity

* InstallMode - Application.installMode (Store, DeveloperBuild, Adhoc, Editor, etc)
* CopyTextureSupport - SystemInfo.copyTextureSupport
* RenderingThreadingMode - SystemInfo.renderingThreadingMode

**Comment by chamnassi2** [comment]
SystemInfo.supportsRayTracing  is very poor option for unity 2018.4 
SystemInfo.supportsRayTracing option added since 2019.3 

your team need to test for more versions
