### ISSUE TITLE
Give access to SentryUnityOptions.Integrations to allow for removing default integrations and allow overriding them

### ISSUE THREAD

**Issue by oddgames-david** [getsentry/sentry-unity#492]
I don't want to use Application.logMessageReceivedThreaded or Application.logMessageReceived for exception reporting but instead use ILogHandler because it usually gives me access to a context UnityEngine.Object which I can collect additional data from and add as attachment or extra.

Currently solving it by using reflection but I feel default integrations should be editable and even the classes themselves should be overridable.

**Comment by bitsandfoxes** [comment]
Interesting idea! We've already been discussing adding more Unity-specific context data to the events and this might be a way forward. Thanks for your input.

**Comment by bruno-garcia** [comment]
This is very relevant and we will take into consideration. Is there a need for a hook here (a callback that gives you the Event or Breadcrumb together with the Unity object? Or do you see something where we can already extract generally data from  UnityEngine.Object and add to event/crumbs?

**Comment by oddgames-david** [comment]
@bruno-garcia I just need to be able to make my own integrations and remove default ones, it seems like there is already enough flexibility in the sdk to do what I want. I currently remove the integration with reflection:
![image](https://user-images.githubusercontent.com/1932174/149042368-5ed5983f-e0d2-4fdf-ba8e-1432d4e83e12.png)

Then have this fire off exceptions and breadcrumbs:
![image](https://user-images.githubusercontent.com/1932174/149042347-44360cc4-fcad-4a82-81d3-b68e9097ac51.png)

**Comment by bitsandfoxes** [comment]
Closing this as we've added extensions to disable default integrations to the options object here
https://github.com/getsentry/sentry-unity/blob/1cc3587faac15e980d21185af8bf3d23e94957d2/src/Sentry.Unity/SentryUnityOptionsExtensions.cs#L78-L107

If there's something you miss from having control over it please feel free to reopen this issue.
