### ISSUE TITLE
Failed Install Sentry SDK for Unity

### ISSUE THREAD

**Issue by Humoon** [getsentry/sentry-unity#498]
### Environment

How do you use Sentry?
sentry.io

Platform
Win10 + UnityHub@2.5.6 + Unity@2020.3.23f1c1

### Steps to Reproduce
1. Copy ```git@github.com:getsentry/sentry-unity.git``` or ```https://github.com/getsentry/unity.git#0.9.1``` from github,
2. Install Sentry Unity SDK using Unity Package Mananger with above URL, and got failed.

### Expected Result
Installed Successfully.

### Actual Result
[Package Manager Window] Error adding package: git@github.com:getsentry/sentry-unity.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

![image](https://user-images.githubusercontent.com/9549462/147206307-b90b3f0e-9ed2-462e-92d0-ce57b19c9d0b.png)

**Comment by bitsandfoxes** [comment]
Hey @Humoon. The `getsentry/sentry-unity.git` repository is our working repository and is not a package you can add to Unity.
But `https://github.com/getsentry/unity.git#0.9.1` should work. There is an issue with the package manager not dealing with trailing whitespace. Could you try adding it again? 
![image](https://user-images.githubusercontent.com/25725783/147222086-fdde542a-6b05-4bbc-9866-cdcfbd8e30a8.png)

**Comment by Humoon** [comment]
I have try ```https://github.com/getsentry/unity.git#0.9.1``` for several times without trailing whitespace, and got similar errors. 
![image](https://user-images.githubusercontent.com/9549462/147225878-949f6e36-9ace-4359-a514-f39a8313a2f7.png)

Can you try this installation for a new project. Thanks a lot !

**Comment by bitsandfoxes** [comment]
`OpenSSL SSL_read: Connection was reset` sounds a lot like Unity package manager network issues to me. I can refer you to the Package Manager network issue [docs](https://docs.unity3d.com/Manual/upm-config-network.html) and maybe this [forum post](https://forum.unity.com/threads/read-me-first-troubleshooting-connection-loading-project-issues-with-package-manager.869683/).
Alternatively, you could download the package, unzip it and instead of `Add package from git URL` you could `Install from disc`.

**Comment by SimonCropp** [comment]
> Could you try this installation for a new project. Thanks a lot !

@Humoon i tried this with two installs (2020.3.25f1 and 2019.4.33f1) and both worked. 

 * could you try with 2020.3.25f1 ?
 * Do other packages successfully install from git?
 * have you raised a bug with unity?

**Comment by Humoon** [comment]
> `OpenSSL SSL_read: Connection was reset` sounds a lot like Unity package manager network issues to me. I can refer you to the Package Manager network issue [docs](https://docs.unity3d.com/Manual/upm-config-network.html) and maybe this [forum post](https://forum.unity.com/threads/read-me-first-troubleshooting-connection-loading-project-issues-with-package-manager.869683/). Alternatively, you could download the package, unzip it and instead of `Add package from git URL` you could `Install from disc`.


Thanks for your reply, it is really helpful. I have successfully installed the sentry unity package by ```Install from disc```！

**Comment by Humoon** [comment]
> 



> > `OpenSSL SSL_read: Connection was reset` sounds a lot like Unity package manager network issues to me. I can refer you to the Package Manager network issue [docs](https://docs.unity3d.com/Manual/upm-config-network.html) and maybe this [forum post](https://forum.unity.com/threads/read-me-first-troubleshooting-connection-loading-project-issues-with-package-manager.869683/). Alternatively, you could download the package, unzip it and instead of `Add package from git URL` you could `Install from disc`.
> 
> Thanks for your reply, it is really helpful. I have successfully installed the sentry unity package by `Install from disc`！

I really appreciate your suggestions,
1. Yes, I tried to change the unity version, but the 2020.3.25f1 is not compatible with my project, but above error always appears, I think it may be a network problem. I have successfully installed sentry unity from disk.
2. Yes, I have successfully installed the sentry-unity-lite version from git.

**Comment by Humoon** [comment]
> > Could you try this installation for a new project. Thanks a lot !
> 
> @Humoon i tried this with two installs (2020.3.25f1 and 2019.4.33f1) and both worked.
> 
> * could you try with 2020.3.25f1 ?
> * Do other packages successfully install from git?
> * have you raised a bug with unity?

I really appreciate your suggestions,
1. Yes, I tried to change the unity version, but the 2020.3.25f1 is not compatible with my project, but above error always appears, I think it may be a network problem. I have successfully installed sentry unity from disk.
2. Yes, I have successfully installed the sentry-unity-lite version from git.
