### ISSUE TITLE
Add time option for log, error, warning debouncers

### ISSUE THREAD

**Issue by oddgames-david** [getsentry/sentry-unity#501]
With unity it's very common for the first exception to be only one that truly needs fixing and a debounce time of 1 second doesn't really cut it, I'd use a 30 second timer so my sentry review box doesn't fill up with stuff I really don't need to see.

**Comment by bruno-garcia** [comment]
The debouncing strategy is something we can improve. Just based on time is also not good enough as it often drops legit events. There has been some other issues discussing this but we should bring this topic back to improve this feature going forward

**Comment by bitsandfoxes** [comment]
Superseded by https://github.com/getsentry/sentry-unity/issues/379
