### ISSUE TITLE
Improve folder structure for dev flow

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#52]
* Create a new folder `package-dev` and output the result from `src` into it
* Configure `.gitignore`
* `/samples/unity-of-bugs` change reference from `package` to `package-dev`
* README.md?

**Comment by bruno-garcia** [comment]
We can also surface the sample project in the package itself:

**Comment by semuserable** [comment]
> We can also surface the sample project in the package itself:
> https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/

From my perspective this is not related to `dev` flow, but more for `release` flow.
I'll try to check the possibilities.

**Comment by semuserable** [comment]
@bruno-garcia just checked. We can add `unity-of-bugs` project into `Samples~` folder for `package`.

![image](https://user-images.githubusercontent.com/2175097/107508523-d1e4a600-6ba9-11eb-9ba1-10837239c2e1.png)

Do you want me to proceed with that?

**Comment by bruno-garcia** [comment]
@semuserable can we use a symlink maybe? It's nice within the `src` for now.
