### ISSUE TITLE
Stacktrace does not match Unity log when switching from 'Script Only' to 'Full'

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#522]
Came from: https://discord.com/channels/621778831602221064/621783582628642822/930258591452123147

1. Create new Unity 3D project with Unity 2021.2.4f1.
2. Import Sentry Unity 0.9.2 package via Git URL.
3. Add High Definition RP through Unity Package Manager.
4. Duplicate "Directional Light" once in the default "SampleScene" so that there are now two.
5. For unrelated reasons, be forced to restart Unity once or twice and have it crash on you twice. (this happened to me, your mileage may vary)
6. Set a valid DSN in Sentry options window.
7. Go to "Player Settings" and in the "Stack Trace" options checkboxes, switch it from "ScriptOnly" to "Full" for errors and exceptions.
8. Run the game in editor and see the  "Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time" error in Console output.
9. View this issue in Sentry dashboard, and see that the call stack only has the addresses, but the callstack seen in the editor's console output had much more information. 

[unity-error-sentry-repro (1).zip](https://github.com/getsentry/sentry-unity/files/7891672/unity-error-sentry-repro.1.zip)

**Comment by bitsandfoxes** [comment]
Some context information:
When switching to 'Full' Unity provides additional string as stacktrace that we do not yet support by parsing.
 
![Screenshot 2022-01-18 at 20 37 41](https://user-images.githubusercontent.com/25725783/150006615-8b59e9e3-5776-47c1-8184-979355aa3797.png)

```
Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
 #4  (Mono JIT Code) [LightLoop.cs:1612] UnityEngine.Rendering.HighDefinition.HDRenderPipeline:PrepareGPULightdata (UnityEngine.Rendering.CommandBuffer,UnityEngine.Rendering.HighDefinition.HDCamera,UnityEngine.Rendering.CullingResults)
 #5  (Mono JIT Code) [LightLoop.cs:1878] UnityEngine.Rendering.HighDefinition.HDRenderPipeline:PrepareLightsForGPU (UnityEngine.Rendering.CommandBuffer,UnityEngine.Rendering.HighDefinition.HDCamera,UnityEngine.Rendering.CullingResults,UnityEngine.Rendering.HighDefinition.HDProbeCullingResults,UnityEngine.Rendering.HighDefinition.LocalVolumetricFogList,UnityEngine.Rendering.HighDefinition.DebugDisplaySettings,UnityEngine.Rendering.HighDefinition.AOVRequestData)
 #6  (Mono JIT Code) [HDRenderPipeline.cs:2046] UnityEngine.Rendering.HighDefinition.HDRenderPipeline:ExecuteRenderRequest (UnityEngine.Rendering.HighDefinition.HDRenderPipeline/RenderRequest,UnityEngine.Rendering.ScriptableRenderContext,UnityEngine.Rendering.CommandBuffer,UnityEngine.Rendering.HighDefinition.AOVRequestData)
 #7  (Mono JIT Code) [HDRenderPipeline.cs:1856] UnityEngine.Rendering.HighDefinition.HDRenderPipeline:Render (UnityEngine.Rendering.ScriptableRenderContext,System.Collections.Generic.List`1<UnityEngine.Camera>)
 #8  (Mono JIT Code) [RenderPipeline.cs:52] UnityEngine.Rendering.RenderPipeline:InternalRender (UnityEngine.Rendering.ScriptableRenderContext,System.Collections.Generic.List`1<UnityEngine.Camera>)
 #9  (Mono JIT Code) [RenderPipelineManager.cs:115] UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset,intptr,System.Collections.Generic.List`1<UnityEngine.Camera/RenderRequest>,Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle)
 #10  (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr_object_AtomicSafetyHandle (object,intptr,intptr,intptr)
 #11 mono_jit_runtime_invoke
 #12 do_runtime_invoke
 #13 mono_runtime_invoke
 #14 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
 #15 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
 #16 ScriptableRenderContext::ExtractAndExecuteRenderPipeline(dynamic_array<Camera*, 0ul> const&, void (*)(SceneNode const*, AABB const*, IndexList&, SceneCullingParameters const*), void*, ScriptingObjectPtr)
 #17 Camera::ExecuteCustomRenderPipeline(Camera::EditorDrawingMode, DrawGridParameters const*, Camera::RenderFlag)
 #18 Camera::RenderEditorCamera(Camera::EditorDrawingMode, DrawGridParameters const*, CullResults*, Camera::RenderFlag, int, bool, bool, core::hash_set<GameObject*, core::hash<GameObject*>, std::__1::equal_to<GameObject*> >*)
 #19 Camera::RenderEditorCamera(Camera::EditorDrawingMode, DrawGridParameters const*, bool, bool, core::hash_set<GameObject*, core::hash<GameObject*>, std::__1::equal_to<GameObject*> >*)
 #20 Handles_CUSTOM_Internal_DrawCameraWithGrid(ScriptingBackendNativeObjectPtrOpaque*, Camera::EditorDrawingMode, DrawGridParameters&, unsigned char, unsigned char)
 #21  (Mono JIT Code) (wrapper managed-to-native) UnityEditor.Handles:Internal_DrawCameraWithGrid (UnityEngine.Camera,UnityEditor.DrawCameraMode,UnityEditor.DrawGridParameters&,bool,bool)
```

**Comment by bruno-garcia** [comment]
Mono isn't the main use case but on IL2CPP I'm curious what these would look like.
That said, makes sense to improve parsing so that we show all frames with the most data relevant.

We have some unit tests for the current parsing code:
https://github.com/getsentry/sentry-unity/blob/c82d676e47bded44b2d747129e3c7ab47aa75369/test/Sentry.Unity.Tests/UnityLogExceptionTests.cs#L11

Code for parsing this is here: https://github.com/getsentry/sentry-unity/blob/main/src/Sentry.Unity/UnityLogException.cs
This is a good first issue for someone who wants to contribute to the SDK, we're happy to help review the PR

**Comment by lucas-zimerman** [comment]
For reference:
https://github.com/getsentry/sentry-xamarin/blob/c227f665574033195c1a00116ff7a8020cbd13b3/Src/Sentry.Xamarin/Internals/NativeExceptionProcessor.ios.cs#L19-L25
