### ISSUE TITLE
Move gson to External Dependency Manager

### ISSUE THREAD

**Issue by oddgames-david** [getsentry/sentry-unity#523]
* What went wrong:
Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.gson.DefaultDateTypeAdapter found in modules jetified-gson-2.8.5.jar (gson-2.8.5.jar) and jetified-gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
  Duplicate class com.google.gson.ExclusionStrategy found in modules jetified-gson-2.8.5.jar (gson-2.8.5.jar) and jetified-gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
  Duplicate class com.google.gson.FieldAttributes found in modules jetified-gson-2.8.5.jar (gson-2.8.5.jar) and jetified-gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
  Duplicate class com.google.gson.FieldNamingPolicy found in modules jetified-gson-2.8.5.jar (gson-2.8.5.jar) and jetified-gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
  Duplicate class com.google.gson.FieldNamingPolicy$1 found in modules jetified-gson-2.8.5.jar (gson-2.8.5.jar) and jetified-gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)

**Comment by bruno-garcia** [comment]
Our latest android sdk (v6.0) doesn't depend on Gson anymore so it'll resolve this issue but it's still in preview. Until we ship a Unity sdk that includes the new android sdk, the work around would be to repack the sentry sdk without the Gson dependency so it picks the one from the other upm package you're using which brings Gson.

Worth noting that Gson 2.8.6 could have issues (https://github.com/google/gson/issues/1597) if you're using Android Gradle Plugin on a version lower than 3.5.3. 
Unity documents which version of Gradle it uses, but not of AGP it seems: https://docs.unity3d.com/Manual/android-gradle-overview.html
