### ISSUE TITLE
Unity logged exceptions should be marked as `unhandled` by default

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#532]
It seems not to be possible to distinguish between a user calling `Debug.LogException` and an unhandled exception we capture through the Unity logging integration. Because of that, we've historically didn't mark any of those as Unhandled. The product a lot of distinctions between those, giving more emphasis to unhandled exceptions, as they have more user impact.

We should turn any exception logged through `Debug.LogException` into `unhandled` and document that users should use `SentrySdk.CaptureException` instead.

Remove any usage of `Debug.LogException` from the docs. Other than in `Troubleshooting` docs where we can explain the difference between calling either API and handled/unhandled exceptions.

**Comment by ripperdoc** [comment]
This also seems to apply to LogError, so that any LogError shows up as unhandled. Is that expected too?

**Comment by bitsandfoxes** [comment]
Yes, we treat the Unity logTypes `Error`, `Exception`, and `Assert`as equal in this case and mark the resulting event as `unhandled`.

> This also seems to apply to LogError, so that any LogError shows up as unhandled. Is that expected too?

**Comment by bitsandfoxes** [comment]
Yes, we treat the Unity logTypes `Error`, `Exception`, and `Assert`as equal in this case and mark the resulting event as `unhandled`.

**Comment by bitsandfoxes** [comment]
Yes, we treat the Unity logTypes `Error`, `Exception`, and `Assert`as equal in this case and mark the resulting event as `unhandled`.

> This also seems to apply to LogError, so that any LogError shows up as unhandled. Is that expected too?

**Comment by bitsandfoxes** [comment]
> This also seems to apply to LogError, so that any LogError shows up as unhandled. Is that expected too?

Yes, we treat the Unity logTypes `Error`, `Exception`, and `Assert`as equal in this case and mark the resulting event as `unhandled`.

**Comment by bitsandfoxes** [comment]
Yes, we treat the Unity logTypes `Error`, `Exception`, and `Assert`as equal in this case and mark the resulting event as `unhandled`.

**Comment by oddgames-david** [comment]
This is backwards to all other bug capture sdk's I've used. If you are logging it you have handled it and it's just for informational purposes. Anything that is thrown and not caught is unhandled.

**Comment by bruno-garcia** [comment]
What's the strategy used by the sdks to mark something as unhandled?
