### ISSUE TITLE
Define testing strategy\structure

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#54]
We need to have a testing suite for Unity Sentry package.

* check Unity instruments for testing - [Unity Test Framework](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/index.html)
* add tests to the package\project - [Adding tests to a package](https://docs.unity3d.com/Manual/cus-tests.html)

**Comment by Tyrrrz** [comment]
I have briefly looked at it, so I might be missing something. Do you think this approach is sound?

1. Create a test scene in `Sentry.Unity.Tests` that contains a single button that throws exception on click
2. Instrument it via UTF like so:

```csharp
[UnityTest]
 public IEnumerator SetupButtonTestSetupButton()
 {
     yield return PlayModeSetup();
     yield return null;
     var button = GameObject.Find("TheButton");
     button.onClick.Invoke();
}
```

3. Run UTF tests from command line like so ([reference](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-command-line.html)):

```
Unity.exe -runTests -batchmode -projectPath PATH_TO_YOUR_PROJECT -testResults C:\temp\results.xml -testPlatform PS4
```

4. On CI, use https://github.com/marketplace/actions/unity-test-runner to run the tests

**Comment by Tyrrrz** [comment]
There is also [AltUnity](https://altom.gitlab.io/altunity/altunitytester/) that allows you to instrument UI tests on top of Unity, which might actually be easier than running tests as part of the game.

**Comment by semuserable** [comment]
@bruno-garcia can we close this one? Seems no longer relevant as we merged both `Runtime` and `Editor` examples.

**Comment by bruno-garcia** [comment]
@semuserable feel free to close issues you believe are done.
