### ISSUE TITLE
Android symbols fail to be uploaded to Sentry.io

### ISSUE THREAD

**Issue by jzapdot** [getsentry/sentry-unity#553]
### Environment

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which version of the SDK?**
`0.9.4`

**Which version of Unity?**
Unity `2020.3.10f1`

**Is this happening in Unity (editor) or on a player like Android, iOS, Windows?**
Building for Android in the Editor

### Steps to Reproduce

1. Attempt to build for Android with Sentry disabled (we enable this in code so we can set additional args) and Upload Dev Symbols enabled.

### Expected Result

**What you thought would happen.**

Build symbols are uploaded successfully and build succeeds.

### Actual Result

**What actually happened. Maybe a screenshot/recording? Maybe some logs?**

Android build gets to the point of packaging and fails on uploading dev symbols for Android to Sentry. **NOTE:** If I disable the Upload Dev Symbols step the build completes successfully and works correctly on device.

```
* What went wrong:
Execution failed for task ':launcher:assembleRelease'.
> Process 'command 'D:/Bitbucket/popcorn2/Unity/Library/PackageCache/io.sentry.unity@4f0f2e13c5/Editor/sentry-cli/sentry-cli-Windows-x86_64.exe'' finished with non-zero exit value 1
```

### Any logs or screenshots

Relevant Editor log contents are here.
[EditorLog.txt](https://github.com/getsentry/sentry-unity/files/8028002/EditorLog.txt)

**Comment by bruno-garcia** [comment]
The problem was caused due to mismatching casing in the project name. Sentry project names are case sensitive so the case in the Editor window must match the case in Sentry itself

![image](https://user-images.githubusercontent.com/1633368/153236399-40712a2e-d147-4e91-a949-18df6c380e08.png)
