### ISSUE TITLE
Set env var `SENTRY_LOG_LEVEL=` matching the diagnostic level

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#554]
`SENTRY_LOG_LEVEL=` is used by the CLI to give more information on issues and it's needed to diagnosing some issues.
Set the env var before invoking sentry-cli

For context: https://github.com/getsentry/sentry-unity/issues/553

**Comment by vaind** [comment]
I've actually tried this (independent of this issue) when working on the Windows symbol upload and the slight problem with this is that the INFO logs coming from the sentry-cli seem to be printed to stderr for some reason. At least that's how it behaved while capturing the stderr & stdout when the process was launched from c#. 

https://github.com/getsentry/sentry-unity/pull/607/files#diff-33dd65bbdffe8c1099e276c49804112fa0c7cba38eeec03787b7112b583f17cbR116

**Comment by vaind** [comment]
https://github.com/getsentry/sentry-cli/issues/1130

**Comment by bitsandfoxes** [comment]
We're setting the diagnostic loglevel in the `.properties` file instead
https://github.com/getsentry/sentry-unity/blob/1cc3587faac15e980d21185af8bf3d23e94957d2/src/Sentry.Unity.Editor/SentryCli.cs#L32
