### ISSUE TITLE
Frames with namespace `Mono` are marked as InApp=true

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#575]
```
            {
              "function": "Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext",
              "raw_function": "Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext ()",
              "lineno": 0,
              "in_app": true
            },
            {
              "function": "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult",
              "raw_function": "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result)",
              "lineno": 0,
              "in_app": false
            },
```

This is surprising because: https://github.com/getsentry/sentry-dotnet/blob/b5acb724549bf201f8fa8d13da165a47e35b4b86/src/Sentry/SentryOptions.cs#L615

**Comment by lucas-zimerman** [comment]
> 

Not exactly, the error was captured using unity and not the .NET SDK
by calling Debug.LogError you'll skip the StackTrace factory and instead use the this
https://github.com/getsentry/sentry-unity/blob/1b7470daef9cf28a16871178c276b5e2095d3574/src/Sentry.Unity/UnityLogException.cs#L125-L127

**Comment by lucas-zimerman** [comment]
Waiting for a new release containing https://github.com/getsentry/sentry-dotnet/pull/1493 to conclude this task in Unity.
