### ISSUE TITLE
LogException is not splitting Inner exceptions

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-unity#579]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which version of the SDK? Unity (Mono - Android)

Which version of Unity? 2019.4.34f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Tested on Android

### Steps to Reproduce

Run sample code below and you'll notice something like 
![image](https://user-images.githubusercontent.com/8229322/155212719-8adab46d-d3d4-4a29-a693-a3bd5a9803ac.png)

### Expected Result

A StackTrace similar to the one captured by CaptureException.

### Actual Result

Event captured by LogException
https://sentry.io/organizations/sentry-sdks/issues/3037507922/?query=is%3Aunresolved&statsPeriod=1h

Event captured by CaptureException
https://sentry.io/organizations/sentry-sdks/issues/3037473558/?_allp=1&query=is%3Aunresolved&statsPeriod=1h

### Any logs or screenshots
Sample code
```csharp
        try
        {
            Task.Run(async () =>
            {
                var  client = new HttpClient();
                (await client.GetAsync("https://expired.badssl.com/")).EnsureSuccessStatusCode();
            }).Wait();
            
        }
        catch (Exception e)
        {
            Debug.LogException(e, this);
//          VS            
            SentrySdk.CaptureException(e);
        }
```

**Comment by bruno-garcia** [comment]
This will be addressed when we change from the application logger (that parses a string) to the Unity logger that gives us an exception instance.
