### ISSUE TITLE
Align the default `user-id` between the C# and native layers

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#606]
SDKs usually have some default 'installation-id' as a User. When capturing from C# and Native those don't match.

Relates to: https://github.com/getsentry/sentry-cocoa/issues/1554

**Comment by bruno-garcia** [comment]
@marandaneto is there a way to get the default/built-in installation-id from Android?
Do we align those already between Java/NDK layers?

**Comment by marandaneto** [comment]
NDK events don't set the user id, so the Android layer does it, you can get it via `Installation.id(context)`, but it's package-private, if you need to access it, we need to make it public.
iOS just changed that and it has to be fixed on Flutter and React Native https://github.com/getsentry/sentry-cocoa/pull/1680
