### ISSUE TITLE
The app code defines a custom `HostnameVerifier` that does not perform any validation of the server's hostname

### ISSUE THREAD

**Issue by mikson60** [getsentry/sentry-unity#613]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Sentry SaaS

Which version of the SDK?
0.8.0

Which version of Unity?
2021.1.28f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Built an APK with Sentry included.
2. Uploaded to the Oculus release channel

### Expected Result

The automatic test results will be a success

### Actual Result

Received a warning:
"The app code defines a custom `HostnameVerifier` that does not perform any validation of the server's hostname: As a result, connections using this `HostnameVerifier` will accept any certificate signed by a valid certificate authority (CA), from any hostname, as valid."

### Any logs or screenshots
I'm attaching a screen shot after analyzing the apk. I found out that Sentry is using the HostnameVerifier class.
![hostnameVerifier](https://user-images.githubusercontent.com/10653357/156779626-68ef6e49-2013-4f01-a8fd-1bbed9b1a1f7.png)

**Comment by bruno-garcia** [comment]
This raised a few times in the past but in short: It's a *false positive*. Particularly in the Unity SDK since we don't expose the `bypassSecurity` option.

More context: https://github.com/getsentry/sentry-java/issues/840 and https://github.com/getsentry/sentry-java/issues/861

**Comment by bruno-garcia** [comment]
Actually `bypassSecurity` is gone. I don't see where in the code base we are setting a hostname verifier at all. It's just an option users can set.
