### ISSUE TITLE
Tag whether event was created in the UI thread

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#62]
We should add a tag that indicates whether the event was raised from the UI thread or not

**Comment by philipphofmann** [comment]
I'm not sure if a tag is the way to add this type of information, but I agree that Sentry should clearly display if the event was created in the UI thread or not.

**Comment by oddgames-david** [comment]
Does this work?
```
        static SynchronizationContext unitySynchronizationContext;

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Setup()
        {

            if (unitySynchronizationContext == null)
                unitySynchronizationContext = SynchronizationContext.Current;

            tcs.TrySignal();
        }

        public static bool IsRunningOnUnityThread => SynchronizationContext.Current == unitySynchronizationContext;

```

**Comment by bruno-garcia** [comment]
Internally we have an API for this:

https://github.com/getsentry/sentry-unity/blob/e5a6649c2c3d9e4df8018dd4db94c81d3c4be99b/src/Sentry.Unity/MainThreadData.cs#L68-L69
