### ISSUE TITLE
Expose BeforeSend on native layers

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#620]
The goal is to avoid users from taking the "Manual Init" approach so we can rely on the options at build time

**Comment by bruno-garcia** [comment]
Removed the `Platform: Android` so it doesn't show up on the Android SDK boards since nothing they can do about this.
I realize we have a few extra issues that have the platform label as a way to reference "Relates to Android" but it has that side effect

**Comment by vaind** [comment]
Duplicate of #609
