### ISSUE TITLE
Windows Native: Add call to sentry_init in the main function at compile time

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#628]
Follow up from #527

The Native SDK is currently initialized via C# (after the Unity C# layer runs). It works well to capture crashes after the game boots properly. The one downside is that we don't capture crashes of the engine bootstrapping itself. Our docs are written to indicate it works this way because we built it like that for Android and iOS.

Until this task is completed we need to update the docs to mention the early crash detection is for mobile only.

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-unity/issues/527#issuecomment-1064117119

**Comment by bruno-garcia** [comment]
PR tackling #622

**Comment by vaind** [comment]
This is on hold now, @bitsandfoxes can you please add a comment with details/status and move to "blocked" or "backlog" in the project? We may also need to update the priority

**Comment by bitsandfoxes** [comment]
We've got a draft exploring how we'd make it work https://github.com/getsentry/sentry-unity/pull/622
Unity ships with pre-built playback engines but provides the source code. The idea is to add Sentry Native to the playback engine and build it ourselves. Why we're currently not going forward with this: The draft relies on finding the correct package to locate `vswhere` to locate `msbuild` and there is a whole lot of uncertainty and risk with this approach.

Maybe we could do it like Unity and ship with pre-built playback engines and provide the source for signing?

**Comment by bitsandfoxes** [comment]
For context we're introducing and defaulting to having the managed layer initialize the native one in
- https://github.com/getsentry/sentry-unity/pull/1915
- https://github.com/getsentry/sentry-unity/pull/1924

as this kept coming up no matter how much documentation we put in front of people and it is the much more intuitive approach. We're keeping the native-init first as an opt-in tho.

**Comment by bruno-garcia** [comment]
We're taking the inverse route where we init native from C# on mobile now. So it's unlikely we'll get to this anytime soon. So closing.

Draft of this approach is here if anyone wants to take on
* https://github.com/getsentry/sentry-unity/pull/622
