### ISSUE TITLE
Bundle `sentry.pdb` in the UPM package and upload with game debug symbols

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#634]
https://github.com/getsentry/unity/tree/main/Plugins/Windows/Sentry

Events captured with sentry-native are failing with:

![image](https://user-images.githubusercontent.com/1633368/157913947-388f19c1-34dd-44f5-907d-3d2333e6f0f4.png)

**Comment by vaind** [comment]
FYI: https://github.com/getsentry/sentry-unity/blob/13650d30c4c945fded60853ff762ee6049808713/src/Sentry.Unity.Editor/Native/BuildPostProcess.cs#L97-L98

there's no debug info (sentry-cli doesn't upload anything for the file

**Comment by bruno-garcia** [comment]
Do we generate a `.pdb` when we compile sentry-native? We could just bundle that in the UPM package

**Comment by bruno-garcia** [comment]
Maybe @Swatinem has thoughts

**Comment by vaind** [comment]
AFAIK we need to build RelWithDebInfo, i'll have a look

**Comment by vaind** [comment]
Result: building as RelWithDebInfo and uploading the DLL fixes the issue. I've also added the .pdb for good measure but it doesn't seem to provide any further info in the testing errors we use.
