### ISSUE TITLE
Compression level for IL2CPP builds

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#647]
With the options configuration, more users will run into the issue of setting [compression levels](https://github.com/getsentry/sentry-unity/blob/271d080ef2c68b8c2e22e297924cb63963bacc2f/src/Sentry.Unity/SentryUnityOptions.cs#L52) that are unsupported on IL2CPP and lead to the SDK silently failing to send events.

We could warn during build time or simply set the compression ourselves.

**Comment by bruno-garcia** [comment]
Maybe best hiding it altogether with the old hack?
```
internal new CompressionLevel Level {get;set;}
```
ppl can still cast to to the base SentryOptions and access it but they'd be getting out of their way to do it.

**Comment by bitsandfoxes** [comment]
This needs a bit of investigation to see if it's an issue on all platforms so that we might raise an issue with Unity.
A nice repro would be to simply compress something with Gzip.

**Comment by bruno-garcia** [comment]
Things seem to be working OK wrt compression. Feel free to reopen otherwise
