### ISSUE TITLE
Build input file cannot be found in XCode when targetting iOS / IL2CPP

### ISSUE THREAD

**Issue by maeln** [getsentry/sentry-unity#649]
### Environment

1. We use sentry SaaS on sentry.io.
2. Unity version is 2020.3.26f1
3. Sentry Unity SDK is version 0.12.0
4. Compilation target is: iOS + IL2CPP

The bug is appearing when compiling the build in XCode.

### Steps to Reproduce

1. Updated the SDK from version 0.9.1
2. Deleted the current iOS build
3. Reboot Unity 
4. Build the application
5. When Unity is finished building, XCode opens and start to compile the Unity build
6. The build fail with the following error:

```
Build input file cannot be found: '/Users/maeln/UnityApp/ClawMaster/Builds/ios/Libraries/io.sentry.unity/Plugins/iOS/SentryNativeBridge.m'
```

### Expected Result

The XCode build would finish without error.

### Actual Result

The build fail with the following error:

```
Build input file cannot be found: '/Users/maeln/UnityApp/ClawMaster/Builds/ios/Libraries/io.sentry.unity/Plugins/iOS/SentryNativeBridge.m'
```
There is no other log.

The file exist but not at the same path. The actual path is:
```
➜  io.sentry.unity git:(master) ✗ pwd
/Users/maeln/UnityApp/ClawMaster/Builds/ios/Libraries/io.sentry.unity
➜  io.sentry.unity git:(master) ✗ ls
SentryNativeBridge.m
```

I will try to downgrade one version at a time to pinpoint where this started happening.

Faithfully yours,

**Comment by maeln** [comment]
Update: I downgraded to the Sentry SDK version `0.11.0` and the bug doesn't appear.

**Comment by vaind** [comment]
From a quick look, looks like an issue with the .meta file: 
https://github.com/getsentry/unity/commit/2ec0745194dd3a73bddd6c7da9b38ed83ac2b4be#diff-8857af0fc9d09d1bf0a1030b4522a55d5b0f6d9b5f64bc8f848f911fd1554fe8R14-R31

**Comment by vaind** [comment]
@bitsandfoxes may know how to best fix this

**Comment by bitsandfoxes** [comment]
> From a quick look, looks like an issue with the .meta file: https://github.com/getsentry/unity/blob/2ec0745194dd3a73bddd6c7da9b38ed83ac2b4be/Plugins/iOS/SentryNativeBridge.m.meta#L25

That is actually on purpose. If it were enabled in the meta file then Unity would copy it over to the Xcode project even when Sentry is disabled, breaking the build.

It looks to me like Xcode is still looking for the NativeBridge at the old location (where we did let Unity copy it over for us). 
So something seems to be out of sync. I know you state that you deleted the previous build but your you delete the entire Xcode project and try again with 0.12.0?

The path where it actually is does seem correct: https://github.com/getsentry/sentry-unity/blob/7b31ebff8473d3e387c3b1f7d131bf21e2142a37/src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs#L31
And the same path is used to add it to the project: https://github.com/getsentry/sentry-unity/blob/7b31ebff8473d3e387c3b1f7d131bf21e2142a37/src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs#L132

**Comment by maeln** [comment]
Sorry, I have been stuck with another issue for days now and I had no time to look into this one.

> I know you state that you deleted the previous build but could you try deleting the entire Xcode project and try again with 0.12.0?

As mentioned, it is more or less what I did since the "build" is actually the XCode project, but I will try to do it again once I get some free time.

**Comment by bitsandfoxes** [comment]
Hey, I'm closing this since I believe the clean build will resolve this issue. Please feel free to reopen if this issue persists for you.
