### ISSUE TITLE
Add a clear path to opt-out of the SentryWindow approach to manual initialization

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#66]
For advanced scenarios folks will want to init the SDK programatically.

To support such scenarios, we need to include a clear:

```csharp
var options = new SentryUnityOptions();
SentryUnity.Init(options);
```

The [code done initializing](https://github.com/getsentry/sentry-unity/blob/main/src/Sentry.Unity/SentryInitialization.cs#L60) today was good enough for using SentryWindow. We need to pull out into `SentryUnity` to become the API used by customers when they opt-out from the `SentryWindow` and get access to the complete .NET API/options

This means our auto init should also go through such API.

**edit by semuserable:** we need to force `link.xml` to be created if user decides to use programmatic approach. Current approach is to copy it from `Packages/<sentry-plugin-folder>/Runtime/link.xml` into `Assets/Resources/Sentry/link.xml`. Check https://github.com/getsentry/sentry-unity/issues/84.

The approach is taken by Xamarin:
https://github.com/getsentry/sentry-xamarin/blob/63e764393415324f7fa0356e62d679d64f8d34ff/Src/Sentry.Xamarin/SentryXamarin.cs#L32-L42

**Comment by semuserable** [comment]
I guess that basically means to move out the current logic from `SentryInitialization.Init` into a separate class and "make it more composable"?

**Comment by bruno-garcia** [comment]
Yes. The Editor window configuration can have a toggle to turn off auto init (I believe I already added one) and we can document the user how they can initialize programatically.

We need to consider: Does that mean all the configuration set via the SentryWindow doesn't apply?
Does Unity provide some sort of hook for us to invoke a user-defined method passing our `SentryUnityOptions` instance as an argument? Similar to a Spring Bean, a service locator or some IoC container we can resolve stuff from?

**Comment by semuserable** [comment]
Started looking into it. I have a question. What is the proper way of disposing of `SentrySdk`? Can I rely on `SentrySdk.Init()` `IDisposable` or use `SentrySdk.Close()`?

Looking at the approach of replacing one `SentrySdk` with another. What is the recommended way?

**Comment by bruno-garcia** [comment]
> Started looking into it. I have a question. What is the proper way of disposing of `SentrySdk`? Can I rely on `SentrySdk.Init()` `IDisposable` or use `SentrySdk.Close()`?
> 
> Looking at the approach of replacing one `SentrySdk` with another. What is the recommended way?

`SentrySdk.Close()` will close the current `Hub` reference held inside which is fine if you make sure you call `SentrySdk.Init`. To make sure you close the the `Hub` referent to the `Init` call **you** made, you should hold a reference to the returned Disposable. This would only make a difference if for some reason Init is called more than once (in aspnetcore it is for example since it's initialized via the DI container and 2 containers are created during a normal app start.

In hindsight I regret having the two approaches. Having a `defer Sentry.Init();` was the main goal to return the `IDisposable` but ultimately the `Close()` method was a convinience that came in handy in some other uses cases where the reference wasn't easily passed around to the point the SDK should be shut down.

**Comment by semuserable** [comment]
closed by https://github.com/getsentry/sentry-unity/pull/130
