### ISSUE TITLE
No way to attach files when error/exception is triggered

### ISSUE THREAD

**Issue by pistoleta** [getsentry/sentry-unity#663]
Since the BeforeSend method can't be made async and the SentrySdk.ConfigureScope call works with a callback is not possible to add files in that precise moment, such as, for example a screenshot to know what the player was doing exactly when the error happened... 
Also, since the SentryEvent class does not allow to add attachments I dont see anyway to achieve that.. Am I missing something? 

Either there must exist a way to attach files to already sent events or the way of doing this is to attach the file in the context when the file does not exist and create it inside the BeforeSend method.

**Comment by vaind** [comment]
For dotnet, the tracking issue is https://github.com/getsentry/sentry-dotnet/issues/1469

For native, we currently don't support any `beforeSend` configuration, see https://github.com/getsentry/sentry-unity/issues/609

**Comment by pistoleta** [comment]
> For dotnet, the tracking issue is [getsentry/sentry-dotnet#1469](https://github.com/getsentry/sentry-dotnet/issues/1469)
> 
> For native, we currently don't support any `beforeSend` configuration, see #609

You're telling me sentry hasn't  the capability to send screenshot to know what was the player doing when the error occurred? no way? 😮

**Comment by vaind** [comment]
And specifically for screenshots (if that's what this was all about), there's this issue: #284

**Comment by vaind** [comment]
Closing this in favor of the [dotnet issue (generic attachments)](https://github.com/getsentry/sentry-dotnet/issues/1469) & the screenshots attachment issue mentioned above.
