### ISSUE TITLE
Modifying the SentryEvent in BeforeSend does not make any change

### ISSUE THREAD

**Issue by pistoleta** [getsentry/sentry-unity#664]
How do you use Sentry?
(sentry.io)

Which version of the SDK? 0.13.1

Which version of Unity? 2020.3.30f1

iOS

Modifying the SentryEvent inside the BeforeSend method adding a couple of tags and setting the the sentryEvent.User doesn't work. 
No tags were added, User not set.

**Comment by vaind** [comment]
> iOS

is the event in question a native crash or a dotnet exception?

**Comment by pistoleta** [comment]
> > iOS
> 
> is the event in question a native crash or a dotnet exception?
> 
> For native crashes, BeforeSend is not called. Are you sure your function is being called, e.g. by printing out some logs you then verified on device?

I tried Debug.LogError and throwing a custom system exception: "throw new Exception("Test exception");"

**Comment by pistoleta** [comment]
> > iOS
> 
> is the event in question a native crash or a dotnet exception?
> 
> For native crashes, BeforeSend is not called. Are you sure your function is being called, e.g. by printing out some logs you then verified on device?

Okay even if its not a native crash, I just realized BeforeSend is not being called.
I've set the SentryUnityInit inside the Awake method and I assign the BeforeSend there, just before I set the scope which is succesfully set.

```
private void Awake()
    {
        var buildCFG =  (BuildConfigSO) Resources.Load("Configuration/BuildConfig", typeof(BuildConfigSO));
        SentryUnity.Init(options =>
        {
            options.Environment = buildCFG.buildType.ToString();
            options.AutoSessionTracking = true; // default: false
            options.SampleRate = 1;
            options.TracesSampleRate = 1;
            options.BeforeSend= BeforeSend;
            options.TracesSampler= TracesSampler;
        });
        
       
        SentrySdk.ConfigureScope(scope =>
        {
            scope.SetTag("IOS", UnityEngine.iOS.Device.systemVersion);
            scope.SetTag("deviceLang", Application.systemLanguage.ToString());
            scope.SetTag("gameLang",  LocalizationManager.CurrentLanguageCode);
            scope.SetTag("buildType",  buildCFG.buildType.ToString());
        });
```

I don't know what I'm doing wrong

**Comment by pistoleta** [comment]
Okay I just realized the configuration has to be done in the SentryOptionsConfiguration script.
Now BeforeSend is being called 👍

**Comment by vaind** [comment]
> Now BeforeSend is being called 👍

Glad to hear you've find the issue. Closing this. Feel free to reopen/follow up in case the issue persists.
