### ISSUE TITLE
Possible making BeforeSend async? 

### ISSUE THREAD

**Issue by pistoleta** [getsentry/sentry-unity#665]
Would be a big deal to add an async overload of the BeforeSend method? I
All the problems regarding attaching files like logs or screenshots to the context would be solved... I guess its not possible but I had to ask. Thanks!

**Comment by vaind** [comment]
I don't think this is an option at the moment. In any case, it would be a better idea to take this to sentry-dotnet. The solution would likely be to add `Hint` as in other SDKs. Let's keep this discussion in the single dotnet issue to have all the info in the single place - https://github.com/getsentry/sentry-dotnet/issues/1469

**Comment by pistoleta** [comment]
> I don't think this is an option at the moment. In any case, it would be a better idea to take this to sentry-dotnet. The solution would likely be to add `Hint` as in other SDKs. Let's keep this discussion in the single dotnet issue to have all the info in the single place - [getsentry/sentry-dotnet#1469](https://github.com/getsentry/sentry-dotnet/issues/1469)

Sorry for the noob question but several times you have pointed me to the sentry-dotnet sdk from unity-sdk issues, but I'm not sure if I understand why... Does tha mean by fixing that in the dotnet-sdk it is solved automatically for unity-sdk?  
Thanks for your help

**Comment by vaind** [comment]
The Unity SDK uses the dotnet SDK internally, just updates some configuration, adds error handlers, context info, etc. So yes, if the feature is required on the dotnet side of things (not native) then and is not strictly unity-specific, then it should be implemented in sentry-dotnet first and after release, we can integrate it in sentry-unity.

Just for completeness, the above is true for .net errors, while for native desktop & mobile errors/crashes there are other sentry SDKs included, e.g. sentry-java, sentry-cocoa, sentry-native.
