### ISSUE TITLE
Align boolean tag values

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#680]
There seem to be multiple boolean value representations, used by different tags. I believe it would be better to only use a single representation, so that filtering is easier for users. What I've seen so far: yes/no, true/false, True/False

<img width="878" alt="image" src="https://user-images.githubusercontent.com/6349682/162784607-6a01f85b-23cc-4d9b-8260-c843ddde4fdd.png">

Also, why is there "handled: no" and "handled: false"?

If we decide to change this, can/should we also update existing data?

**Comment by bitsandfoxes** [comment]
TIL: Boolean.ToString returns a capitalized string. I think we should default our manual strings to whatever it is that ToString for that type would return.
Same for `environment: editor` and `unity.install_mode: Editor`. The environment gets set manually and I think should be capitalized as well.

**Comment by vaind** [comment]
> I think we should default our manual strings to whatever it is that ToString for that type would return.

Not a fan, because that is C# specific, while users may also be using other languages. I'd suggest having a look at other SDKs and use the most common way of representing booleans.
