### ISSUE TITLE
Flaky tests tracker

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#698]
To keep track of them / find commonalities.

Android 29 Unity 2019 - timeout: https://github.com/getsentry/sentry-unity/runs/6128970275?check_suite_focus=true
iOS latest Unity 2019 - timeout: https://github.com/getsentry/sentry-unity/runs/6126636817?check_suite_focus=true

**Comment by bitsandfoxes** [comment]
Android 30 Unity 2021 - timeout: https://github.com/getsentry/sentry-unity/runs/6169488280?check_suite_focus=true

**Comment by bitsandfoxes** [comment]
Android 27 Unity 2019 - **?**: https://github.com/getsentry/sentry-unity/runs/6176502288?check_suite_focus=true
Android 29 Unity 2021 - **?**: https://github.com/getsentry/sentry-unity/runs/6176502795?check_suite_focus=true

**Comment by bitsandfoxes** [comment]
Android 29 Unity 2021 - **smoke test: FAIL**: https://github.com/getsentry/sentry-unity/runs/6192179959?check_suite_focus=true

**Comment by bitsandfoxes** [comment]
iOS 12.4 Unity 21 - timeout: https://github.com/getsentry/sentry-unity/runs/6190565912?check_suite_focus=true

**Comment by bitsandfoxes** [comment]
iOS latest Unity 2021 - timeout: https://github.com/getsentry/sentry-unity/runs/6193857232?check_suite_focus=true
Android 30 Unity 2020 - flakey: https://github.com/getsentry/sentry-unity/runs/6194215455?check_suite_focus=true

**Comment by bruno-garcia** [comment]
For CI: https://docs.sentry.io/platforms/dotnet/configuration/options/#init-cache-flush-timeout

**Comment by vaind** [comment]
these seem pretty stable now, closing the issue.
