### ISSUE TITLE
Stop setting usesCleartextTraffic to true in AndroidManifest.xml

### ISSUE THREAD

**Issue by rthery** [getsentry/sentry-unity#714]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?) 
SaaS

Which version of the SDK?
0.15.0

Which version of Unity?
2020.3.0f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce

1. Build for Android
2. Upload the build to Google Play
3. Note the warning "Cleartext traffic allowed for all domains" in your Pre-launch report in the Google Play Console website

### Expected Result

Sentry package should not set usesCleartextTraffic, ideally it should only communicate via HTTPS. If it can't for some reasons, it should implement its own network_security_config.xml
cf. https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

### Actual Result

Sentry package forces usesCleartextTraffic to true, triggering a security warning on the Google Play Console

### Any logs or screenshots
This is the text of the actual warning:

> Your app's Network Security Configuration allows cleartext traffic for all domains. This could allow eavesdroppers to intercept data sent by your app. If that data is sensitive or user-identifiable it could impact the privacy of your users.
> 
> Consider only permitting encrypted traffic by setting the [cleartextTrafficPermitted](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted) flag to false, or adding an encrypted policy for specific domains.

**Comment by mystikxkemix** [comment]
+1

**Comment by marandaneto** [comment]
@rthery are you using Sentry self-hosted with a non-https DSN? the SDK itself does not do anything special around it.
Why do you need to set the `usesCleartextTraffic` flag at all? can you copy-paste the error message?

**Comment by bitsandfoxes** [comment]
Does this issue persist if you disable `AndroidNativeSupport`in the Config Window?

**Comment by bruno-garcia** [comment]
The only use of it we have is in our sample game:

https://github.com/getsentry/sentry-unity/blob/e273d15d932a0f5682b2d554109542e4c1f71ce0/samples/unity-of-bugs/Assets/Editor/AndroidManifestUpdater.cs#L19

We bundle the sample in the package. Is it possible you loaded our sample scene in your game? I wonder if this would be picked up by Unity and executed on a player build. If so, we'll need to make sure this doesn't end up on the package anymore.

**Comment by bitsandfoxes** [comment]
I checked 0.15.0 and the editor scripts don't make it into the package.
@rthery, are you by any chance building Sentry from source?

**Comment by bitsandfoxes** [comment]
Happy to help and hear it worked out for you @rthery!

> This is another point where I feel we should clearly separate the "sample" code from our smoke tests... I think we should have a separate project for integration tests (smoke-test) & remove anything test related from unity-of-bugs sample, even from this repo, not only from the output package

Agreed https://github.com/getsentry/sentry-unity/issues/637
