### ISSUE TITLE
iOS crash caused by sentry

### ISSUE THREAD

**Issue by pistoleta** [getsentry/sentry-unity#721]
iOS > 15
Unity 2020.3.33
sentry-unity 0.15.0

Got this crash report on Xcode organizer...
[
![](https://i.ibb.co/VC4fqzr/Captura-de-Pantalla-2022-04-30-a-las-12-16-27.png)
](url)

I have not been using Sentry for long (maybe 2 months) but this is the first time I see this kind of crash so maybe is something about the 0.15.0 ?

Full crash log attached:

[2022-04-30_01 SentryCrash.log](https://github.com/getsentry/sentry-unity/files/8596700/2022-04-30_01.SentryCrash.log)

**Comment by bitsandfoxes** [comment]
Hey @pistoleta, would you be able to provide a repro for us? I tried recreating it in a fresh project but was not able to.

**Comment by pistoleta** [comment]
for the moment it has happened just once but we don't have too many testers so it's a bit concerning. I'll let you know more if I find out more.

**Comment by bitsandfoxes** [comment]
I'm hoping this has been resolved 🙏 .
