### ISSUE TITLE
Use upstream setup-unity GHA

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#722]
We're using a forked setup-unity action but the change we have there seems to already be in the upstream action so we can remove the fork and use the original. 
* fork: https://github.com/getsentry/setup-unity/commit/46c2e082d98cc3a825a5b59038cb31705fe9ff56
* upstream: https://github.com/kuler90/setup-unity/commit/f78de78be36656beaebc21da1602381360e2171a

**Comment by bruno-garcia** [comment]
https://github.com/kuler90/setup-unity wasn't updated in 2 years.
[our fork is 22 commits ahead](https://github.com/kuler90/setup-unity/compare/master...getsentry:setup-unity:master)

So closing as we'll stay with our fork
