### ISSUE TITLE
CI: Use Windows Containers in CI when possible

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#739]
We have a 'desktop' step on Windows that installs Unity and it's rather slow.
Ideally we use this image instead: https://hub.docker.com/layers/editor/unityci/editor/windows-2021.3.2f1-windows-il2cpp-1.0.1/images/sha256-f47eb164cb4cd8e1b1f0100975a941a70095ab824ea7d7233dee639b5cba5385?context=explore

**Comment by bitsandfoxes** [comment]
Closing this as it's not relevant anymore. The windows tests do not take any longer than other platforms. Exception being Unity 2019 on Windows.
But we're going to drop 2019 in the near future.
