### ISSUE TITLE
Mono crash report on desktop

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#750]
Currently only IL2CPP backend is supported for native crashes.

native support wasnt added on Mono originally because it broke the ability of Mono to handle certain types of errors and keep running. Since sentry native would create a minidump and the process would terminate

**Comment by vaind** [comment]
> Mono to handle certain types of errors and keep running

Do we have a specific reproduction?

**Comment by lucas-zimerman** [comment]
Oh so there's an opened issue, I just face on a game that I was working on that on mono it wasn't logging the crashes.
