### ISSUE TITLE
App.version missing in .NET & desktop native

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#754]
Native mobile SDKs expose app version (at least Android does, I haven't checked iOS but I assume it has it as well) - we don't have it in .NET events or on desktop crashes (Windows, Linux). They're very useful to track which app releases have the issue.
I was thinking of adding the following [contexts](https://develop.sentry.dev/sdk/event-payloads/contexts/#app-context):
* `App.Version` - https://docs.unity3d.com/ScriptReference/Application-version.html
* `App.Build` - https://docs.unity3d.com/ScriptReference/Application-buildGUID.html

**Comment by bruno-garcia** [comment]
We currently use `Application.version` to create the `Release`:

https://github.com/getsentry/sentry-unity/blob/c8960266ef2973d3e4aa804e967c97bb4323c757/src/Sentry.Unity/SentryUnityOptions.cs#L167-L168

These numbers should match. Perhaps Build is missing? The format `package@version+build` is defined here:

https://docs.sentry.io/platforms/unity/configuration/releases/#bind-the-version

The parts of the release could be added to the context["app"] indeed.

**Comment by bitsandfoxes** [comment]
This has been fixed in https://github.com/getsentry/sentry-unity/pull/795
