### ISSUE TITLE
Add LowMemory notification to breadcrumbs

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-unity#757]
Maybe it would be helpful to diagnose some events if you could see that previously a low-memory notification came (https://docs.unity3d.com/ScriptReference/Application-lowMemory.html). 

* we could add this automatically to breadcrumbs. If we're doing so, we should ensure we only add it once (or once for a given period of time).
* alternatively, we could just remember this in the event processor and set the extra info of the last low-memory event time when an error occurs - this wouldn't work for native though, and that's probably where this is most useful.

**Comment by vaind** [comment]
Let's have a look at how it's done on sentry-cocoa/java (breadcrumb or event)

**Comment by bitsandfoxes** [comment]
Duplicate of https://github.com/getsentry/sentry-unity/issues/93
