### ISSUE TITLE
Basic support for Adventure Creator

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-unity#760]
https://assetstore.unity.com/packages/tools/game-toolkits/adventure-creator-11896
Adventure Creator is a package that helps developers and non developers to create point and click games.

I did a hackweek where I was able to connect their script system with Sentry so it may look something like the below image
![image](https://user-images.githubusercontent.com/8229322/169834678-4ccdb22b-7348-4338-ac77-246615291afc.png)

The idea is to expose some Sentry functionalities and document it on Sentry Docs or on a separated project on Github

**Comment by bitsandfoxes** [comment]
Do you have an idea of what API you'd need to be made available?

**Comment by lucas-zimerman** [comment]
> Do you have an idea of what API you'd need to be made available?
I think only the basic functionalities would be enough (set user data like id, tags, captureMessage, maybe being able to add/remove data from the context?)

I have a sample code on how to capture a message and Set/Unset a tag
https://gist.github.com/lucas-zimerman/d46fdcd18c6acc9eb11169645e36ab23

https://gist.github.com/lucas-zimerman/22bf1426dd0204092f3defc27315427e

Not sure the best use case here, we/I could create a separated project with the required  code in order to use Sentry with that Tool or just document on Sentry docs on how to integrate Sentry Unity with Adventure Creator.

**Comment by bitsandfoxes** [comment]
Closing this as I think it's unlikely that we will build this integration.
