### ISSUE TITLE
0.18.0 sends Sentry.Unity.ApplicationNotResponding every time game goes background

### ISSUE THREAD

**Issue by pistoleta** [getsentry/sentry-unity#794]
Sentry Saas 0.18.0 installed via git
Unity 2020.3.33
iOS
(Editor didnt test)

EVERY time the game goes background I get this error on sentry.

-On IAP purchases
-Watching an AD
-Bring out iOS quick settings
-Bringing game to background (event is sent when coming back from background)

Happening JUST on 0.18.0

**Comment by bitsandfoxes** [comment]
Hey @pistoleta and thanks for raising this! We'll take a look!
