### ISSUE TITLE
Sentry SDK should be initialized using RuntimeInitializeOnLoadMethod

### ISSUE THREAD

**Issue by chrisse27** [getsentry/sentry-unity#8]
Sentry should be initialized as early as possible.

So the start method of a MonoBehaviour is pretty late in the lifecycle of a Unity app.

Please consider using [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html.

**Comment by chrisse27** [comment]
I will prepare an example implementation.

**Comment by bruno-garcia** [comment]
This seem like a good approach! Thanks for raising this.

**Comment by bruno-garcia** [comment]
@chrisse27 I made an experiment with a complete different approach (using the [.NET SDK](https://github.com/getsentry/sentry-dotnet) and also using the initialization method you propose.

Please take a look at #15

**Comment by chrisse27** [comment]
@bruno-garcia Will have a look this week.

**Comment by bruno-garcia** [comment]
Thank you for raising this issue. For that reason I've added init exactly as you described:

https://github.com/getsentry/sentry-unity/blob/e0ab5d4bb6700f4e5daabd3fb1d39115d1a770d1/src/sentry-dotnet-unity/Sentry.Unity/SentryInitialization.cs#L16

Some announcements here today: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222
