### ISSUE TITLE
Tune linker configuration to include only what's is required

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#81]
Should we revisit what is really needed in link.xml. Some of the rules added there were from 2018 when the Sentry SDK for .NET used `Newtonsoft.Json` with reflection. Now the serialization is mostly done manually. Only bits with reflection are what's set in `Event.Contexts` or `Event.Extra`.

**Comment by bitsandfoxes** [comment]
The package no longer ships with a `link.xml`.
