### ISSUE TITLE
Load SentryOptions json at build time and embed into the assembly

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#82]
An idea for discussion: Currently loading the json config is an I/O on the UI thread blocking the app start. It will likely not cause any noticeable slowdowns at least on fast/modern devices but one thing we could consider is to load SentryOptions json at build time and embed into the assembly

**Comment by bitsandfoxes** [comment]
Closed by https://github.com/getsentry/sentry-unity/pull/220
