### ISSUE TITLE
Come up with an approach for 'dev' mode in `Sentry.Unity.*` projects

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry-unity#83]
_We need to #ifdef or something so the test DSN only gets included in dev mode for the SDK. Meaning it shouldn't go into the unity package. (c)_

We don't have access to `Unity` preprocessor directives from `Sentry.Unity` projects. How should we decide if we're in 'dev' mode?

**Comment by bitsandfoxes** [comment]
We now compile `SentryInitialization.cs` with the actual game to give us access to those preprocessor directives.
