### ISSUE TITLE
ANR: Disable native in favor of C#

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#838]
We're currently missing an opt-out for ANR on the native layer. `RemoveIntegration<>` does not work since the setup for mobile happens during build time.

- [x] Android
- [x] iOS

**Comment by bruno-garcia** [comment]
There'll be App Hangs soon (ANR for ios) so we might need a flag per platform. Or a generic "ANR for native". Though the native ANR might not be useful in either case as it depends on UIKit / Activity 

Maybe we just turn it off and that's it?
