### ISSUE TITLE
SDK internal error logged through Debug.LogError

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#839]
We're logging an SDK internal error through the Unity logger here https://github.com/getsentry/sentry-unity/blob/6322d6b6e5701d8dad143eac0efe0453f1b84b20/src/Sentry.Unity.Android/SentryJava.cs#L154

`Error in SentryJava.ScopeCallback: UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='getContexts' signature='()Ljava/lang/Object;'`

https://sentry.io/organizations/sentry-sdks/issues/3369803070/?project=5439417&query=is%3Aunresolved

**Comment by vaind** [comment]
as explained in a call, the linked issue was created while I was working on the proguard support

as for the LogError - changing that to warning per Bruno's request https://github.com/getsentry/sentry-unity/pull/747#discussion_r903926267
