### ISSUE TITLE
Document SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#86]
Docs for how to contribute to the docs are here: https://docs.sentry.io/contributing/ Take a look at the Android docs for inspiration. It inherits from `Java` same as the `Unity` docs will inherit from the `.NET` SDK.

Docs should mention thsi version is still in preview and point to unity-lite (current docs) which can be a single page under the docs.

Raised in the docs repo: https://github.com/getsentry/sentry-docs/issues/3313

Main goal: 

* Inheriting from the dotnet docs
* Move current single-page unity-lite docs into a sub page.
* Mention this is a preview and we want feedback, and link to subpage/unity-lite as stable.
* Document setting things up with SentryWindow.

This is just the first iteration. We'll follow with reviewing the options and ajusting to what makes sense for Unity (say `CacheDirectoryPath` is set by default as opposed to the base config from dotnet with is not defined by default).

Going forward once we add the opt-out of Sentry Window in order to programatically set up the SDK: #66 we'll revisit the docs to consider both approaches.

example of preview note;

```
<Note>

This is a preview API available since 7.0.0-alpha.2. This API is not in stable state yet. It may change in the future.

</Note>
```

**Comment by semuserable** [comment]
PR is in a different repository: https://github.com/getsentry/sentry-docs/pull/3330

**Comment by semuserable** [comment]
Initial version merged https://github.com/getsentry/sentry-docs/pull/3330. Closing.
