### ISSUE TITLE
IL2CPP line numbers

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#895]
Issue tracking the current IL2CPP line number support coverage:
IL2CPP line number support is currently an experimental feature: `Tools -> Sentry -> Advanced -> IL2CPP Line Numbers`.

- [x] Android
  - [x] 2020 - https://github.com/getsentry/sentry-unity/pull/872
  - [x] 2021
- [x] iOS
  - [x] 2020
  - [x] 2021
- [x] macOS
  - [x] 2020
  - [x] 2021
- [x] Windows
  - [x] 2020 - 
  - [x] 2021
- [x] Linux
  - [x] 2020
  - [x] 2021
- [ ] WebGL - IL2CPP methods not found in build
  - [ ] 2020
  - [ ] 2021

**Comment by vaind** [comment]
I'm having trouble running this on iOS - always getting il2cppmethods is null (defined here: https://github.com/getsentry/sentry-unity/blob/27d2de0974115faddcdda7ba7de3aa52224ab579/package-dev/Runtime/SentryInitialization.cs#L109)

**Comment by vaind** [comment]
TODO
* [ ] update integration test (SmokeTester.cs) to check the captured exceptions - they must contain line numbers.

**Comment by bitsandfoxes** [comment]
For smoketesting I thought we could do:

- [ ] Check that this log doesn't show up in builds where it should work: https://github.com/getsentry/sentry-unity/blob/aedaed6b699c88161cccdfdd659f4fd03c9a433a/src/Sentry.Unity/SentryUnityOptionsExtensions.cs#L74 - verifies the logic in SentryInitialization
- [ ] Check that event contains `debug_meta`

**Comment by bitsandfoxes** [comment]
Closed by https://github.com/getsentry/sentry-unity/pull/1165
Possible integration test for IL2CPP tracked by https://github.com/getsentry/sentry-unity/issues/1177
