### ISSUE TITLE
Exceptions should not be sent when in editor mode

### ISSUE THREAD

**Issue by chrisse27** [getsentry/sentry-unity#9]
Quite often I am not interested in exceptions that are thrown during development. However, if I have a SentrySdk instance in my scene, even compiler errors will be sent to Sentry.

There should be at least a flag that prevents this.

**Comment by samuelgoldenbaum** [comment]
I guess you can wrap in unity precompilation tags for now.
```
#if !UNITY_EDITOR
            sentry.gameObject.SetActive (false);
#endif
```

**Comment by bruno-garcia** [comment]
Thanks for raising this. Because of this issue the new code in the `main` branch has a checkbox in the editor to opt-out of capturing errors in the editor.

There's more context here: https://forum.sentry.io/t/unity-sdk-lite-vs-native-support/12222
