### ISSUE TITLE
Capture Minidumps from Windows players

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#94]
This issue will track adding support for Minidumps on Windows builds.

One approach is to bundle [`sentry-native`](https://github.com/getsentry/sentry-native) with a `crashpad` backend. That would not only add minidump support but the Sentry SDK API so users can add tags and other data to crashes using Sentry's SDK. [This project provides Sentry's native SDK bundled in a NuGet package](https://github.com/getsentry/sentry-dotnet-minidump).

**Comment by LukasKastern** [comment]
I've demonstrated another approach in [this sample](https://github.com/LukasKastern/SentryCrashListener) 
The sample I linked shows how a .net 5 app can be used to track Unity's crash handler.

That way we can use the dump and logs that unity already generates when the game crashes and forward those to sentry.

**Comment by bruno-garcia** [comment]
I believe the SDk already captures minidump after #380 and we're just missing some extra features like symbol upload:

See #527
