### ISSUE TITLE
Add iOS 12.0 to smoke testing

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#946]
Due to excessive flakiness, iOS 12.0 got removed from smoke testing and should be put back in.
12.0 is the lowest supported version even in Unity 2022.

**Comment by vaind** [comment]
iOS 12 has a very low market share at this time, so while it's still officially supported for now, we can keep it as is (CI disabled due to flakiness) and if an issue comes up, we can revisit this.
