### ISSUE TITLE
Support native Android crashes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#95]
A player built for Android can fail with Java/Kotlin or with native (NDK). [Sentry's Android SDK ](https://github.com/getsentry/sentry-java) supports both. And [Sentry's gradle plugin](https://github.com/getsentry/sentry-android-gradle-plugin) can upload proguard/R8 files of minified builds.

`sentry-android` would also give support for release health, given crashes and errors were communicated downstream by the .NET SDK to reflect in the sessions.

In terms of adding it to this project, we could consider `git submodule` or `gradle` with their pros and cons. Perhaps more easily is to rely on gradle (if we can inject gradle dependencies through UPM) but for development it's easier to bring it in as submodule.

The gradle approach was used in the [MVP demo'd on this video](https://www.youtube.com/watch?v=bHc4QMlV8bM). It was using the [gradle template approach](https://github.com/getsentry/sentry-unity/tree/43025e68c06b337500a95a20eb87852f910cb5fb/sentry-unity/Assets/Plugins/Android).

The original MVP of this project included native Android support. As prepare the project to be the new official SDK we decided to start off with the .NET-only API and add Android on a following iteration.
This issue tracks adding `sentry-android`.

Delete until needed for Android:

https://github.com/getsentry/sentry-unity/blob/fd4a26e239d18865f1c947e3551178a1cde00120/src/Sentry.Unity.Editor/AndroidManifestConfiguration.cs

**Comment by canyousayyes** [comment]
Hello. Based on the issue, does it mean that Sentry-Unity cannot capture any native crashes at this moment?
Do you have any updates and ETA for the native Android crash support?

**Comment by bruno-garcia** [comment]
@canyousayyes we plan to ship this in Q3. Currently you can add the sentry-android SDK directly via gradle and it will capture native crashes. We will just make the integration easier to install and from there share some extra context data between the C# and Java/NDK layers.

**Comment by canyousayyes** [comment]
Thanks for the info. Just noticed there's also #164 , does that mean we also need to install sentry-cocoa ourselves to capture native crashes on iOS side?

If we want to:

- Capture exceptions in Unity
- Send custom error events in Unity
- Capture native crashes

on both Android and iOS platforms,

We need both Unity-sentry for the first 2 use cases, and (sentry-android + sentry-cocoa) for the third one. Is my understanding is correct?

**Comment by bruno-garcia** [comment]
> We need both Unity-sentry for the first 2 use cases, and (sentry-android + sentry-cocoa) for the third one. Is my understanding correct?

That's right.
We'll bundle it all for you and make sure the native layer is initialized automatically too. This is coming in the next few months.
