### ISSUE TITLE
Use cocoa's `PrivateSentrySDKOnly` to set SDK name

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#950]
![image](https://user-images.githubusercontent.com/1633368/186264089-ca6b59f2-f8df-41de-b022-9b0bbf34db2c.png)

Using the latest version 0.22.2

**Comment by bitsandfoxes** [comment]
We should add a check to the smoke test to make sure it does not go missing again.

**Comment by vaind** [comment]
`PrivateSentrySDKOnly` should now be used: https://github.com/getsentry/sentry-cocoa/pull/1960/files#diff-321979279232433e004cfdaab6ac97727ac4aead9a53d2cd77637084d9208277R47

**Comment by bitsandfoxes** [comment]
Closing this as fixed.
