### ISSUE TITLE
Sentry not send error after network restored

### ISSUE THREAD

**Issue by whatisor** [getsentry/sentry-unity#951]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 
Which version of the SDK? 0.22.2

How did you install the package? (Git-URL,)

Which version of Unity?
2020.3.37f1
Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android
### Steps to Reproduce

1. Start application
2. Disconnect wifi
3. Reconnect wifi
4. Wait for network restored.

### Expected Result

Sentry should send error after network restored. OR at least ,we can reconnect/send manually by Sentry api after network is restored.

### Actual Result

Nothing sent until we restart application.

**Comment by bitsandfoxes** [comment]
Hey @whatisor, thanks for raising this. Just to double-check:
1. App start
2. Disconnect wifi
3. An error happens
4. Reconnect
5. The error does not get sent to Sentry?

**Comment by lucas-zimerman** [comment]
Just an idea but what if FlushAsync would also flush envelopes stored offline?

**Comment by bitsandfoxes** [comment]
Currently, the SDK does not automatically send cached to disk events when coming back online. It will send them once a new one gets sent when the device is back online again. 

We're tracking this as a feature request of the .NET SDK here: https://github.com/getsentry/sentry-dotnet/issues/1882

**Comment by mattjohnsonpint** [comment]
> Just an idea but what if FlushAsync would also flush envelopes stored offline?

That's a good idea.  `CachingTransport.FlushAsync` already exists, but it isn't called from `BackgroundWorker.FlushAsync` (which is called by `SentryClient.FlushAsync`).

We can get that done faster than the other.

**Comment by whatisor** [comment]
yes, for now, I overcome it by listening network event and control an separated cache for those event.

**Comment by whatisor** [comment]
the most simple change should be:
+ current Flush should check if cache is not empty and send them. Then user can listen to network status and flush in need.

better is FlushAsync which auto-listen to network event, user is free.
